-- 回滚以模型为中心的供给改造。
--
-- 注意：route 三表与 user_model_policies 的数据无法恢复，本回滚只重建结构。
-- 重建后 routes 为空，api_keys.route_id 无法回填，需要人工重新配置线路与绑定。

-- ── 5. 重建 route 与用户模型策略 ─────────────────────────────────────────────
CREATE TABLE routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    mode TEXT NOT NULL,
    status TEXT NOT NULL,
    description TEXT,
    price_ratio NUMERIC(20, 10) NOT NULL DEFAULT 1.0,
    rpm_limit INTEGER,
    rpd_limit INTEGER,
    concurrency_limit INTEGER,
    sticky_enabled BOOLEAN,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE route_channels (
    route_id bigint NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    channel_id bigint NOT NULL REFERENCES channels(id),
    PRIMARY KEY (route_id, channel_id)
);
CREATE INDEX idx_route_channels_channel ON route_channels (channel_id);

CREATE TABLE route_model_offerings (
    route_id bigint NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    model_id bigint NOT NULL REFERENCES models(id),
    ingress_protocol TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (route_id, model_id, ingress_protocol)
);

CREATE TABLE user_model_policies (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    model_id bigint NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    visibility TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, model_id)
);

ALTER TABLE api_keys ADD COLUMN route_id bigint REFERENCES routes(id);
ALTER TABLE request_records ADD COLUMN route_id bigint;
ALTER TABLE routing_decision_traces ADD COLUMN route_id bigint;

-- ── 4. 目录元数据 ────────────────────────────────────────────────────────────
DROP TABLE model_labs;
ALTER TABLE models DROP COLUMN family;

ALTER TABLE models
    DROP CONSTRAINT ck_models_disabled_reason,
    DROP COLUMN disabled_reason,
    DROP COLUMN disabled_at;

-- ── 5. 限流默认值设置正名 ────────────────────────────────────────────────────
ALTER TABLE runtime_control_operations
    DROP CONSTRAINT ck_runtime_control_operations_target;

UPDATE runtime_control_operations
SET setting_key = 'gateway.route_rate_limit_defaults'
WHERE setting_key = 'gateway.request_rate_limit_defaults';

ALTER TABLE runtime_control_operations
    ADD CONSTRAINT ck_runtime_control_operations_target CHECK (
        ((kind = 'channel_capacity'::text) AND (channel_id IS NOT NULL) AND (setting_key IS NULL))
        OR ((kind = 'app_setting'::text) AND (channel_id IS NULL) AND (setting_key = ANY (ARRAY[
            'gateway.route_rate_limit_defaults'::text,
            'gateway.concurrency_defaults'::text,
            'gateway.circuit_breaker'::text,
            'gateway.routing_balance'::text
        ])))
        OR ((kind = 'runtime_state_epoch'::text) AND (channel_id IS NULL)
            AND (setting_key = 'gateway.runtime_state_epoch'::text))
    );

UPDATE app_settings
SET key = 'gateway.route_rate_limit_defaults'
WHERE key = 'gateway.request_rate_limit_defaults';

-- ── 3. 模型级售价 ────────────────────────────────────────────────────────────
DELETE FROM app_settings WHERE key = 'gateway.model_sale_price_ratio';

ALTER TABLE model_price_service_tiers
    DROP CONSTRAINT ck_model_price_tiers_sale_all_or_none,
    DROP CONSTRAINT ck_model_price_tiers_sale_non_negative,
    DROP COLUMN sale_uncached_input_price,
    DROP COLUMN sale_cache_read_input_price,
    DROP COLUMN sale_cache_write_5m_input_price,
    DROP COLUMN sale_cache_write_1h_input_price,
    DROP COLUMN sale_cache_write_30m_input_price,
    DROP COLUMN sale_output_price,
    DROP COLUMN sale_reasoning_output_price;

ALTER TABLE model_prices
    DROP CONSTRAINT ck_model_prices_sale_all_or_none,
    DROP CONSTRAINT ck_model_prices_sale_non_negative,
    DROP COLUMN sale_uncached_input_price,
    DROP COLUMN sale_cache_read_input_price,
    DROP COLUMN sale_cache_write_5m_input_price,
    DROP COLUMN sale_cache_write_1h_input_price,
    DROP COLUMN sale_cache_write_30m_input_price,
    DROP COLUMN sale_output_price,
    DROP COLUMN sale_reasoning_output_price;

-- ── 2. 限流 ──────────────────────────────────────────────────────────────────
ALTER TABLE users
    DROP CONSTRAINT ck_users_concurrency_limit_non_negative,
    DROP CONSTRAINT ck_users_rpd_limit_non_negative,
    DROP CONSTRAINT ck_users_rpm_limit_non_negative,
    DROP COLUMN concurrency_limit,
    DROP COLUMN rpd_limit,
    DROP COLUMN rpm_limit;

-- ── 1. 渠道协议 ──────────────────────────────────────────────────────────────
ALTER TABLE channels ADD COLUMN protocol TEXT NOT NULL DEFAULT 'openai';
UPDATE channels SET protocol = protocols[1] WHERE cardinality(protocols) > 0;
ALTER TABLE channels ALTER COLUMN protocol DROP DEFAULT;
ALTER TABLE channels
    DROP CONSTRAINT ck_channels_protocols_known,
    DROP CONSTRAINT ck_channels_protocols_non_empty,
    DROP COLUMN protocols;
ALTER TABLE channels ADD CONSTRAINT channels_protocol_check
    CHECK (protocol = ANY (ARRAY['openai'::text, 'anthropic'::text]));
