-- 模型出品方：承载厂商图标，供前端在模型列表旁展示。
CREATE TABLE public.model_labs (
    -- id: 主键。--
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    -- slug: 出品方标识，与 models.owned_by 取值一致。--
    slug text NOT NULL,
    -- name: 展示名；目录同步时暂用 slug 填充。--
    name text NOT NULL,
    -- logo_svg: 图标的 SVG 内容；空串表示尚未同步到。--
    logo_svg text DEFAULT ''::text NOT NULL,
    -- logo_synced_at: 图标最近一次同步时间；NULL 表示从未同步。--
    logo_synced_at timestamp with time zone,
    -- created_at: 记录创建时间。--
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    -- updated_at: 记录更新时间。--
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_model_labs_logo_svg CHECK (((logo_svg = ''::text) OR (logo_svg ~~ '%<svg%'::text)))
);

ALTER TABLE ONLY public.model_labs
    ADD CONSTRAINT model_labs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.model_labs
    ADD CONSTRAINT model_labs_slug_key UNIQUE (slug);

COMMENT ON TABLE public.model_labs IS '模型出品方（models.dev 的 lab），与 models.owned_by 按 slug 关联，不设外键：owned_by 是 OpenAI 兼容契约字段，必须保持字符串形态。';

-- ---------------------------------------------------------------------------
-- 存 SVG 内容而非 URL：图标属于展示不能挂的部分，让用户浏览器直连第三方既慢也多一个
-- 失效来源。CHECK 只做最粗的形态校验，挡住把 URL 或图片二进制填进来的情况。
--
-- 表内容由目录同步（models.dev feed）负责填充与补图标，迁移不预置任何行：
-- 只在手建模型里出现过的 owned_by 不会自动建行，那只影响图标展示，不影响功能。
-- ---------------------------------------------------------------------------
