// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminMessages = `-- name: CountAdminMessages :one
SELECT COUNT(*) AS total
FROM admin_messages
WHERE (NOT $1::boolean OR read_at IS NULL)
  AND ($2::text IS NULL OR topic = $2::text)
`

type CountAdminMessagesParams struct {
	UnreadOnly bool
	Topic      pgtype.Text
}

// CountAdminMessages 统计与 ListAdminMessagesPage 同口径的总数（分页 meta 用）。
func (q *Queries) CountAdminMessages(ctx context.Context, arg CountAdminMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminMessages, arg.UnreadOnly, arg.Topic)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUnreadAdminMessages = `-- name: CountUnreadAdminMessages :one
SELECT COUNT(*) AS total
FROM admin_messages
WHERE read_at IS NULL
`

// CountUnreadAdminMessages 未读总数（admin 顶栏铃铛轮询，命中未读部分索引）。
func (q *Queries) CountUnreadAdminMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadAdminMessages)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAdminMessage = `-- name: CreateAdminMessage :execrows
INSERT INTO admin_messages (severity, topic, title, body, source, dedupe_key)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (dedupe_key) WHERE read_at IS NULL DO NOTHING
`

type CreateAdminMessageParams struct {
	Severity  string
	Topic     string
	Title     string
	Body      string
	Source    string
	DedupeKey pgtype.Text
}

// CreateAdminMessage 写入一条站内消息。dedupe_key 非空且已存在同 key 未读消息时静默跳过
// （命中部分唯一索引 uq_admin_messages_unread_dedupe，DO NOTHING），返回受影响行数 0；
// 用于周期性 worker 告警防重复轰炸。
func (q *Queries) CreateAdminMessage(ctx context.Context, arg CreateAdminMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAdminMessage,
		arg.Severity,
		arg.Topic,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.DedupeKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAdminMessagesPage = `-- name: ListAdminMessagesPage :many
SELECT id, severity, topic, title, body, source, dedupe_key, created_at, read_at
FROM admin_messages
WHERE (NOT $1::boolean OR read_at IS NULL)
  AND ($2::text IS NULL OR topic = $2::text)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListAdminMessagesPageParams struct {
	UnreadOnly bool
	Topic      pgtype.Text
	PageOffset int32
	PageLimit  int32
}

// ListAdminMessagesPage 分页列出站内消息（新消息在前），可选只看未读、按 topic 过滤。
func (q *Queries) ListAdminMessagesPage(ctx context.Context, arg ListAdminMessagesPageParams) ([]AdminMessage, error) {
	rows, err := q.db.Query(ctx, listAdminMessagesPage,
		arg.UnreadOnly,
		arg.Topic,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminMessage
	for rows.Next() {
		var i AdminMessage
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.Topic,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.DedupeKey,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAdminMessageRead = `-- name: MarkAdminMessageRead :one
UPDATE admin_messages
SET read_at = COALESCE(read_at, now())
WHERE id = $1
RETURNING id, severity, topic, title, body, source, dedupe_key, created_at, read_at
`

// MarkAdminMessageRead 幂等标记单条消息已读（重复标记保留首次 read_at），返回更新后的行；id 不存在时无行。
func (q *Queries) MarkAdminMessageRead(ctx context.Context, id int64) (AdminMessage, error) {
	row := q.db.QueryRow(ctx, markAdminMessageRead, id)
	var i AdminMessage
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.Topic,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.DedupeKey,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const markAllAdminMessagesRead = `-- name: MarkAllAdminMessagesRead :execrows
UPDATE admin_messages
SET read_at = now()
WHERE read_at IS NULL
`

// MarkAllAdminMessagesRead 把全部未读消息标记为已读，返回标记条数。
func (q *Queries) MarkAllAdminMessagesRead(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markAllAdminMessagesRead)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
