// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAPIKeySpentTotal = `-- name: AddAPIKeySpentTotal :exec
UPDATE api_keys
SET spent_total = spent_total + $1, updated_at = now()
WHERE id = $2
`

type AddAPIKeySpentTotalParams struct {
	Amount pgtype.Numeric
	ID     int64
}

// AddAPIKeySpentTotal 在 settlement capture 时累加该 Key 的累计花费（M7 费用上限计数器）。
func (q *Queries) AddAPIKeySpentTotal(ctx context.Context, arg AddAPIKeySpentTotalParams) error {
	_, err := q.db.Exec(ctx, addAPIKeySpentTotal, arg.Amount, arg.ID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.user_id, k.name, k.key_prefix, k.key_hash, k.last_used_at, k.expires_at, k.disabled_at, k.revoked_at, k.created_at, k.updated_at,
       (k.spend_limit IS NOT NULL AND k.spent_total >= k.spend_limit) AS spend_limit_reached,
       u.rpm_limit AS user_rpm_limit,
       u.rpd_limit AS user_rpd_limit,
       u.concurrency_limit AS user_concurrency_limit
FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE key_hash = $1
LIMIT 1
`

type GetAPIKeyByHashRow struct {
	ID                   int64
	UserID               int64
	Name                 string
	KeyPrefix            string
	KeyHash              string
	LastUsedAt           pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	DisabledAt           pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	SpendLimitReached    pgtype.Bool
	UserRpmLimit         pgtype.Int4
	UserRpdLimit         pgtype.Int4
	UserConcurrencyLimit pgtype.Int4
}

// GetAPIKeyByHash 按 key hash 读取 API Key，带出所属用户 ID 与用户级限流，并计算是否已达费用上限。
// spend_limit_reached 在 SQL 层判定，避免认证路径在 Go 里做 NUMERIC 比较（M7 费用上限闸门）。
// 限流上限（rpm/rpd/concurrency）取自所属用户（按用户计数）：同一用户的多把 Key 共享配额。
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpendLimitReached,
		&i.UserRpmLimit,
		&i.UserRpdLimit,
		&i.UserConcurrencyLimit,
	)
	return i, err
}

const updateAPIKeyLastUsedAt = `-- name: UpdateAPIKeyLastUsedAt :exec
UPDATE api_keys
SET last_used_at = $1, updated_at = now()
WHERE id = $2
`

type UpdateAPIKeyLastUsedAtParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         int64
}

// UpdateAPIKeyLastUsedAt 更新 API Key 最近使用时间。
func (q *Queries) UpdateAPIKeyLastUsedAt(ctx context.Context, arg UpdateAPIKeyLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsedAt, arg.LastUsedAt, arg.ID)
	return err
}
