// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeConsolePasswordIfSet = `-- name: ChangeConsolePasswordIfSet :execrows
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
  AND password_hash IS NOT NULL
`

type ChangeConsolePasswordIfSetParams struct {
	PasswordHash pgtype.Text
	ID           int64
}

func (q *Queries) ChangeConsolePasswordIfSet(ctx context.Context, arg ChangeConsolePasswordIfSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeConsolePasswordIfSet, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consoleActiveEmailExists = `-- name: ConsoleActiveEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE lower(email) = lower($1)
      AND status = 'active'
)
`

func (q *Queries) ConsoleActiveEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, consoleActiveEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consoleRegistrationEmailExists = `-- name: ConsoleRegistrationEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE lower(email) = lower($1)
)
`

func (q *Queries) ConsoleRegistrationEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, consoleRegistrationEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createConsoleUser = `-- name: CreateConsoleUser :one
INSERT INTO users (uid, email, password_hash, display_name, status)
VALUES ($1, $2, $3, $4, 'active')
RETURNING id, uid, email, password_hash, display_name, status, created_at, updated_at
`

type CreateConsoleUserParams struct {
	Uid          pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	DisplayName  string
}

type CreateConsoleUserRow struct {
	ID           int64
	Uid          pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateConsoleUser(ctx context.Context, arg CreateConsoleUserParams) (CreateConsoleUserRow, error) {
	row := q.db.QueryRow(ctx, createConsoleUser,
		arg.Uid,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i CreateConsoleUserRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConsoleUserByEmail = `-- name: GetConsoleUserByEmail :one
SELECT id, uid, email, password_hash, display_name, status, created_at, updated_at
FROM users
WHERE lower(email) = lower($1)
LIMIT 1
`

type GetConsoleUserByEmailRow struct {
	ID           int64
	Uid          pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetConsoleUserByEmail(ctx context.Context, email string) (GetConsoleUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getConsoleUserByEmail, email)
	var i GetConsoleUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConsoleUserByUID = `-- name: GetConsoleUserByUID :one
SELECT id, uid, email, password_hash, display_name, status, created_at, updated_at
FROM users
WHERE uid = $1
LIMIT 1
`

type GetConsoleUserByUIDRow struct {
	ID           int64
	Uid          pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetConsoleUserByUID(ctx context.Context, uid pgtype.UUID) (GetConsoleUserByUIDRow, error) {
	row := q.db.QueryRow(ctx, getConsoleUserByUID, uid)
	var i GetConsoleUserByUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConsolePasswordIfUnset = `-- name: SetConsolePasswordIfUnset :execrows
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
  AND password_hash IS NULL
`

type SetConsolePasswordIfUnsetParams struct {
	PasswordHash pgtype.Text
	ID           int64
}

func (q *Queries) SetConsolePasswordIfUnset(ctx context.Context, arg SetConsolePasswordIfUnsetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setConsolePasswordIfUnset, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateConsoleDisplayName = `-- name: UpdateConsoleDisplayName :one
UPDATE users
SET display_name = $1, updated_at = now()
WHERE id = $2
RETURNING id, uid, email, password_hash, display_name, status, created_at, updated_at
`

type UpdateConsoleDisplayNameParams struct {
	DisplayName string
	ID          int64
}

type UpdateConsoleDisplayNameRow struct {
	ID           int64
	Uid          pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateConsoleDisplayName(ctx context.Context, arg UpdateConsoleDisplayNameParams) (UpdateConsoleDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateConsoleDisplayName, arg.DisplayName, arg.ID)
	var i UpdateConsoleDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConsolePassword = `-- name: UpdateConsolePassword :one
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
RETURNING id, uid, email, password_hash, display_name, status, created_at, updated_at
`

type UpdateConsolePasswordParams struct {
	PasswordHash pgtype.Text
	ID           int64
}

type UpdateConsolePasswordRow struct {
	ID           int64
	Uid          pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateConsolePassword(ctx context.Context, arg UpdateConsolePasswordParams) (UpdateConsolePasswordRow, error) {
	row := q.db.QueryRow(ctx, updateConsolePassword, arg.PasswordHash, arg.ID)
	var i UpdateConsolePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
