// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cdkey_exports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportCDKeysByFilter = `-- name: ExportCDKeysByFilter :many
SELECT
    c.id,
    c.batch_id,
    c.code_plaintext,
    c.amount,
    c.currency,
    c.status,
    c.created_at,
    c.redeemed_at,
    c.revoked_at,
    r.user_id AS redemption_user_id,
    u.email AS redemption_user_email,
    r.ledger_entry_id AS redemption_ledger_entry_id,
    r.redeemed_at AS redemption_redeemed_at
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE c.status = ANY($1::text[])
  AND NOT (c.id = ANY($2::bigint[]))
  AND ($3::numeric IS NULL OR c.amount = $3::numeric)
  AND ($4::uuid IS NULL OR c.batch_id = $4::uuid)
  AND ($5::text IS NULL OR (
      c.code_prefix ILIKE '%' || $5::text || '%'
      OR c.code_suffix ILIKE '%' || $5::text || '%'
      OR c.batch_id::text ILIKE '%' || $5::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $5::text || '%'
      OR COALESCE(r.user_id::text, '') ILIKE '%' || $5::text || '%'
  ))
  AND ($6::timestamptz IS NULL OR c.created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR c.created_at < $7::timestamptz)
ORDER BY c.id
`

type ExportCDKeysByFilterParams struct {
	Statuses   []string
	ExcludeIds []int64
	Amount     pgtype.Numeric
	BatchID    pgtype.UUID
	Search     pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

type ExportCDKeysByFilterRow struct {
	ID                      int64
	BatchID                 pgtype.UUID
	CodePlaintext           string
	Amount                  pgtype.Numeric
	Currency                string
	Status                  string
	CreatedAt               pgtype.Timestamptz
	RedeemedAt              pgtype.Timestamptz
	RevokedAt               pgtype.Timestamptz
	RedemptionUserID        pgtype.Int8
	RedemptionUserEmail     pgtype.Text
	RedemptionLedgerEntryID pgtype.Int8
	RedemptionRedeemedAt    pgtype.Timestamptz
}

func (q *Queries) ExportCDKeysByFilter(ctx context.Context, arg ExportCDKeysByFilterParams) ([]ExportCDKeysByFilterRow, error) {
	rows, err := q.db.Query(ctx, exportCDKeysByFilter,
		arg.Statuses,
		arg.ExcludeIds,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportCDKeysByFilterRow
	for rows.Next() {
		var i ExportCDKeysByFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CodePlaintext,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.RedeemedAt,
			&i.RevokedAt,
			&i.RedemptionUserID,
			&i.RedemptionUserEmail,
			&i.RedemptionLedgerEntryID,
			&i.RedemptionRedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCDKeysByIDs = `-- name: ExportCDKeysByIDs :many

SELECT
    c.id,
    c.batch_id,
    c.code_plaintext,
    c.amount,
    c.currency,
    c.status,
    c.created_at,
    c.redeemed_at,
    c.revoked_at,
    r.user_id AS redemption_user_id,
    u.email AS redemption_user_email,
    r.ledger_entry_id AS redemption_ledger_entry_id,
    r.redeemed_at AS redemption_redeemed_at
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE c.id = ANY($1::bigint[])
  AND c.status = ANY($2::text[])
  AND NOT (c.id = ANY($3::bigint[]))
ORDER BY c.id
`

type ExportCDKeysByIDsParams struct {
	Ids        []int64
	Statuses   []string
	ExcludeIds []int64
}

type ExportCDKeysByIDsRow struct {
	ID                      int64
	BatchID                 pgtype.UUID
	CodePlaintext           string
	Amount                  pgtype.Numeric
	Currency                string
	Status                  string
	CreatedAt               pgtype.Timestamptz
	RedeemedAt              pgtype.Timestamptz
	RevokedAt               pgtype.Timestamptz
	RedemptionUserID        pgtype.Int8
	RedemptionUserEmail     pgtype.Text
	RedemptionLedgerEntryID pgtype.Int8
	RedemptionRedeemedAt    pgtype.Timestamptz
}

// Export is the only Admin query that intentionally selects code_plaintext.
// The HTTP layer streams this result after AdminAuth; it never wraps it in JSON.
func (q *Queries) ExportCDKeysByIDs(ctx context.Context, arg ExportCDKeysByIDsParams) ([]ExportCDKeysByIDsRow, error) {
	rows, err := q.db.Query(ctx, exportCDKeysByIDs, arg.Ids, arg.Statuses, arg.ExcludeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportCDKeysByIDsRow
	for rows.Next() {
		var i ExportCDKeysByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CodePlaintext,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.RedeemedAt,
			&i.RevokedAt,
			&i.RedemptionUserID,
			&i.RedemptionUserEmail,
			&i.RedemptionLedgerEntryID,
			&i.RedemptionRedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
