// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cdkeys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCDKeyBatches = `-- name: CountCDKeyBatches :one
SELECT COUNT(DISTINCT c.batch_id)::bigint AS total
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE c.status <> 'revoked'
  AND (cardinality($1::text[]) = 0 OR c.status = ANY($1::text[]))
  AND ($2::numeric IS NULL OR c.amount = $2::numeric)
  AND ($3::uuid IS NULL OR c.batch_id = $3::uuid)
  AND ($4::text IS NULL OR (
      c.code_prefix ILIKE '%' || $4::text || '%'
      OR c.code_suffix ILIKE '%' || $4::text || '%'
      OR c.batch_id::text ILIKE '%' || $4::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $4::text || '%'
      OR COALESCE(r.user_id::text, '') ILIKE '%' || $4::text || '%'
  ))
  AND ($5::timestamptz IS NULL OR c.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR c.created_at < $6::timestamptz)
`

type CountCDKeyBatchesParams struct {
	Statuses []string
	Amount   pgtype.Numeric
	BatchID  pgtype.UUID
	Search   pgtype.Text
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

func (q *Queries) CountCDKeyBatches(ctx context.Context, arg CountCDKeyBatchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCDKeyBatches,
		arg.Statuses,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCDKeyRedemptions = `-- name: CountCDKeyRedemptions :one
SELECT COUNT(*) AS total
FROM cdkey_redemptions r
JOIN cdkeys c ON c.id = r.cdkey_id
JOIN users u ON u.id = r.user_id
WHERE ($1::bigint IS NULL OR r.user_id = $1::bigint)
  AND ($2::text IS NULL OR (
      c.code_prefix ILIKE '%' || $2::text || '%'
      OR c.code_suffix ILIKE '%' || $2::text || '%'
      OR c.batch_id::text ILIKE '%' || $2::text || '%'
      OR u.email ILIKE '%' || $2::text || '%'
      OR r.user_id::text ILIKE '%' || $2::text || '%'
  ))
  AND ($3::numeric IS NULL OR r.amount = $3::numeric)
  AND ($4::timestamptz IS NULL OR r.redeemed_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR r.redeemed_at < $5::timestamptz)
`

type CountCDKeyRedemptionsParams struct {
	UserID   pgtype.Int8
	Search   pgtype.Text
	Amount   pgtype.Numeric
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

func (q *Queries) CountCDKeyRedemptions(ctx context.Context, arg CountCDKeyRedemptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCDKeyRedemptions,
		arg.UserID,
		arg.Search,
		arg.Amount,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCDKeys = `-- name: CountCDKeys :one
SELECT COUNT(*) AS total
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE (cardinality($1::text[]) = 0 OR c.status = ANY($1::text[]))
  AND ($2::numeric IS NULL OR c.amount = $2::numeric)
  AND ($3::uuid IS NULL OR c.batch_id = $3::uuid)
  AND ($4::text IS NULL OR (
      c.code_prefix ILIKE '%' || $4::text || '%'
      OR c.code_suffix ILIKE '%' || $4::text || '%'
      OR c.batch_id::text ILIKE '%' || $4::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $4::text || '%'
      OR COALESCE(r.user_id::text, '') ILIKE '%' || $4::text || '%'
  ))
  AND ($5::timestamptz IS NULL OR c.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR c.created_at < $6::timestamptz)
`

type CountCDKeysParams struct {
	Statuses []string
	Amount   pgtype.Numeric
	BatchID  pgtype.UUID
	Search   pgtype.Text
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

func (q *Queries) CountCDKeys(ctx context.Context, arg CountCDKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCDKeys,
		arg.Statuses,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCDKey = `-- name: CreateCDKey :one

INSERT INTO cdkeys (
    batch_id, code_plaintext, code_hash, code_prefix, code_suffix,
    amount, currency, status
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING id, batch_id, code_plaintext, code_hash, code_prefix, code_suffix,
          amount, currency, status, created_at, redeemed_at, revoked_at
`

type CreateCDKeyParams struct {
	BatchID       pgtype.UUID
	CodePlaintext string
	CodeHash      string
	CodePrefix    string
	CodeSuffix    string
	Amount        pgtype.Numeric
	Currency      string
	Status        string
}

// CDKEY core queries shared by admin generation and console redemption.
func (q *Queries) CreateCDKey(ctx context.Context, arg CreateCDKeyParams) (Cdkey, error) {
	row := q.db.QueryRow(ctx, createCDKey,
		arg.BatchID,
		arg.CodePlaintext,
		arg.CodeHash,
		arg.CodePrefix,
		arg.CodeSuffix,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	var i Cdkey
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CodePlaintext,
		&i.CodeHash,
		&i.CodePrefix,
		&i.CodeSuffix,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.RedeemedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createCDKeyRedemption = `-- name: CreateCDKeyRedemption :one
INSERT INTO cdkey_redemptions (
    cdkey_id, user_id, amount, currency, ledger_entry_id, idempotency_key, redeemed_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, cdkey_id, user_id, amount, currency, ledger_entry_id, idempotency_key, redeemed_at
`

type CreateCDKeyRedemptionParams struct {
	CdkeyID        int64
	UserID         int64
	Amount         pgtype.Numeric
	Currency       string
	LedgerEntryID  int64
	IdempotencyKey string
	RedeemedAt     pgtype.Timestamptz
}

func (q *Queries) CreateCDKeyRedemption(ctx context.Context, arg CreateCDKeyRedemptionParams) (CdkeyRedemption, error) {
	row := q.db.QueryRow(ctx, createCDKeyRedemption,
		arg.CdkeyID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.LedgerEntryID,
		arg.IdempotencyKey,
		arg.RedeemedAt,
	)
	var i CdkeyRedemption
	err := row.Scan(
		&i.ID,
		&i.CdkeyID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.LedgerEntryID,
		&i.IdempotencyKey,
		&i.RedeemedAt,
	)
	return i, err
}

const deleteCDKey = `-- name: DeleteCDKey :execrows
DELETE FROM cdkeys
WHERE id = $1
`

func (q *Queries) DeleteCDKey(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCDKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCDKeyBatchSummary = `-- name: GetCDKeyBatchSummary :many
WITH filtered AS (
    SELECT c.batch_id, c.amount, c.status
    FROM cdkeys c
    LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
    LEFT JOIN users u ON u.id = r.user_id
    WHERE c.status <> 'revoked'
      AND (cardinality($1::text[]) = 0 OR c.status = ANY($1::text[]))
      AND ($2::numeric IS NULL OR c.amount = $2::numeric)
      AND ($3::uuid IS NULL OR c.batch_id = $3::uuid)
      AND ($4::text IS NULL OR (
          c.code_prefix ILIKE '%' || $4::text || '%'
          OR c.code_suffix ILIKE '%' || $4::text || '%'
          OR c.batch_id::text ILIKE '%' || $4::text || '%'
          OR COALESCE(u.email, '') ILIKE '%' || $4::text || '%'
          OR COALESCE(r.user_id::text, '') ILIKE '%' || $4::text || '%'
      ))
      AND ($5::timestamptz IS NULL OR c.created_at >= $5::timestamptz)
      AND ($6::timestamptz IS NULL OR c.created_at < $6::timestamptz)
), batches AS (
    SELECT batch_id,
           amount,
           COUNT(*)::bigint AS key_count,
           COUNT(*) FILTER (WHERE status = 'unused')::bigint AS unused_count,
           COUNT(*) FILTER (WHERE status = 'redeemed')::bigint AS redeemed_count
    FROM filtered
    GROUP BY batch_id, amount
)
SELECT amount,
       COUNT(*)::bigint AS batch_count,
       COUNT(*) FILTER (WHERE unused_count > 0)::bigint AS batches_with_unused,
       COUNT(*) FILTER (WHERE key_count > 0 AND redeemed_count = key_count)::bigint AS fully_redeemed_batch_count
FROM batches
GROUP BY amount
ORDER BY amount
`

type GetCDKeyBatchSummaryParams struct {
	Statuses []string
	Amount   pgtype.Numeric
	BatchID  pgtype.UUID
	Search   pgtype.Text
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetCDKeyBatchSummaryRow struct {
	Amount                  pgtype.Numeric
	BatchCount              int64
	BatchesWithUnused       int64
	FullyRedeemedBatchCount int64
}

// Batch-level card details.  A batch is considered "fully redeemed" only
// when every non-revoked key in the batch is redeemed.  The row filters are
// applied before grouping so the detail remains consistent with the page
// filters, while revoked keys never make a batch look partially redeemed.
func (q *Queries) GetCDKeyBatchSummary(ctx context.Context, arg GetCDKeyBatchSummaryParams) ([]GetCDKeyBatchSummaryRow, error) {
	rows, err := q.db.Query(ctx, getCDKeyBatchSummary,
		arg.Statuses,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCDKeyBatchSummaryRow
	for rows.Next() {
		var i GetCDKeyBatchSummaryRow
		if err := rows.Scan(
			&i.Amount,
			&i.BatchCount,
			&i.BatchesWithUnused,
			&i.FullyRedeemedBatchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCDKeyByIDForUpdate = `-- name: GetCDKeyByIDForUpdate :one
SELECT id, batch_id, code_plaintext, code_hash, code_prefix, code_suffix,
       amount, currency, status, created_at, redeemed_at, revoked_at
FROM cdkeys
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCDKeyByIDForUpdate(ctx context.Context, id int64) (Cdkey, error) {
	row := q.db.QueryRow(ctx, getCDKeyByIDForUpdate, id)
	var i Cdkey
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CodePlaintext,
		&i.CodeHash,
		&i.CodePrefix,
		&i.CodeSuffix,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.RedeemedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCDKeyForRedemptionByHashForUpdate = `-- name: GetCDKeyForRedemptionByHashForUpdate :one
SELECT id, batch_id, code_hash, amount, currency, status,
       created_at, redeemed_at, revoked_at
FROM cdkeys
WHERE code_hash = $1
FOR UPDATE
`

type GetCDKeyForRedemptionByHashForUpdateRow struct {
	ID         int64
	BatchID    pgtype.UUID
	CodeHash   string
	Amount     pgtype.Numeric
	Currency   string
	Status     string
	CreatedAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// Console redemption never needs the plaintext or display fragments. Keep this
// query separate from the Admin lock/export queries so the sensitive column is
// not read into the Console service process.
func (q *Queries) GetCDKeyForRedemptionByHashForUpdate(ctx context.Context, codeHash string) (GetCDKeyForRedemptionByHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCDKeyForRedemptionByHashForUpdate, codeHash)
	var i GetCDKeyForRedemptionByHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CodeHash,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.RedeemedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCDKeyRedemptionByCDKeyID = `-- name: GetCDKeyRedemptionByCDKeyID :one
SELECT r.id, r.cdkey_id, r.user_id, r.amount, r.currency, r.ledger_entry_id,
       r.idempotency_key, r.redeemed_at,
       l.balance_after
FROM cdkey_redemptions r
JOIN ledger_entries l ON l.id = r.ledger_entry_id
WHERE r.cdkey_id = $1
`

type GetCDKeyRedemptionByCDKeyIDRow struct {
	ID             int64
	CdkeyID        int64
	UserID         int64
	Amount         pgtype.Numeric
	Currency       string
	LedgerEntryID  int64
	IdempotencyKey string
	RedeemedAt     pgtype.Timestamptz
	BalanceAfter   pgtype.Numeric
}

func (q *Queries) GetCDKeyRedemptionByCDKeyID(ctx context.Context, cdkeyID int64) (GetCDKeyRedemptionByCDKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getCDKeyRedemptionByCDKeyID, cdkeyID)
	var i GetCDKeyRedemptionByCDKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.CdkeyID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.LedgerEntryID,
		&i.IdempotencyKey,
		&i.RedeemedAt,
		&i.BalanceAfter,
	)
	return i, err
}

const getCDKeySummary = `-- name: GetCDKeySummary :many
SELECT c.amount,
       c.status,
       COUNT(*)::bigint AS quantity,
       COALESCE(SUM(c.amount), 0)::numeric AS total_value,
       COUNT(DISTINCT c.batch_id)::bigint AS batch_count
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE (cardinality($1::text[]) = 0 OR c.status = ANY($1::text[]))
  AND ($2::numeric IS NULL OR c.amount = $2::numeric)
  AND ($3::uuid IS NULL OR c.batch_id = $3::uuid)
  AND ($4::text IS NULL OR (
      c.code_prefix ILIKE '%' || $4::text || '%'
      OR c.code_suffix ILIKE '%' || $4::text || '%'
      OR c.batch_id::text ILIKE '%' || $4::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $4::text || '%'
      OR COALESCE(r.user_id::text, '') ILIKE '%' || $4::text || '%'
  ))
  AND ($5::timestamptz IS NULL OR c.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR c.created_at < $6::timestamptz)
GROUP BY c.amount, c.status
ORDER BY c.amount, c.status
`

type GetCDKeySummaryParams struct {
	Statuses []string
	Amount   pgtype.Numeric
	BatchID  pgtype.UUID
	Search   pgtype.Text
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetCDKeySummaryRow struct {
	Amount     pgtype.Numeric
	Status     string
	Quantity   int64
	TotalValue pgtype.Numeric
	BatchCount int64
}

func (q *Queries) GetCDKeySummary(ctx context.Context, arg GetCDKeySummaryParams) ([]GetCDKeySummaryRow, error) {
	rows, err := q.db.Query(ctx, getCDKeySummary,
		arg.Statuses,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCDKeySummaryRow
	for rows.Next() {
		var i GetCDKeySummaryRow
		if err := rows.Scan(
			&i.Amount,
			&i.Status,
			&i.Quantity,
			&i.TotalValue,
			&i.BatchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCDKeysForUpdateByIDs = `-- name: GetCDKeysForUpdateByIDs :many
SELECT id, batch_id, code_plaintext, code_hash, code_prefix, code_suffix,
       amount, currency, status, created_at, redeemed_at, revoked_at
FROM cdkeys
WHERE id = ANY($1::bigint[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) GetCDKeysForUpdateByIDs(ctx context.Context, ids []int64) ([]Cdkey, error) {
	rows, err := q.db.Query(ctx, getCDKeysForUpdateByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cdkey
	for rows.Next() {
		var i Cdkey
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CodePlaintext,
			&i.CodeHash,
			&i.CodePrefix,
			&i.CodeSuffix,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.RedeemedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCDKeyIDs = `-- name: ListCDKeyIDs :many

SELECT c.id
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE (cardinality($1::text[]) = 0 OR c.status = ANY($1::text[]))
  AND ($2::numeric IS NULL OR c.amount = $2::numeric)
  AND ($3::uuid IS NULL OR c.batch_id = $3::uuid)
  AND ($4::text IS NULL OR (
      c.code_prefix ILIKE '%' || $4::text || '%'
      OR c.code_suffix ILIKE '%' || $4::text || '%'
      OR c.batch_id::text ILIKE '%' || $4::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $4::text || '%'
      OR COALESCE(r.user_id::text, '') ILIKE '%' || $4::text || '%'
  ))
  AND ($5::timestamptz IS NULL OR c.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR c.created_at < $6::timestamptz)
ORDER BY c.id
`

type ListCDKeyIDsParams struct {
	Statuses []string
	Amount   pgtype.Numeric
	BatchID  pgtype.UUID
	Search   pgtype.Text
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

// Admin CDKEY list, summary and state mutation queries. Plaintext is intentionally absent.
// Resolve a server-side selection without loading plaintext or an unbounded page.
func (q *Queries) ListCDKeyIDs(ctx context.Context, arg ListCDKeyIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCDKeyIDs,
		arg.Statuses,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCDKeyRedemptionsPage = `-- name: ListCDKeyRedemptionsPage :many
SELECT
    r.id,
    r.cdkey_id,
    c.batch_id,
    c.code_prefix,
    c.code_suffix,
    r.user_id,
    u.email AS user_email,
    u.display_name AS user_display_name,
    r.amount,
    r.currency,
    r.ledger_entry_id,
    r.idempotency_key,
    r.redeemed_at,
    COUNT(*) OVER () AS total_count
FROM cdkey_redemptions r
JOIN cdkeys c ON c.id = r.cdkey_id
JOIN users u ON u.id = r.user_id
WHERE ($1::bigint IS NULL OR r.user_id = $1::bigint)
  AND ($2::text IS NULL OR (
      c.code_prefix ILIKE '%' || $2::text || '%'
      OR c.code_suffix ILIKE '%' || $2::text || '%'
      OR c.batch_id::text ILIKE '%' || $2::text || '%'
      OR u.email ILIKE '%' || $2::text || '%'
      OR r.user_id::text ILIKE '%' || $2::text || '%'
  ))
  AND ($3::numeric IS NULL OR r.amount = $3::numeric)
  AND ($4::timestamptz IS NULL OR r.redeemed_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR r.redeemed_at < $5::timestamptz)
ORDER BY
  CASE WHEN COALESCE($6::text, 'redeemed_at') IN ('', 'redeemed_at') AND COALESCE($7::bool, true) THEN r.redeemed_at END DESC NULLS LAST,
  CASE WHEN COALESCE($6::text, 'redeemed_at') IN ('', 'redeemed_at') AND NOT COALESCE($7::bool, true) THEN r.redeemed_at END ASC NULLS LAST,
  CASE WHEN $6::text = 'amount' AND COALESCE($7::bool, false) THEN r.amount END DESC NULLS LAST,
  CASE WHEN $6::text = 'amount' AND NOT COALESCE($7::bool, false) THEN r.amount END ASC NULLS LAST,
  CASE WHEN $6::text = 'user_id' AND COALESCE($7::bool, false) THEN r.user_id END DESC NULLS LAST,
  CASE WHEN $6::text = 'user_id' AND NOT COALESCE($7::bool, false) THEN r.user_id END ASC NULLS LAST,
  r.id DESC
LIMIT $9 OFFSET $8
`

type ListCDKeyRedemptionsPageParams struct {
	UserID     pgtype.Int8
	Search     pgtype.Text
	Amount     pgtype.Numeric
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	SortField  pgtype.Text
	SortDesc   pgtype.Bool
	PageOffset int32
	PageLimit  int32
}

type ListCDKeyRedemptionsPageRow struct {
	ID              int64
	CdkeyID         int64
	BatchID         pgtype.UUID
	CodePrefix      string
	CodeSuffix      string
	UserID          int64
	UserEmail       string
	UserDisplayName string
	Amount          pgtype.Numeric
	Currency        string
	LedgerEntryID   int64
	IdempotencyKey  string
	RedeemedAt      pgtype.Timestamptz
	TotalCount      int64
}

func (q *Queries) ListCDKeyRedemptionsPage(ctx context.Context, arg ListCDKeyRedemptionsPageParams) ([]ListCDKeyRedemptionsPageRow, error) {
	rows, err := q.db.Query(ctx, listCDKeyRedemptionsPage,
		arg.UserID,
		arg.Search,
		arg.Amount,
		arg.FromTime,
		arg.ToTime,
		arg.SortField,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCDKeyRedemptionsPageRow
	for rows.Next() {
		var i ListCDKeyRedemptionsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CdkeyID,
			&i.BatchID,
			&i.CodePrefix,
			&i.CodeSuffix,
			&i.UserID,
			&i.UserEmail,
			&i.UserDisplayName,
			&i.Amount,
			&i.Currency,
			&i.LedgerEntryID,
			&i.IdempotencyKey,
			&i.RedeemedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCDKeysPage = `-- name: ListCDKeysPage :many
SELECT
    c.id,
    c.batch_id,
    c.code_prefix,
    c.code_suffix,
    c.amount,
    c.currency,
    c.status,
    c.created_at,
    c.redeemed_at,
    c.revoked_at,
    r.id AS redemption_id,
    r.user_id AS redemption_user_id,
    u.email AS redemption_user_email,
    u.display_name AS redemption_user_display_name,
    r.ledger_entry_id AS redemption_ledger_entry_id,
    r.redeemed_at AS redemption_redeemed_at,
    COUNT(*) OVER () AS total_count
FROM cdkeys c
LEFT JOIN cdkey_redemptions r ON r.cdkey_id = c.id
LEFT JOIN users u ON u.id = r.user_id
WHERE (cardinality($1::text[]) = 0 OR c.status = ANY($1::text[]))
  AND ($2::numeric IS NULL OR c.amount = $2::numeric)
  AND ($3::uuid IS NULL OR c.batch_id = $3::uuid)
  AND ($4::text IS NULL OR (
      c.code_prefix ILIKE '%' || $4::text || '%'
      OR c.code_suffix ILIKE '%' || $4::text || '%'
      OR c.batch_id::text ILIKE '%' || $4::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $4::text || '%'
      OR COALESCE(r.user_id::text, '') ILIKE '%' || $4::text || '%'
  ))
  AND ($5::timestamptz IS NULL OR c.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR c.created_at < $6::timestamptz)
ORDER BY
  CASE WHEN COALESCE($7::text, 'created_at') IN ('', 'created_at') AND COALESCE($8::bool, true) THEN c.created_at END DESC NULLS LAST,
  CASE WHEN COALESCE($7::text, 'created_at') IN ('', 'created_at') AND NOT COALESCE($8::bool, true) THEN c.created_at END ASC NULLS LAST,
  CASE WHEN $7::text = 'amount' AND COALESCE($8::bool, false) THEN c.amount END DESC NULLS LAST,
  CASE WHEN $7::text = 'amount' AND NOT COALESCE($8::bool, false) THEN c.amount END ASC NULLS LAST,
  CASE WHEN $7::text = 'status' AND COALESCE($8::bool, false) THEN c.status END DESC NULLS LAST,
  CASE WHEN $7::text = 'status' AND NOT COALESCE($8::bool, false) THEN c.status END ASC NULLS LAST,
  CASE WHEN COALESCE($7::text, 'created_at') IN ('', 'created_at') AND COALESCE($8::bool, true) THEN c.id END DESC,
  CASE WHEN COALESCE($7::text, 'created_at') IN ('', 'created_at') AND NOT COALESCE($8::bool, true) THEN c.id END ASC,
  c.id DESC
LIMIT $10 OFFSET $9
`

type ListCDKeysPageParams struct {
	Statuses   []string
	Amount     pgtype.Numeric
	BatchID    pgtype.UUID
	Search     pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	SortField  pgtype.Text
	SortDesc   pgtype.Bool
	PageOffset int32
	PageLimit  int32
}

type ListCDKeysPageRow struct {
	ID                        int64
	BatchID                   pgtype.UUID
	CodePrefix                string
	CodeSuffix                string
	Amount                    pgtype.Numeric
	Currency                  string
	Status                    string
	CreatedAt                 pgtype.Timestamptz
	RedeemedAt                pgtype.Timestamptz
	RevokedAt                 pgtype.Timestamptz
	RedemptionID              pgtype.Int8
	RedemptionUserID          pgtype.Int8
	RedemptionUserEmail       pgtype.Text
	RedemptionUserDisplayName pgtype.Text
	RedemptionLedgerEntryID   pgtype.Int8
	RedemptionRedeemedAt      pgtype.Timestamptz
	TotalCount                int64
}

func (q *Queries) ListCDKeysPage(ctx context.Context, arg ListCDKeysPageParams) ([]ListCDKeysPageRow, error) {
	rows, err := q.db.Query(ctx, listCDKeysPage,
		arg.Statuses,
		arg.Amount,
		arg.BatchID,
		arg.Search,
		arg.FromTime,
		arg.ToTime,
		arg.SortField,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCDKeysPageRow
	for rows.Next() {
		var i ListCDKeysPageRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CodePrefix,
			&i.CodeSuffix,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.RedeemedAt,
			&i.RevokedAt,
			&i.RedemptionID,
			&i.RedemptionUserID,
			&i.RedemptionUserEmail,
			&i.RedemptionUserDisplayName,
			&i.RedemptionLedgerEntryID,
			&i.RedemptionRedeemedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCDKeyIfUnused = `-- name: RevokeCDKeyIfUnused :execrows
UPDATE cdkeys
SET status = 'revoked', revoked_at = now()
WHERE id = $1 AND status = 'unused'
`

func (q *Queries) RevokeCDKeyIfUnused(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCDKeyIfUnused, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateConsoleCDKeyRedeemed = `-- name: UpdateConsoleCDKeyRedeemed :execrows

UPDATE cdkeys
SET status = 'redeemed', redeemed_at = $1, revoked_at = NULL
WHERE id = $2 AND status = 'unused'
`

type UpdateConsoleCDKeyRedeemedParams struct {
	RedeemedAt pgtype.Timestamptz
	ID         int64
}

// Console redemption reads/writes are deliberately narrow; no plaintext is returned.
// Keep the Console state transition write-only. In particular, do not use the
// shared Admin-shaped UPDATE ... RETURNING query here: that result includes
// code_plaintext and would unnecessarily bring the redeemable credential into
// the Console process.
func (q *Queries) UpdateConsoleCDKeyRedeemed(ctx context.Context, arg UpdateConsoleCDKeyRedeemedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConsoleCDKeyRedeemed, arg.RedeemedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
