// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailMessages = `-- name: CountEmailMessages :one
SELECT COUNT(*) AS total
FROM email_messages
WHERE ($1::text IS NULL OR email_type = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR recipient ILIKE '%' || $3::text || '%')
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
`

type CountEmailMessagesParams struct {
	EmailType pgtype.Text
	Status    pgtype.Text
	Recipient pgtype.Text
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

// CountEmailMessages 统计与 ListEmailMessages 同口径的总数（分页 meta 用）。
func (q *Queries) CountEmailMessages(ctx context.Context, arg CountEmailMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailMessages,
		arg.EmailType,
		arg.Status,
		arg.Recipient,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getEmailMessage = `-- name: GetEmailMessage :one
SELECT id, email_type, recipient, sender, subject, body_html, status, error_summary, locale, duration_ms, sent_at, created_at
FROM email_messages
WHERE id = $1
`

// GetEmailMessage 读取单条发送记录详情（含 body_html，供 Admin 详情页隔离预览）。
func (q *Queries) GetEmailMessage(ctx context.Context, id int64) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, getEmailMessage, id)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.EmailType,
		&i.Recipient,
		&i.Sender,
		&i.Subject,
		&i.BodyHtml,
		&i.Status,
		&i.ErrorSummary,
		&i.Locale,
		&i.DurationMs,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmailMessage = `-- name: InsertEmailMessage :one
INSERT INTO email_messages (
    email_type, recipient, sender, subject, body_html,
    status, error_summary, locale, duration_ms, sent_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id
`

type InsertEmailMessageParams struct {
	EmailType    string
	Recipient    string
	Sender       string
	Subject      string
	BodyHtml     string
	Status       string
	ErrorSummary pgtype.Text
	Locale       string
	DurationMs   pgtype.Int4
	SentAt       pgtype.Timestamptz
}

// InsertEmailMessage 写入一条邮件发送记录（同步发送路径在 SMTP 提交完成后调用，成功失败都记录）。
func (q *Queries) InsertEmailMessage(ctx context.Context, arg InsertEmailMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEmailMessage,
		arg.EmailType,
		arg.Recipient,
		arg.Sender,
		arg.Subject,
		arg.BodyHtml,
		arg.Status,
		arg.ErrorSummary,
		arg.Locale,
		arg.DurationMs,
		arg.SentAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEmailMessages = `-- name: ListEmailMessages :many
SELECT id, email_type, recipient, sender, subject, status, error_summary, locale, duration_ms, sent_at, created_at
FROM email_messages
WHERE ($1::text IS NULL OR email_type = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR recipient ILIKE '%' || $3::text || '%')
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
ORDER BY id DESC
LIMIT $7 OFFSET $6
`

type ListEmailMessagesParams struct {
	EmailType  pgtype.Text
	Status     pgtype.Text
	Recipient  pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

type ListEmailMessagesRow struct {
	ID           int64
	EmailType    string
	Recipient    string
	Sender       string
	Subject      string
	Status       string
	ErrorSummary pgtype.Text
	Locale       string
	DurationMs   pgtype.Int4
	SentAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// ListEmailMessages 分页列出邮件发送记录（新记录在前）。列表不返回 body_html（正文较大，详情单独取）。
// 筛选：email_type / status 精确匹配；recipient 子串匹配（ILIKE）；from/to 为 created_at 半开区间。
func (q *Queries) ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]ListEmailMessagesRow, error) {
	rows, err := q.db.Query(ctx, listEmailMessages,
		arg.EmailType,
		arg.Status,
		arg.Recipient,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailMessagesRow
	for rows.Next() {
		var i ListEmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmailType,
			&i.Recipient,
			&i.Sender,
			&i.Subject,
			&i.Status,
			&i.ErrorSummary,
			&i.Locale,
			&i.DurationMs,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
