// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_rates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExchangeRates = `-- name: CountExchangeRates :one
SELECT COUNT(*) AS total
FROM exchange_rates
WHERE ($1::text IS NULL OR quote_currency = $1::text)
`

// CountExchangeRates 统计与 ListExchangeRatesPage 同口径的总数。
func (q *Queries) CountExchangeRates(ctx context.Context, quoteCurrency pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countExchangeRates, quoteCurrency)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const latestExchangeRate = `-- name: LatestExchangeRate :one
SELECT id, base_currency, quote_currency, rate, rate_date, source, fetched_at
FROM exchange_rates
WHERE base_currency = $1
  AND quote_currency = $2
ORDER BY rate_date DESC, fetched_at DESC
LIMIT 1
`

type LatestExchangeRateParams struct {
	BaseCurrency  string
	QuoteCurrency string
}

// LatestExchangeRate 取某币种对当前生效汇率：rate_date 最新优先，同日 fetched_at 最新优先
// （手工行只要日期/时间更新即覆盖外部源）。守卫 / 结算 / 展示的唯一消费口径。
func (q *Queries) LatestExchangeRate(ctx context.Context, arg LatestExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, latestExchangeRate, arg.BaseCurrency, arg.QuoteCurrency)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.RateDate,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const listExchangeRatesPage = `-- name: ListExchangeRatesPage :many
SELECT id, base_currency, quote_currency, rate, rate_date, source, fetched_at
FROM exchange_rates
WHERE ($1::text IS NULL OR quote_currency = $1::text)
ORDER BY rate_date DESC, fetched_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListExchangeRatesPageParams struct {
	QuoteCurrency pgtype.Text
	PageOffset    int32
	PageLimit     int32
}

// ListExchangeRatesPage 分页列出汇率历史（admin 汇率页），可按目标币种过滤。
func (q *Queries) ListExchangeRatesPage(ctx context.Context, arg ListExchangeRatesPageParams) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listExchangeRatesPage, arg.QuoteCurrency, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangeRate
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.Rate,
			&i.RateDate,
			&i.Source,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :one
INSERT INTO exchange_rates (base_currency, quote_currency, rate, rate_date, source)
VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (base_currency, quote_currency, rate_date, source)
DO UPDATE SET rate = EXCLUDED.rate, fetched_at = now()
RETURNING id, base_currency, quote_currency, rate, rate_date, source, fetched_at
`

type UpsertExchangeRateParams struct {
	BaseCurrency  string
	QuoteCurrency string
	Rate          pgtype.Numeric
	RateDate      pgtype.Date
	Source        string
}

// UpsertExchangeRate 写入一条汇率；同 (币种对, 汇率日, 来源) 已存在时刷新 rate 与 fetched_at
// （worker 同日重复拉取 / 手工同日修正都走此路径），行只追加或刷新、从不删除。
func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, upsertExchangeRate,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
		arg.RateDate,
		arg.Source,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.RateDate,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}
