// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteModelCatalogCapabilities = `-- name: DeleteModelCatalogCapabilities :exec
DELETE FROM model_catalog_capabilities
WHERE canonical_id = $1
`

// DeleteModelCatalogCapabilities 清空某目录条目的全部能力提示（同步刷新时先删后插）。
func (q *Queries) DeleteModelCatalogCapabilities(ctx context.Context, canonicalID string) error {
	_, err := q.db.Exec(ctx, deleteModelCatalogCapabilities, canonicalID)
	return err
}

const insertModelCatalogCapability = `-- name: InsertModelCatalogCapability :exec
INSERT INTO model_catalog_capabilities (
    canonical_id,
    capability_key,
    support_level,
    limits
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (canonical_id, capability_key) DO UPDATE
SET support_level = excluded.support_level,
    limits = excluded.limits
`

type InsertModelCatalogCapabilityParams struct {
	CanonicalID   string
	CapabilityKey string
	SupportLevel  string
	Limits        []byte
}

// InsertModelCatalogCapability 写入一条目录能力提示（同步刷新时配合 DeleteModelCatalogCapabilities）。
func (q *Queries) InsertModelCatalogCapability(ctx context.Context, arg InsertModelCatalogCapabilityParams) error {
	_, err := q.db.Exec(ctx, insertModelCatalogCapability,
		arg.CanonicalID,
		arg.CapabilityKey,
		arg.SupportLevel,
		arg.Limits,
	)
	return err
}

const listModelCatalogCanonicalIDs = `-- name: ListModelCatalogCanonicalIDs :many
SELECT canonical_id, removed_upstream_at
FROM model_catalog
ORDER BY canonical_id ASC
`

type ListModelCatalogCanonicalIDsRow struct {
	CanonicalID       string
	RemovedUpstreamAt pgtype.Timestamptz
}

// ListModelCatalogCanonicalIDs 列出当前目录全部 canonical_id（含已下架），供同步推导「feed 不含 → 标记下架」。
func (q *Queries) ListModelCatalogCanonicalIDs(ctx context.Context) ([]ListModelCatalogCanonicalIDsRow, error) {
	rows, err := q.db.Query(ctx, listModelCatalogCanonicalIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelCatalogCanonicalIDsRow
	for rows.Next() {
		var i ListModelCatalogCanonicalIDsRow
		if err := rows.Scan(&i.CanonicalID, &i.RemovedUpstreamAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelLabsNeedingLogo = `-- name: ListModelLabsNeedingLogo :many
SELECT slug
FROM model_labs
WHERE logo_synced_at IS NULL
   OR logo_synced_at < $1
ORDER BY slug
`

// ListModelLabsNeedingLogo 列出需要抓取图标的出品方：从未同步过，或上次同步早于给定时间。
// 有图标的不重复抓：厂商 logo 极少变动，每次目录同步都全量重抓只是白费上游带宽。
func (q *Queries) ListModelLabsNeedingLogo(ctx context.Context, staleBefore pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, listModelLabsNeedingLogo, staleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelCatalogRemovedUpstream = `-- name: MarkModelCatalogRemovedUpstream :execrows
UPDATE model_catalog
SET removed_upstream_at = now(),
    updated_at = now()
WHERE canonical_id = $1
    AND removed_upstream_at IS NULL
`

// MarkModelCatalogRemovedUpstream 标记 models.dev 已下架的目录条目（不删本地行）；已标记的不重复更新。
func (q *Queries) MarkModelCatalogRemovedUpstream(ctx context.Context, canonicalID string) (int64, error) {
	result, err := q.db.Exec(ctx, markModelCatalogRemovedUpstream, canonicalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelLabLogo = `-- name: UpdateModelLabLogo :exec
UPDATE model_labs
SET logo_svg = $1,
    logo_synced_at = now(),
    updated_at = now()
WHERE slug = $2
`

type UpdateModelLabLogoParams struct {
	LogoSvg string
	Slug    string
}

// UpdateModelLabLogo 写入图标内容并打上同步时间。
// 空串是合法结果，表示「上游确实没有这个图标」——同样要记时间，否则每次同步都会重试。
func (q *Queries) UpdateModelLabLogo(ctx context.Context, arg UpdateModelLabLogoParams) error {
	_, err := q.db.Exec(ctx, updateModelLabLogo, arg.LogoSvg, arg.Slug)
	return err
}

const upsertModelCatalogEntry = `-- name: UpsertModelCatalogEntry :one
INSERT INTO model_catalog (
    canonical_id,
    lab,
    family,
    display_name,
    description,
    knowledge_cutoff,
    context_window_tokens,
    input_limit_tokens,
    max_output_tokens,
    input_price_usd_per_million_tokens,
    output_price_usd_per_million_tokens,
    cache_read_price_usd_per_million_tokens,
    cache_creation_price_usd_per_million_tokens,
    open_weights,
    modalities_input,
    modalities_output,
    release_date,
    last_updated,
    fingerprint,
    removed_upstream_at,
    synced_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    NULL,
    now()
)
ON CONFLICT (canonical_id) DO UPDATE
SET lab = EXCLUDED.lab,
    family = EXCLUDED.family,
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    knowledge_cutoff = EXCLUDED.knowledge_cutoff,
    context_window_tokens = EXCLUDED.context_window_tokens,
    input_limit_tokens = EXCLUDED.input_limit_tokens,
    max_output_tokens = EXCLUDED.max_output_tokens,
    input_price_usd_per_million_tokens = EXCLUDED.input_price_usd_per_million_tokens,
    output_price_usd_per_million_tokens = EXCLUDED.output_price_usd_per_million_tokens,
    cache_read_price_usd_per_million_tokens = EXCLUDED.cache_read_price_usd_per_million_tokens,
    cache_creation_price_usd_per_million_tokens = EXCLUDED.cache_creation_price_usd_per_million_tokens,
    open_weights = EXCLUDED.open_weights,
    modalities_input = EXCLUDED.modalities_input,
    modalities_output = EXCLUDED.modalities_output,
    release_date = EXCLUDED.release_date,
    last_updated = EXCLUDED.last_updated,
    fingerprint = EXCLUDED.fingerprint,
    removed_upstream_at = NULL,
    synced_at = now(),
    updated_at = now()
RETURNING canonical_id, lab, display_name, context_window_tokens, max_output_tokens, input_price_usd_per_million_tokens, output_price_usd_per_million_tokens, release_date, removed_upstream_at, fingerprint, synced_at, created_at, updated_at, family, description, knowledge_cutoff, cache_read_price_usd_per_million_tokens, cache_creation_price_usd_per_million_tokens, input_limit_tokens, open_weights, modalities_input, modalities_output, last_updated
`

type UpsertModelCatalogEntryParams struct {
	CanonicalID                           string
	Lab                                   string
	Family                                string
	DisplayName                           string
	Description                           string
	KnowledgeCutoff                       string
	ContextWindowTokens                   pgtype.Int8
	InputLimitTokens                      pgtype.Int8
	MaxOutputTokens                       pgtype.Int8
	InputPriceUsdPerMillionTokens         pgtype.Numeric
	OutputPriceUsdPerMillionTokens        pgtype.Numeric
	CacheReadPriceUsdPerMillionTokens     pgtype.Numeric
	CacheCreationPriceUsdPerMillionTokens pgtype.Numeric
	OpenWeights                           pgtype.Bool
	ModalitiesInput                       []string
	ModalitiesOutput                      []string
	ReleaseDate                           pgtype.Date
	LastUpdated                           pgtype.Date
	Fingerprint                           string
}

// UpsertModelCatalogEntry 按 canonical_id 全量 upsert 目录条目；覆盖时刷新 fingerprint/synced_at 并清除下架标记。
func (q *Queries) UpsertModelCatalogEntry(ctx context.Context, arg UpsertModelCatalogEntryParams) (ModelCatalog, error) {
	row := q.db.QueryRow(ctx, upsertModelCatalogEntry,
		arg.CanonicalID,
		arg.Lab,
		arg.Family,
		arg.DisplayName,
		arg.Description,
		arg.KnowledgeCutoff,
		arg.ContextWindowTokens,
		arg.InputLimitTokens,
		arg.MaxOutputTokens,
		arg.InputPriceUsdPerMillionTokens,
		arg.OutputPriceUsdPerMillionTokens,
		arg.CacheReadPriceUsdPerMillionTokens,
		arg.CacheCreationPriceUsdPerMillionTokens,
		arg.OpenWeights,
		arg.ModalitiesInput,
		arg.ModalitiesOutput,
		arg.ReleaseDate,
		arg.LastUpdated,
		arg.Fingerprint,
	)
	var i ModelCatalog
	err := row.Scan(
		&i.CanonicalID,
		&i.Lab,
		&i.DisplayName,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.InputPriceUsdPerMillionTokens,
		&i.OutputPriceUsdPerMillionTokens,
		&i.ReleaseDate,
		&i.RemovedUpstreamAt,
		&i.Fingerprint,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Family,
		&i.Description,
		&i.KnowledgeCutoff,
		&i.CacheReadPriceUsdPerMillionTokens,
		&i.CacheCreationPriceUsdPerMillionTokens,
		&i.InputLimitTokens,
		&i.OpenWeights,
		&i.ModalitiesInput,
		&i.ModalitiesOutput,
		&i.LastUpdated,
	)
	return i, err
}

const upsertModelLab = `-- name: UpsertModelLab :exec
INSERT INTO model_labs (slug, name)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = now()
`

type UpsertModelLabParams struct {
	Slug string
	Name string
}

// UpsertModelLab 按 slug 登记出品方；已存在时只补名称，不动图标
// （图标由 UpdateModelLabLogo 单独维护，避免目录同步把已抓到的图标覆盖成空）。
func (q *Queries) UpsertModelLab(ctx context.Context, arg UpsertModelLabParams) error {
	_, err := q.db.Exec(ctx, upsertModelLab, arg.Slug, arg.Name)
	return err
}
