// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_labs.sql

package sqlc

import (
	"context"
)

const getModelLabLogo = `-- name: GetModelLabLogo :one
SELECT logo_svg
FROM model_labs
WHERE slug = $1
`

// GetModelLabLogo 读取出品方图标 SVG（console 与 admin 的 logo 端点共用）。
// 空串表示登记过但上游没有图标；无行表示 slug 未登记——两者都由上层按 404 处理。
func (q *Queries) GetModelLabLogo(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, getModelLabLogo, slug)
	var logo_svg string
	err := row.Scan(&logo_svg)
	return logo_svg, err
}
