// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlc

import (
	"context"
)

const listAvailableModels = `-- name: ListAvailableModels :many
SELECT
    m.id,
    m.model_id,
    m.display_name,
    m.owned_by,
    COALESCE(
        array_agg(DISTINCT mc.capability_key)
            FILTER (WHERE mc.capability_key IS NOT NULL AND mc.support_level <> 'unsupported'),
        '{}'
    )::text[] AS capability_keys
FROM models m
LEFT JOIN model_capabilities mc ON mc.model_id = m.id
WHERE m.status = 'enabled'
GROUP BY m.id, m.model_id, m.display_name, m.owned_by
ORDER BY m.model_id ASC
`

type ListAvailableModelsRow struct {
	ID             int64
	ModelID        string
	DisplayName    string
	OwnedBy        string
	CapabilityKeys []string
}

// ListAvailableModels 列出所有启用模型，并附带该模型已声明的 cap-tags
// （能力架构 Layer 2，support_level<>'unsupported' 的 capability_key 去重升序）。
// cap-tags 取模型级声明，不下钻到 channel override（不向客户暴露 channel 维度收紧）。
// 未声明任何能力的模型 capability_keys 为空数组（unprovisioned）。
//
// 不做用户级过滤：模型 enabled 的前置条件是「至少有一条可用渠道能供」（供给不变量），
// 因此列出即可调用。协议维度由 ListModelProtocols 单独提供，不在此收窄。
func (q *Queries) ListAvailableModels(ctx context.Context) ([]ListAvailableModelsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableModelsRow
	for rows.Next() {
		var i ListAvailableModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.DisplayName,
			&i.OwnedBy,
			&i.CapabilityKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelProtocols = `-- name: ListModelProtocols :many
SELECT
    m.model_id,
    array_agg(DISTINCT proto ORDER BY proto)::text[] AS protocols
FROM models m
JOIN channel_models cm ON cm.model_id = m.id AND cm.status = 'enabled'
JOIN channels c ON c.id = cm.channel_id AND c.status = 'enabled' AND c.credential_valid
JOIN providers p ON p.id = c.provider_id AND p.status = 'enabled'
CROSS JOIN LATERAL unnest(c.protocols) AS proto
WHERE m.status = 'enabled'
GROUP BY m.model_id
ORDER BY m.model_id ASC
`

type ListModelProtocolsRow struct {
	ModelID   string
	Protocols []string
}

// ListModelProtocols 汇总每个启用模型当前实际可用的入口协议：
// 取其所有可用渠道 protocols 的并集。协议信息不落库，恒等于实际供给能力，
// 不存在「声明支持但调不通」的状态。
func (q *Queries) ListModelProtocols(ctx context.Context) ([]ListModelProtocolsRow, error) {
	rows, err := q.db.Query(ctx, listModelProtocols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelProtocolsRow
	for rows.Next() {
		var i ListModelProtocolsRow
		if err := rows.Scan(&i.ModelID, &i.Protocols); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelIngressQualification = `-- name: ModelIngressQualification :one
SELECT
    EXISTS (
        SELECT 1
        FROM models m
        WHERE m.model_id = $1
        AND m.status = 'enabled'
    ) AS model_exists,
    (
        EXISTS (
            SELECT 1
            FROM models m
            JOIN channel_models cm ON cm.model_id = m.id
            JOIN channels c ON c.id = cm.channel_id AND c.status <> 'archived'
            WHERE m.model_id = $1
            AND $2::text = ANY(c.protocols)
        )
        OR NOT EXISTS (
            SELECT 1
            FROM models m
            JOIN channel_models cm ON cm.model_id = m.id
            JOIN channels c ON c.id = cm.channel_id AND c.status <> 'archived'
            WHERE m.model_id = $1
        )
    )::boolean AS protocol_supported
`

type ModelIngressQualificationParams struct {
	RequestedModelID string
	IngressProtocol  string
}

type ModelIngressQualificationRow struct {
	ModelExists       bool
	ProtocolSupported bool
}

// ModelIngressQualification 在 request_records 创建之前一次判定模型产品资格：
//
//	model_exists       模型是否存在且启用；
//	protocol_supported 请求的入口协议族是否属于该模型的产品面。
//
// protocol_supported 只看配置存在性（绑定行 + 未归档渠道，不看绑定/渠道启停、
// 凭据、价格等运行时供给），并且只有「模型配置过供给、但请求协议不在其协议
// 集合内」才判 false——那是客户端用错协议，在资格阶段拒绝、不落请求记录。
// 两类情况必须保持 503 口径、不得在此拒绝（ADR-0020：暂停供给不能把服务失败
// 移出失败率统计）：
//  1. 协议面配置过但临时打不通（绑定/渠道停用、凭据无效、缺价格等）；
//  2. 模型被解绑到没有任何供给配置、管理员显式选择保留 enabled。
//
// 这两类由 FindModelCandidates 按 no_available_channel 收口并落请求记录。
func (q *Queries) ModelIngressQualification(ctx context.Context, arg ModelIngressQualificationParams) (ModelIngressQualificationRow, error) {
	row := q.db.QueryRow(ctx, modelIngressQualification, arg.RequestedModelID, arg.IngressProtocol)
	var i ModelIngressQualificationRow
	err := row.Scan(&i.ModelExists, &i.ProtocolSupported)
	return i, err
}
