// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_prices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveModelPrice = `-- name: FindActiveModelPrice :one
SELECT id, model_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_creation_5m_input_price, cache_creation_1h_input_price, output_price, reasoning_output_price, status, effective_from, effective_to, created_at, updated_at, cache_creation_30m_input_price, long_context_enabled, long_context_threshold, long_context_input_multiplier, long_context_output_multiplier, sale_uncached_input_price, sale_cache_read_input_price, sale_cache_creation_5m_input_price, sale_cache_creation_1h_input_price, sale_cache_creation_30m_input_price, sale_output_price, sale_reasoning_output_price, sale_discount
FROM model_prices
WHERE model_id = $1
    AND status = 'enabled'
    AND effective_from <= $2
    AND (
        effective_to IS NULL
        OR effective_to > $2
    )
ORDER BY effective_from DESC, id DESC
LIMIT 1
`

type FindActiveModelPriceParams struct {
	ModelID int64
	AtTime  pgtype.Timestamptz
}

// FindActiveModelPrice 查找指定 model 在指定时间生效的基准售价（settlement / authorization 计算客户售价用）。
func (q *Queries) FindActiveModelPrice(ctx context.Context, arg FindActiveModelPriceParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, findActiveModelPrice, arg.ModelID, arg.AtTime)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheCreation5mInputPrice,
		&i.CacheCreation1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CacheCreation30mInputPrice,
		&i.LongContextEnabled,
		&i.LongContextThreshold,
		&i.LongContextInputMultiplier,
		&i.LongContextOutputMultiplier,
		&i.SaleUncachedInputPrice,
		&i.SaleCacheReadInputPrice,
		&i.SaleCacheCreation5mInputPrice,
		&i.SaleCacheCreation1hInputPrice,
		&i.SaleCacheCreation30mInputPrice,
		&i.SaleOutputPrice,
		&i.SaleReasoningOutputPrice,
		&i.SaleDiscount,
	)
	return i, err
}
