// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardBillingExceptionSummary = `-- name: DashboardBillingExceptionSummary :many
SELECT
    event_type,
    COUNT(*) AS total,
    COALESCE(SUM(platform_amount), 0)::numeric AS platform_amount
FROM ledger_billing_exceptions
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
GROUP BY event_type
ORDER BY event_type
`

type DashboardBillingExceptionSummaryParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardBillingExceptionSummaryRow struct {
	EventType      string
	Total          int64
	PlatformAmount pgtype.Numeric
}

// DashboardBillingExceptionSummary 在区间内按 event_type 聚合计费异常数与平台承担金额。
// 语义为「区间内新增异常」（该表无 resolved 状态，写入即审计事实）。
func (q *Queries) DashboardBillingExceptionSummary(ctx context.Context, arg DashboardBillingExceptionSummaryParams) ([]DashboardBillingExceptionSummaryRow, error) {
	rows, err := q.db.Query(ctx, dashboardBillingExceptionSummary, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBillingExceptionSummaryRow
	for rows.Next() {
		var i DashboardBillingExceptionSummaryRow
		if err := rows.Scan(&i.EventType, &i.Total, &i.PlatformAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBreakdownChannel = `-- name: DashboardBreakdownChannel :many
WITH attempt_agg AS (
    SELECT
        c.id AS channel_id,
        c.name AS channel_name,
        c.status AS channel_status,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream') AS terminal_total,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded') AS succeeded_total,
        COUNT(a.id) FILTER (WHERE a.status = 'failed') AS failed_total,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded' AND a.completed_at IS NOT NULL) AS latency_sample,
        COALESCE(AVG(CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_avg,
        COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p50,
        COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p90,
        COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95,
        COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p99
    FROM channels c
    JOIN request_attempts a
      ON a.channel_id = c.id
     AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
     AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    GROUP BY c.id, c.name, c.status
),
money_agg AS (
    SELECT
        r.final_channel_id AS channel_id,
        COALESCE(SUM(
            u.uncached_input_tokens + u.cache_read_input_tokens
            + u.cache_creation_5m_input_tokens + u.cache_creation_1h_input_tokens + u.cache_creation_30m_input_tokens
            + u.output_tokens_total
        ), 0)::bigint AS tokens_total,
        COALESCE(SUM(ledger.revenue_usd), 0)::numeric AS revenue_usd,
        -- 成本读 USD 归一列（D8）。
        COALESCE(SUM(cs.total_cost_amount_usd), 0)::numeric AS cost_usd
    FROM request_records r
    LEFT JOIN usage_records u ON u.request_record_id = r.id
    LEFT JOIN cost_snapshots cs ON cs.request_record_id = r.id
    LEFT JOIN LATERAL (
        SELECT COALESCE(
            SUM(le.amount) FILTER (WHERE le.entry_type = 'debit' AND le.currency = 'USD'),
            0
        )::numeric AS revenue_usd
        FROM ledger_entries le
        WHERE le.request_record_id = r.id
    ) ledger ON true
    WHERE r.final_channel_id IS NOT NULL
      AND ($1::timestamptz IS NULL OR r.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR r.created_at < $2::timestamptz)
    GROUP BY r.final_channel_id
),
tps_agg AS (
    SELECT
        a.channel_id,
        COALESCE(
            SUM(u.output_tokens_total)::float8 / NULLIF(SUM(
                CASE
                    WHEN a.completed_at IS NOT NULL
                    THEN EXTRACT(EPOCH FROM (a.completed_at - COALESCE(a.gateway_first_token_at, a.started_at)))
                END
            ), 0),
            0
        )::float8 AS avg_tps
    FROM request_attempts a
    JOIN usage_records u ON u.request_record_id = a.request_record_id
    WHERE a.status = 'succeeded'
      AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    GROUP BY a.channel_id
),
latest_error AS (
    SELECT DISTINCT ON (a.channel_id)
        a.channel_id,
        a.error_code
    FROM request_attempts a
    WHERE a.error_code IS NOT NULL
      AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    ORDER BY a.channel_id, a.created_at DESC
)
SELECT
    a.channel_id,
    a.channel_name,
    a.channel_status,
    a.terminal_total,
    a.succeeded_total,
    a.failed_total,
    COALESCE(m.tokens_total, 0)::bigint AS tokens_total,
    COALESCE(m.revenue_usd, 0)::numeric AS revenue_usd,
    COALESCE(m.cost_usd, 0)::numeric AS cost_usd,
    a.latency_sample,
    a.latency_avg,
    a.latency_p50,
    a.latency_p90,
    a.latency_p95,
    a.latency_p99,
    COALESCE(t.avg_tps, 0)::float8 AS avg_tps,
    le.error_code AS recent_error_code
FROM attempt_agg a
LEFT JOIN money_agg m ON m.channel_id = a.channel_id
LEFT JOIN tps_agg t ON t.channel_id = a.channel_id
LEFT JOIN latest_error le ON le.channel_id = a.channel_id
ORDER BY a.terminal_total DESC
LIMIT 20
`

type DashboardBreakdownChannelParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardBreakdownChannelRow struct {
	ChannelID       int64
	ChannelName     string
	ChannelStatus   string
	TerminalTotal   int64
	SucceededTotal  int64
	FailedTotal     int64
	TokensTotal     int64
	RevenueUsd      pgtype.Numeric
	CostUsd         pgtype.Numeric
	LatencySample   int64
	LatencyAvg      float64
	LatencyP50      float64
	LatencyP90      float64
	LatencyP95      float64
	LatencyP99      float64
	AvgTps          float64
	RecentErrorCode pgtype.Text
}

// DashboardBreakdownChannel 按渠道 attempt 聚合成功率/延迟；Token/金额仍按最终请求账务事实聚合。
func (q *Queries) DashboardBreakdownChannel(ctx context.Context, arg DashboardBreakdownChannelParams) ([]DashboardBreakdownChannelRow, error) {
	rows, err := q.db.Query(ctx, dashboardBreakdownChannel, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBreakdownChannelRow
	for rows.Next() {
		var i DashboardBreakdownChannelRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelStatus,
			&i.TerminalTotal,
			&i.SucceededTotal,
			&i.FailedTotal,
			&i.TokensTotal,
			&i.RevenueUsd,
			&i.CostUsd,
			&i.LatencySample,
			&i.LatencyAvg,
			&i.LatencyP50,
			&i.LatencyP90,
			&i.LatencyP95,
			&i.LatencyP99,
			&i.AvgTps,
			&i.RecentErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBreakdownModel = `-- name: DashboardBreakdownModel :many
SELECT
    r.requested_model_id AS model_id,
    COUNT(*) FILTER (WHERE r.status IN ('succeeded', 'failed')) AS terminal_total,
    COUNT(*) FILTER (WHERE r.status = 'succeeded') AS succeeded_total,
    COUNT(*) FILTER (WHERE r.status = 'failed') AS failed_total,
    COALESCE(SUM(
        u.uncached_input_tokens + u.cache_read_input_tokens
        + u.cache_creation_5m_input_tokens + u.cache_creation_1h_input_tokens + u.cache_creation_30m_input_tokens
        + u.output_tokens_total
    ), 0)::bigint AS tokens_total,
    COALESCE(SUM(ledger.revenue_usd), 0)::numeric AS revenue_usd,
    -- 成本读 USD 归一列（D8）。
    COALESCE(SUM(cs.total_cost_amount_usd), 0)::numeric AS cost_usd,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE
            WHEN r.status = 'succeeded' AND r.completed_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (r.completed_at - r.started_at)) * 1000)::float8
        END), 0)::float8 AS latency_p95
FROM request_records r
LEFT JOIN usage_records u ON u.request_record_id = r.id
LEFT JOIN cost_snapshots cs ON cs.request_record_id = r.id
LEFT JOIN LATERAL (
    SELECT COALESCE(
        SUM(le.amount) FILTER (WHERE le.entry_type = 'debit' AND le.currency = 'USD'),
        0
    )::numeric AS revenue_usd
    FROM ledger_entries le
    WHERE le.request_record_id = r.id
) ledger ON true
WHERE ($1::timestamptz IS NULL OR r.created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR r.created_at < $2::timestamptz)
GROUP BY r.requested_model_id
ORDER BY terminal_total DESC
LIMIT 20
`

type DashboardBreakdownModelParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardBreakdownModelRow struct {
	ModelID        string
	TerminalTotal  int64
	SucceededTotal int64
	FailedTotal    int64
	TokensTotal    int64
	RevenueUsd     pgtype.Numeric
	CostUsd        pgtype.Numeric
	LatencyP95     float64
}

// DashboardBreakdownModel 按对外请求模型聚合区间请求（精简 Top），附 token / 成本(USD) / P95 延迟。
func (q *Queries) DashboardBreakdownModel(ctx context.Context, arg DashboardBreakdownModelParams) ([]DashboardBreakdownModelRow, error) {
	rows, err := q.db.Query(ctx, dashboardBreakdownModel, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBreakdownModelRow
	for rows.Next() {
		var i DashboardBreakdownModelRow
		if err := rows.Scan(
			&i.ModelID,
			&i.TerminalTotal,
			&i.SucceededTotal,
			&i.FailedTotal,
			&i.TokensTotal,
			&i.RevenueUsd,
			&i.CostUsd,
			&i.LatencyP95,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBreakdownProvider = `-- name: DashboardBreakdownProvider :many
WITH attempt_agg AS (
    SELECT
        p.id AS provider_id,
        p.name AS provider_name,
        p.status AS provider_status,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream') AS terminal_total,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded') AS succeeded_total,
        COUNT(a.id) FILTER (WHERE a.status = 'failed') AS failed_total,
        COUNT(DISTINCT a.channel_id) AS channel_count,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded' AND a.completed_at IS NOT NULL) AS latency_sample,
        COALESCE(AVG(CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_avg,
        COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p50,
        COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p90,
        COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95,
        COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY
            CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
                 THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p99
    FROM providers p
    JOIN request_attempts a
      ON a.provider_id = p.id
     AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
     AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    GROUP BY p.id, p.name, p.status
),
money_agg AS (
    SELECT
        r.final_provider_id AS provider_id,
        COALESCE(SUM(
            u.uncached_input_tokens + u.cache_read_input_tokens
            + u.cache_creation_5m_input_tokens + u.cache_creation_1h_input_tokens + u.cache_creation_30m_input_tokens
            + u.output_tokens_total
        ), 0)::bigint AS tokens_total,
        COALESCE(SUM(ledger.revenue_usd), 0)::numeric AS revenue_usd,
        -- 成本读 USD 归一列（D8）：每笔按结算钉住的汇率折算，跨币种直接求和。
        COALESCE(SUM(cs.total_cost_amount_usd), 0)::numeric AS cost_usd
    FROM request_records r
    LEFT JOIN usage_records u ON u.request_record_id = r.id
    LEFT JOIN cost_snapshots cs ON cs.request_record_id = r.id
    LEFT JOIN LATERAL (
        SELECT COALESCE(
            SUM(le.amount) FILTER (WHERE le.entry_type = 'debit' AND le.currency = 'USD'),
            0
        )::numeric AS revenue_usd
        FROM ledger_entries le
        WHERE le.request_record_id = r.id
    ) ledger ON true
    WHERE r.final_provider_id IS NOT NULL
      AND ($1::timestamptz IS NULL OR r.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR r.created_at < $2::timestamptz)
    GROUP BY r.final_provider_id
),
tps_agg AS (
    SELECT
        a.provider_id,
        COALESCE(
            SUM(u.output_tokens_total)::float8 / NULLIF(SUM(
                CASE
                    WHEN a.completed_at IS NOT NULL
                    THEN EXTRACT(EPOCH FROM (a.completed_at - COALESCE(a.gateway_first_token_at, a.started_at)))
                END
            ), 0),
            0
        )::float8 AS avg_tps
    FROM request_attempts a
    JOIN usage_records u ON u.request_record_id = a.request_record_id
    WHERE a.status = 'succeeded'
      AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    GROUP BY a.provider_id
)
SELECT
    a.provider_id,
    a.provider_name,
    a.provider_status,
    -- 余额按 provider 原始币种行读取（D2）；balance_usd 为最新汇率折算展示口径；
    -- 低余额判定按 USD 等值（§12.C.5），缺汇率时比较为 NULL 落到 normal 不误报。
    p.currency AS balance_currency,
    pb.balance AS balance,
    (CASE WHEN p.currency = 'USD' THEN pb.balance ELSE pb.balance / fx.rate END)::numeric AS balance_usd,
    CASE
        WHEN pb.balance IS NULL THEN 'unconfigured'
        WHEN pb.balance < 0 THEN 'negative'
        WHEN (CASE WHEN p.currency = 'USD' THEN pb.balance ELSE pb.balance / fx.rate END) < 10 THEN 'low'
        ELSE 'normal'
    END AS balance_status,
    a.terminal_total,
    a.succeeded_total,
    a.failed_total,
    a.channel_count,
    COALESCE(m.tokens_total, 0)::bigint AS tokens_total,
    COALESCE(m.revenue_usd, 0)::numeric AS revenue_usd,
    COALESCE(m.cost_usd, 0)::numeric AS cost_usd,
    a.latency_sample,
    a.latency_avg,
    a.latency_p50,
    a.latency_p90,
    a.latency_p95,
    a.latency_p99,
    COALESCE(t.avg_tps, 0)::float8 AS avg_tps
FROM attempt_agg a
JOIN providers p ON p.id = a.provider_id
LEFT JOIN provider_balances pb ON pb.provider_id = a.provider_id AND pb.currency = p.currency
LEFT JOIN LATERAL (
    SELECT er.rate
    FROM exchange_rates er
    WHERE er.base_currency = 'USD' AND er.quote_currency = p.currency
    ORDER BY er.rate_date DESC, er.fetched_at DESC
    LIMIT 1
) fx ON p.currency <> 'USD'
LEFT JOIN money_agg m ON m.provider_id = a.provider_id
LEFT JOIN tps_agg t ON t.provider_id = a.provider_id
ORDER BY a.terminal_total DESC
LIMIT 20
`

type DashboardBreakdownProviderParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardBreakdownProviderRow struct {
	ProviderID      int64
	ProviderName    string
	ProviderStatus  string
	BalanceCurrency string
	Balance         pgtype.Numeric
	BalanceUsd      pgtype.Numeric
	BalanceStatus   string
	TerminalTotal   int64
	SucceededTotal  int64
	FailedTotal     int64
	ChannelCount    int64
	TokensTotal     int64
	RevenueUsd      pgtype.Numeric
	CostUsd         pgtype.Numeric
	LatencySample   int64
	LatencyAvg      float64
	LatencyP50      float64
	LatencyP90      float64
	LatencyP95      float64
	LatencyP99      float64
	AvgTps          float64
}

// DashboardBreakdownProvider 按服务商 attempt 聚合成功率/延迟；Token/金额仍按最终请求账务事实聚合。
func (q *Queries) DashboardBreakdownProvider(ctx context.Context, arg DashboardBreakdownProviderParams) ([]DashboardBreakdownProviderRow, error) {
	rows, err := q.db.Query(ctx, dashboardBreakdownProvider, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBreakdownProviderRow
	for rows.Next() {
		var i DashboardBreakdownProviderRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderStatus,
			&i.BalanceCurrency,
			&i.Balance,
			&i.BalanceUsd,
			&i.BalanceStatus,
			&i.TerminalTotal,
			&i.SucceededTotal,
			&i.FailedTotal,
			&i.ChannelCount,
			&i.TokensTotal,
			&i.RevenueUsd,
			&i.CostUsd,
			&i.LatencySample,
			&i.LatencyAvg,
			&i.LatencyP50,
			&i.LatencyP90,
			&i.LatencyP95,
			&i.LatencyP99,
			&i.AvgTps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardChannelSuccessBuckets = `-- name: DashboardChannelSuccessBuckets :many
WITH top_channels AS (
    SELECT
        a.channel_id,
        COUNT(a.id) AS terminal_total
    FROM request_attempts a
    WHERE ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    GROUP BY a.channel_id
    ORDER BY terminal_total DESC
    LIMIT 20
),
bucketed AS (
    SELECT
        a.channel_id,
        date_bin('10 minutes'::interval, a.created_at, '1970-01-01 00:00:00+00'::timestamptz)::timestamptz AS bucket,
        COUNT(a.id)::bigint AS terminal_total,
        COUNT(a.id) FILTER (WHERE a.status = 'succeeded')::bigint AS succeeded_total
    FROM request_attempts a
    JOIN top_channels tc ON tc.channel_id = a.channel_id
    WHERE ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
    GROUP BY a.channel_id, date_bin('10 minutes'::interval, a.created_at, '1970-01-01 00:00:00+00'::timestamptz)
),
ranked AS (
    SELECT
        h.channel_id, h.bucket, h.terminal_total, h.succeeded_total,
        row_number() OVER (PARTITION BY h.channel_id ORDER BY h.bucket DESC) AS recency_rank
    FROM bucketed h
)
SELECT
    channel_id,
    bucket,
    terminal_total,
    succeeded_total,
    COALESCE(succeeded_total::float8 / NULLIF(terminal_total, 0), 0)::float8 AS success_rate
FROM ranked
WHERE recency_rank <= 144
ORDER BY channel_id, bucket
`

type DashboardChannelSuccessBucketsParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardChannelSuccessBucketsRow struct {
	ChannelID      int64
	Bucket         pgtype.Timestamptz
	TerminalTotal  int64
	SucceededTotal int64
	SuccessRate    float64
}

// DashboardChannelSuccessBuckets 返回「渠道表现」Top 20 渠道的最近 10 分钟成功率桶。
func (q *Queries) DashboardChannelSuccessBuckets(ctx context.Context, arg DashboardChannelSuccessBucketsParams) ([]DashboardChannelSuccessBucketsRow, error) {
	rows, err := q.db.Query(ctx, dashboardChannelSuccessBuckets, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardChannelSuccessBucketsRow
	for rows.Next() {
		var i DashboardChannelSuccessBucketsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Bucket,
			&i.TerminalTotal,
			&i.SucceededTotal,
			&i.SuccessRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardCostByCurrency = `-- name: DashboardCostByCurrency :many
SELECT currency, COALESCE(SUM(total_cost_amount), 0)::numeric AS total
FROM cost_snapshots
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
GROUP BY currency
ORDER BY currency
`

type DashboardCostByCurrencyParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardCostByCurrencyRow struct {
	Currency string
	Total    pgtype.Numeric
}

// DashboardCostByCurrency 在区间内按币种汇总平台上游成本（cost_snapshots.total_cost_amount）。
func (q *Queries) DashboardCostByCurrency(ctx context.Context, arg DashboardCostByCurrencyParams) ([]DashboardCostByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, dashboardCostByCurrency, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardCostByCurrencyRow
	for rows.Next() {
		var i DashboardCostByCurrencyRow
		if err := rows.Scan(&i.Currency, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardCostTimeseries = `-- name: DashboardCostTimeseries :many
SELECT
    date_trunc($1::text, created_at)::timestamptz AS bucket,
    currency,
    COALESCE(SUM(total_cost_amount), 0)::numeric AS total
FROM cost_snapshots
WHERE ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
GROUP BY bucket, currency
ORDER BY bucket, currency
`

type DashboardCostTimeseriesParams struct {
	Unit     string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardCostTimeseriesRow struct {
	Bucket   pgtype.Timestamptz
	Currency string
	Total    pgtype.Numeric
}

// DashboardCostTimeseries 按时间桶 + 币种聚合平台实际成本（cost_snapshots.total_cost_amount），
// 与 spend 同形（多币种各成一线），供前端画成本趋势折线。时间列用 cost_snapshots.created_at
// （结算写入时刻），与成本 KPI 口径一致。
func (q *Queries) DashboardCostTimeseries(ctx context.Context, arg DashboardCostTimeseriesParams) ([]DashboardCostTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardCostTimeseries, arg.Unit, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardCostTimeseriesRow
	for rows.Next() {
		var i DashboardCostTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.Currency, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPerformanceTimeseries = `-- name: DashboardPerformanceTimeseries :many
SELECT
    date_trunc($1::text, r.created_at)::timestamptz AS bucket,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE
            WHEN r.status = 'succeeded' AND r.completed_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (r.completed_at - r.started_at)) * 1000)::float8
        END), 0)::float8 AS latency_p95,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE
            WHEN r.stream = TRUE AND r.gateway_first_token_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (r.gateway_first_token_at - r.started_at)) * 1000)::float8
        END), 0)::float8 AS gateway_ttft_p95,
    COALESCE(SUM(u.output_tokens_total) FILTER (WHERE r.status = 'succeeded'), 0)::bigint AS output_tokens,
    COALESCE(SUM(
        CASE
            WHEN r.status = 'succeeded' AND r.completed_at IS NOT NULL
            THEN EXTRACT(EPOCH FROM (
                r.completed_at - COALESCE(
                    CASE WHEN r.stream = TRUE THEN r.gateway_first_token_at END,
                    r.started_at
                )
            ))
        END
    ), 0)::float8 AS generation_seconds
FROM request_records r
LEFT JOIN usage_records u ON u.request_record_id = r.id
WHERE ($2::timestamptz IS NULL OR r.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR r.created_at < $3::timestamptz)
GROUP BY bucket
ORDER BY bucket
`

type DashboardPerformanceTimeseriesParams struct {
	Unit     string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardPerformanceTimeseriesRow struct {
	Bucket            pgtype.Timestamptz
	LatencyP95        float64
	GatewayTtftP95    float64
	OutputTokens      int64
	GenerationSeconds float64
}

// DashboardPerformanceTimeseries 按时间桶聚合 P95 延迟 / P95 Gateway TTFT / TPS（性能趋势图）。
// request_records 与 usage_records 为 1:1（usage.request_record_id UNIQUE），JOIN 不放大行数。
func (q *Queries) DashboardPerformanceTimeseries(ctx context.Context, arg DashboardPerformanceTimeseriesParams) ([]DashboardPerformanceTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardPerformanceTimeseries, arg.Unit, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardPerformanceTimeseriesRow
	for rows.Next() {
		var i DashboardPerformanceTimeseriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.LatencyP95,
			&i.GatewayTtftP95,
			&i.OutputTokens,
			&i.GenerationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRadarBadChannels = `-- name: DashboardRadarBadChannels :many
SELECT
    c.id AS channel_id,
    c.name,
    c.status,
    COUNT(a.id) AS attempt_total,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded') AS attempt_succeeded,
    COUNT(a.id) FILTER (WHERE a.status = 'failed' AND a.fault_party = 'upstream') AS attempt_failed,
    (
        SELECT a2.error_code
        FROM request_attempts a2
        WHERE a2.channel_id = c.id
          AND a2.error_code IS NOT NULL
          AND ($1::timestamptz IS NULL OR a2.created_at >= $1::timestamptz)
          AND ($2::timestamptz IS NULL OR a2.created_at < $2::timestamptz)
        ORDER BY a2.created_at DESC
        LIMIT 1
    ) AS recent_error_code
FROM channels c
LEFT JOIN request_attempts a
    ON a.channel_id = c.id
    AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
GROUP BY c.id, c.name, c.status
HAVING COUNT(a.id) > 0
ORDER BY COUNT(a.id) FILTER (WHERE a.status = 'failed' AND a.fault_party = 'upstream') DESC,
         COUNT(a.id) DESC,
         c.id ASC
LIMIT 10
`

type DashboardRadarBadChannelsParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardRadarBadChannelsRow struct {
	ChannelID        int64
	Name             string
	Status           string
	AttemptTotal     int64
	AttemptSucceeded int64
	AttemptFailed    int64
	RecentErrorCode  pgtype.Text
}

// DashboardRadarBadChannels 返回区间内真实上游失败最多的渠道（精简客观事实）。
func (q *Queries) DashboardRadarBadChannels(ctx context.Context, arg DashboardRadarBadChannelsParams) ([]DashboardRadarBadChannelsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRadarBadChannels, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRadarBadChannelsRow
	for rows.Next() {
		var i DashboardRadarBadChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Name,
			&i.Status,
			&i.AttemptTotal,
			&i.AttemptSucceeded,
			&i.AttemptFailed,
			&i.RecentErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRadarRequestPerf = `-- name: DashboardRadarRequestPerf :one

SELECT
    COUNT(*) FILTER (WHERE status IN ('succeeded', 'failed')) AS terminal_total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS succeeded_total,
    COUNT(*) FILTER (WHERE status = 'failed') AS failed_total,
    COUNT(*) FILTER (WHERE status = 'canceled') AS canceled_total,
    COUNT(*) FILTER (WHERE status IN ('pending', 'running')) AS pending_total,
    COUNT(*) FILTER (WHERE error_code ILIKE '%timeout%' OR error_code = 'context_deadline_exceeded') AS timeout_total,
    COALESCE(AVG(lat_ms), 0)::float8 AS latency_avg,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY lat_ms), 0)::float8 AS latency_p50,
    COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY lat_ms), 0)::float8 AS latency_p90,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY lat_ms), 0)::float8 AS latency_p95,
    COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY lat_ms), 0)::float8 AS latency_p99,
    COUNT(lat_ms) AS latency_sample,
    COALESCE(AVG(gateway_ttft_ms), 0)::float8 AS gateway_ttft_avg,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY gateway_ttft_ms), 0)::float8 AS gateway_ttft_p50,
    COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY gateway_ttft_ms), 0)::float8 AS gateway_ttft_p90,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY gateway_ttft_ms), 0)::float8 AS gateway_ttft_p95,
    COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY gateway_ttft_ms), 0)::float8 AS gateway_ttft_p99,
    COUNT(gateway_ttft_ms) AS gateway_ttft_sample
FROM (
    SELECT
        status,
        error_code,
        CASE
            WHEN status = 'succeeded' AND completed_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8
        END AS lat_ms,
        CASE
            WHEN stream = TRUE AND gateway_first_token_at IS NOT NULL
            THEN (EXTRACT(EPOCH FROM (gateway_first_token_at - started_at)) * 1000)::float8
        END AS gateway_ttft_ms
    FROM request_records
    WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
) s
`

type DashboardRadarRequestPerfParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardRadarRequestPerfRow struct {
	TerminalTotal     int64
	SucceededTotal    int64
	FailedTotal       int64
	CanceledTotal     int64
	PendingTotal      int64
	TimeoutTotal      int64
	LatencyAvg        float64
	LatencyP50        float64
	LatencyP90        float64
	LatencyP95        float64
	LatencyP99        float64
	LatencySample     int64
	GatewayTtftAvg    float64
	GatewayTtftP50    float64
	GatewayTtftP90    float64
	GatewayTtftP95    float64
	GatewayTtftP99    float64
	GatewayTtftSample int64
}

// M9+ 概览运营雷达（§3.1 重构）只读聚合。全部纯只读、不引入新业务事实。
// 约定同 dashboard.sql：金额走 NUMERIC（service 格式化为十进制字符串，绝不经 float）；
// 时间区间 [from, to)（左闭右开）；可空 from_time/to_time（narg，NULL = 不过滤）。
// 性能/延迟以 request_records 时间戳推导（无预存延迟列）：
//
//	延迟 = completed_at - started_at；Gateway TTFT 仅对 stream=true 使用 gateway_first_token_at - started_at（毫秒）。
//
// percentile_cont 自动忽略 ORDER BY 中的 NULL 行，故用 CASE 把非目标行置 NULL。
// DashboardRadarRequestPerf 在区间内一次性返回请求终态计数 + 超时数 + 延迟/Gateway TTFT 分位数（request 粒度）。
func (q *Queries) DashboardRadarRequestPerf(ctx context.Context, arg DashboardRadarRequestPerfParams) (DashboardRadarRequestPerfRow, error) {
	row := q.db.QueryRow(ctx, dashboardRadarRequestPerf, arg.FromTime, arg.ToTime)
	var i DashboardRadarRequestPerfRow
	err := row.Scan(
		&i.TerminalTotal,
		&i.SucceededTotal,
		&i.FailedTotal,
		&i.CanceledTotal,
		&i.PendingTotal,
		&i.TimeoutTotal,
		&i.LatencyAvg,
		&i.LatencyP50,
		&i.LatencyP90,
		&i.LatencyP95,
		&i.LatencyP99,
		&i.LatencySample,
		&i.GatewayTtftAvg,
		&i.GatewayTtftP50,
		&i.GatewayTtftP90,
		&i.GatewayTtftP95,
		&i.GatewayTtftP99,
		&i.GatewayTtftSample,
	)
	return i, err
}

const dashboardRadarSettlementBacklog = `-- name: DashboardRadarSettlementBacklog :one
SELECT
    COUNT(*) FILTER (WHERE status IN ('pending', 'running')) AS active_total,
    COUNT(*) FILTER (WHERE status = 'dead') AS dead_total
FROM settlement_recovery_jobs
`

type DashboardRadarSettlementBacklogRow struct {
	ActiveTotal int64
	DeadTotal   int64
}

// DashboardRadarSettlementBacklog 返回结算补偿任务积压（时点值，无时间过滤）：
// active = pending+running（自动重试中），dead = 已耗尽需人工。
func (q *Queries) DashboardRadarSettlementBacklog(ctx context.Context) (DashboardRadarSettlementBacklogRow, error) {
	row := q.db.QueryRow(ctx, dashboardRadarSettlementBacklog)
	var i DashboardRadarSettlementBacklogRow
	err := row.Scan(&i.ActiveTotal, &i.DeadTotal)
	return i, err
}

const dashboardRadarThroughput = `-- name: DashboardRadarThroughput :one
SELECT
    COALESCE(SUM(u.output_tokens_total), 0)::bigint AS output_tokens,
    COALESCE(SUM(
        CASE
            WHEN r.completed_at IS NOT NULL
            THEN EXTRACT(EPOCH FROM (
                r.completed_at - COALESCE(
                    CASE WHEN r.stream = TRUE THEN r.gateway_first_token_at END,
                    r.started_at
                )
            ))
        END
    ), 0)::float8 AS generation_seconds
FROM request_records r
JOIN usage_records u ON u.request_record_id = r.id
WHERE r.status = 'succeeded'
  AND ($1::timestamptz IS NULL OR r.created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR r.created_at < $2::timestamptz)
`

type DashboardRadarThroughputParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardRadarThroughputRow struct {
	OutputTokens      int64
	GenerationSeconds float64
}

// DashboardRadarThroughput 汇总成功请求的输出 token 与生成耗时（秒），service 据此算 TPS。
// 流式生成耗时优先用 completed_at - gateway_first_token_at；非流式和缺 TTFT 时使用 started_at。
func (q *Queries) DashboardRadarThroughput(ctx context.Context, arg DashboardRadarThroughputParams) (DashboardRadarThroughputRow, error) {
	row := q.db.QueryRow(ctx, dashboardRadarThroughput, arg.FromTime, arg.ToTime)
	var i DashboardRadarThroughputRow
	err := row.Scan(&i.OutputTokens, &i.GenerationSeconds)
	return i, err
}

const dashboardRadarTokens = `-- name: DashboardRadarTokens :one
WITH cache_usage AS (
    SELECT id, request_record_id, uncached_input_tokens, uncached_input_tokens_state, cache_read_input_tokens, cache_read_input_tokens_state, cache_creation_5m_input_tokens, cache_creation_5m_input_tokens_state, cache_creation_1h_input_tokens, cache_creation_1h_input_tokens_state, output_tokens_total, output_tokens_total_state, reasoning_output_tokens, reasoning_output_tokens_state, usage_source, usage_mapping_version, created_at, cache_creation_30m_input_tokens, cache_creation_30m_input_tokens_state
    FROM usage_records
    WHERE usage_source IN ('upstream_response', 'upstream_stream')
      AND ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
      AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
),
cache AS (
    SELECT
        COALESCE(SUM(uncached_input_tokens) FILTER (WHERE
            uncached_input_tokens_state = 'known'
            AND cache_read_input_tokens_state = 'known'
            AND cache_creation_5m_input_tokens_state <> 'unknown'
            AND cache_creation_1h_input_tokens_state <> 'unknown'
            AND cache_creation_30m_input_tokens_state <> 'unknown'
            AND uncached_input_tokens + cache_read_input_tokens
                + cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens > 0
        ), 0)::bigint AS metric_uncached_input,
        COALESCE(SUM(cache_read_input_tokens) FILTER (WHERE
            uncached_input_tokens_state = 'known'
            AND cache_read_input_tokens_state = 'known'
            AND cache_creation_5m_input_tokens_state <> 'unknown'
            AND cache_creation_1h_input_tokens_state <> 'unknown'
            AND cache_creation_30m_input_tokens_state <> 'unknown'
            AND uncached_input_tokens + cache_read_input_tokens
                + cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens > 0
        ), 0)::bigint AS metric_cache_read_input,
        COALESCE(SUM(cache_creation_5m_input_tokens) FILTER (WHERE
            uncached_input_tokens_state = 'known'
            AND cache_read_input_tokens_state = 'known'
            AND cache_creation_5m_input_tokens_state <> 'unknown'
            AND cache_creation_1h_input_tokens_state <> 'unknown'
            AND cache_creation_30m_input_tokens_state <> 'unknown'
            AND uncached_input_tokens + cache_read_input_tokens
                + cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens > 0
        ), 0)::bigint AS metric_cache_creation_5m_input,
        COALESCE(SUM(cache_creation_1h_input_tokens) FILTER (WHERE
            uncached_input_tokens_state = 'known'
            AND cache_read_input_tokens_state = 'known'
            AND cache_creation_5m_input_tokens_state <> 'unknown'
            AND cache_creation_1h_input_tokens_state <> 'unknown'
            AND cache_creation_30m_input_tokens_state <> 'unknown'
            AND uncached_input_tokens + cache_read_input_tokens
                + cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens > 0
        ), 0)::bigint AS metric_cache_creation_1h_input,
        COALESCE(SUM(cache_creation_30m_input_tokens) FILTER (WHERE
            uncached_input_tokens_state = 'known'
            AND cache_read_input_tokens_state = 'known'
            AND cache_creation_5m_input_tokens_state <> 'unknown'
            AND cache_creation_1h_input_tokens_state <> 'unknown'
            AND cache_creation_30m_input_tokens_state <> 'unknown'
            AND uncached_input_tokens + cache_read_input_tokens
                + cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens > 0
        ), 0)::bigint AS metric_cache_creation_30m_input,
        COUNT(*) AS cache_usage_records,
        COUNT(*) FILTER (WHERE
            uncached_input_tokens_state = 'known'
            AND cache_read_input_tokens_state = 'known'
            AND cache_creation_5m_input_tokens_state <> 'unknown'
            AND cache_creation_1h_input_tokens_state <> 'unknown'
            AND cache_creation_30m_input_tokens_state <> 'unknown'
            AND uncached_input_tokens + cache_read_input_tokens
                + cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens > 0
        ) AS cache_evaluable_records,
        COUNT(*) FILTER (WHERE cache_read_input_tokens_state = 'not_applicable') AS cache_read_not_applicable_records
    FROM cache_usage
)
SELECT
    COALESCE(SUM(uncached_input_tokens), 0)::bigint AS uncached_input,
    COALESCE(SUM(cache_read_input_tokens), 0)::bigint AS cache_read_input,
    COALESCE(SUM(cache_creation_5m_input_tokens), 0)::bigint AS cache_creation_5m_input,
    COALESCE(SUM(cache_creation_1h_input_tokens), 0)::bigint AS cache_creation_1h_input,
    COALESCE(SUM(cache_creation_30m_input_tokens), 0)::bigint AS cache_creation_30m_input,
    COALESCE(SUM(cache_creation_5m_input_tokens + cache_creation_1h_input_tokens + cache_creation_30m_input_tokens), 0)::bigint AS cache_creation_input,
    COALESCE(SUM(output_tokens_total), 0)::bigint AS output_tokens,
    (SELECT metric_uncached_input FROM cache) AS cache_metric_uncached_input,
    (SELECT metric_cache_read_input FROM cache) AS cache_metric_read_input,
    (SELECT metric_cache_creation_5m_input FROM cache) AS cache_metric_write_5m_input,
    (SELECT metric_cache_creation_1h_input FROM cache) AS cache_metric_write_1h_input,
    (SELECT metric_cache_creation_30m_input FROM cache) AS cache_metric_write_30m_input,
    (SELECT cache_usage_records FROM cache) AS cache_usage_records,
    (SELECT cache_evaluable_records FROM cache) AS cache_evaluable_records,
    (SELECT cache_read_not_applicable_records FROM cache) AS cache_read_not_applicable_records
FROM usage_records
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
`

type DashboardRadarTokensParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardRadarTokensRow struct {
	UncachedInput                 int64
	CacheReadInput                int64
	CacheCreation5mInput          int64
	CacheCreation1hInput          int64
	CacheCreation30mInput         int64
	CacheCreationInput            int64
	OutputTokens                  int64
	CacheMetricUncachedInput      int64
	CacheMetricReadInput          int64
	CacheMetricWrite5mInput       int64
	CacheMetricWrite1hInput       int64
	CacheMetricWrite30mInput      int64
	CacheUsageRecords             int64
	CacheEvaluableRecords         int64
	CacheReadNotApplicableRecords int64
}

// DashboardRadarTokens 在区间内汇总 token 分项（供缓存率与 token 总量卡）。
func (q *Queries) DashboardRadarTokens(ctx context.Context, arg DashboardRadarTokensParams) (DashboardRadarTokensRow, error) {
	row := q.db.QueryRow(ctx, dashboardRadarTokens, arg.FromTime, arg.ToTime)
	var i DashboardRadarTokensRow
	err := row.Scan(
		&i.UncachedInput,
		&i.CacheReadInput,
		&i.CacheCreation5mInput,
		&i.CacheCreation1hInput,
		&i.CacheCreation30mInput,
		&i.CacheCreationInput,
		&i.OutputTokens,
		&i.CacheMetricUncachedInput,
		&i.CacheMetricReadInput,
		&i.CacheMetricWrite5mInput,
		&i.CacheMetricWrite1hInput,
		&i.CacheMetricWrite30mInput,
		&i.CacheUsageRecords,
		&i.CacheEvaluableRecords,
		&i.CacheReadNotApplicableRecords,
	)
	return i, err
}

const dashboardRequestsTimeseries = `-- name: DashboardRequestsTimeseries :many
SELECT
    date_trunc($1::text, created_at)::timestamptz AS bucket,
    COUNT(*) FILTER (WHERE status IN ('succeeded', 'failed')) AS total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS succeeded
FROM request_records
WHERE ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
GROUP BY bucket
ORDER BY bucket
`

type DashboardRequestsTimeseriesParams struct {
	Unit     string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardRequestsTimeseriesRow struct {
	Bucket    pgtype.Timestamptz
	Total     int64
	Succeeded int64
}

// DashboardRequestsTimeseries 按时间桶（hour|day，UTC 截断）聚合请求数与成功数，供前端画折线。
func (q *Queries) DashboardRequestsTimeseries(ctx context.Context, arg DashboardRequestsTimeseriesParams) ([]DashboardRequestsTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardRequestsTimeseries, arg.Unit, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRequestsTimeseriesRow
	for rows.Next() {
		var i DashboardRequestsTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.Total, &i.Succeeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRevenueByCurrency = `-- name: DashboardRevenueByCurrency :many

SELECT currency, COALESCE(SUM(amount), 0)::numeric AS total
FROM ledger_entries
WHERE entry_type = 'debit'
  AND ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
GROUP BY currency
ORDER BY currency
`

type DashboardRevenueByCurrencyParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardRevenueByCurrencyRow struct {
	Currency string
	Total    pgtype.Numeric
}

// M9 工作台看板（运营首页只读聚合）。全部纯只读、不引入新业务事实。
// 约定：金额走 NUMERIC（service 层格式化为十进制字符串，绝不经 float）；
// 时间范围一律用可空 from_time/to_time（narg，NULL = 不过滤）；
// 区间口径 [from, to)（左闭右开），与 M6 列表过滤一致。
// DashboardRevenueByCurrency 在区间内按币种汇总平台收入（客户结算扣费 = entry_type='debit'）。
func (q *Queries) DashboardRevenueByCurrency(ctx context.Context, arg DashboardRevenueByCurrencyParams) ([]DashboardRevenueByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, dashboardRevenueByCurrency, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRevenueByCurrencyRow
	for rows.Next() {
		var i DashboardRevenueByCurrencyRow
		if err := rows.Scan(&i.Currency, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSpendTimeseries = `-- name: DashboardSpendTimeseries :many
SELECT
    date_trunc($1::text, created_at)::timestamptz AS bucket,
    currency,
    COALESCE(SUM(amount), 0)::numeric AS total
FROM ledger_entries
WHERE entry_type = 'debit'
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
GROUP BY bucket, currency
ORDER BY bucket, currency
`

type DashboardSpendTimeseriesParams struct {
	Unit     string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardSpendTimeseriesRow struct {
	Bucket   pgtype.Timestamptz
	Currency string
	Total    pgtype.Numeric
}

// DashboardSpendTimeseries 按时间桶 + 币种聚合平台收入（debit），spend 多币种各成一线。
func (q *Queries) DashboardSpendTimeseries(ctx context.Context, arg DashboardSpendTimeseriesParams) ([]DashboardSpendTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardSpendTimeseries, arg.Unit, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardSpendTimeseriesRow
	for rows.Next() {
		var i DashboardSpendTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.Currency, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTokensTimeseries = `-- name: DashboardTokensTimeseries :many
SELECT
    date_trunc($1::text, created_at)::timestamptz AS bucket,
    COALESCE(SUM(
        uncached_input_tokens
        + cache_read_input_tokens
        + cache_creation_5m_input_tokens
        + cache_creation_1h_input_tokens
        + cache_creation_30m_input_tokens
    ), 0)::bigint AS input_tokens,
    COALESCE(SUM(output_tokens_total), 0)::bigint AS output_tokens
FROM usage_records
WHERE ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
GROUP BY bucket
ORDER BY bucket
`

type DashboardTokensTimeseriesParams struct {
	Unit     string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardTokensTimeseriesRow struct {
	Bucket       pgtype.Timestamptz
	InputTokens  int64
	OutputTokens int64
}

// DashboardTokensTimeseries 按时间桶聚合 input/output token 用量。
func (q *Queries) DashboardTokensTimeseries(ctx context.Context, arg DashboardTokensTimeseriesParams) ([]DashboardTokensTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardTokensTimeseries, arg.Unit, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTokensTimeseriesRow
	for rows.Next() {
		var i DashboardTokensTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.InputTokens, &i.OutputTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopErrors = `-- name: DashboardTopErrors :many
SELECT
    COALESCE(NULLIF(error_code, ''), 'unknown')::text AS error_code,
    COUNT(*) AS total,
    SUM(COUNT(*)) OVER ()::bigint AS failed_total
FROM request_records
WHERE status = 'failed'
  AND ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
GROUP BY COALESCE(NULLIF(error_code, ''), 'unknown')
ORDER BY total DESC, error_code ASC
LIMIT 10
`

type DashboardTopErrorsParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type DashboardTopErrorsRow struct {
	ErrorCode   string
	Total       int64
	FailedTotal int64
}

// DashboardTopErrors 汇总区间内失败请求的错误码分布（Top 10），供概览「失败原因」面板。
// 仅统计 status='failed'（canceled 为客户端取消，不算平台失败）；error_code 空归一为 'unknown'。
// failed_total 用窗口函数返回全部失败总数（在 LIMIT 前求值），供 service 计算占比。
func (q *Queries) DashboardTopErrors(ctx context.Context, arg DashboardTopErrorsParams) ([]DashboardTopErrorsRow, error) {
	rows, err := q.db.Query(ctx, dashboardTopErrors, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTopErrorsRow
	for rows.Next() {
		var i DashboardTopErrorsRow
		if err := rows.Scan(&i.ErrorCode, &i.Total, &i.FailedTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
