// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_recharge_rates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveProviderRechargeRate = `-- name: FindActiveProviderRechargeRate :one
SELECT id, provider_id, provider_currency, nominal_currency, rate, status, source, reason, created_by, effective_from, effective_to, created_at, updated_at
FROM provider_recharge_rates
WHERE provider_id = $1
    AND status = 'enabled'
    AND effective_from <= $2
    AND (
        effective_to IS NULL
        OR effective_to > $2
    )
ORDER BY effective_from DESC, id DESC
LIMIT 1
`

type FindActiveProviderRechargeRateParams struct {
	ProviderID int64
	AtTime     pgtype.Timestamptz
}

// FindActiveProviderRechargeRate 查找指定 provider 在指定时间生效的充值汇率（服务商级，其下所有渠道共享）。
func (q *Queries) FindActiveProviderRechargeRate(ctx context.Context, arg FindActiveProviderRechargeRateParams) (ProviderRechargeRate, error) {
	row := q.db.QueryRow(ctx, findActiveProviderRechargeRate, arg.ProviderID, arg.AtTime)
	var i ProviderRechargeRate
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCurrency,
		&i.NominalCurrency,
		&i.Rate,
		&i.Status,
		&i.Source,
		&i.Reason,
		&i.CreatedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelProviderBilling = `-- name: GetChannelProviderBilling :one
SELECT p.id AS provider_id, p.currency
FROM providers p
JOIN channels c ON c.provider_id = p.id
WHERE c.id = $1
`

type GetChannelProviderBillingRow struct {
	ProviderID int64
	Currency   string
}

// GetChannelProviderBilling 取渠道所属 provider 的 id 与结算币种：
// 倍率路径成本按 provider 币种记账，充值汇率按 provider 解析（settlement / probe 共用）。
func (q *Queries) GetChannelProviderBilling(ctx context.Context, channelID int64) (GetChannelProviderBillingRow, error) {
	row := q.db.QueryRow(ctx, getChannelProviderBilling, channelID)
	var i GetChannelProviderBillingRow
	err := row.Scan(&i.ProviderID, &i.Currency)
	return i, err
}

const getProviderRechargeRate = `-- name: GetProviderRechargeRate :one
SELECT id, provider_id, provider_currency, nominal_currency, rate, status, source, reason, created_by, effective_from, effective_to, created_at, updated_at FROM provider_recharge_rates WHERE id = $1 LIMIT 1
`

// GetProviderRechargeRate 按主键读取单条服务商充值汇率。
func (q *Queries) GetProviderRechargeRate(ctx context.Context, id int64) (ProviderRechargeRate, error) {
	row := q.db.QueryRow(ctx, getProviderRechargeRate, id)
	var i ProviderRechargeRate
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCurrency,
		&i.NominalCurrency,
		&i.Rate,
		&i.Status,
		&i.Source,
		&i.Reason,
		&i.CreatedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
