// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountProxyReferences = `-- name: AdminCountProxyReferences :one
SELECT
    (SELECT count(*) FROM channels c WHERE c.proxy_id = $1::bigint AND c.status <> 'archived')::bigint AS channel_refs,
    (SELECT count(*) FROM subscription_accounts a WHERE a.proxy_id = $1::bigint AND a.status <> 'archived')::bigint AS account_refs
`

type AdminCountProxyReferencesRow struct {
	ChannelRefs int64
	AccountRefs int64
}

func (q *Queries) AdminCountProxyReferences(ctx context.Context, id int64) (AdminCountProxyReferencesRow, error) {
	row := q.db.QueryRow(ctx, adminCountProxyReferences, id)
	var i AdminCountProxyReferencesRow
	err := row.Scan(&i.ChannelRefs, &i.AccountRefs)
	return i, err
}

const adminCreateProxy = `-- name: AdminCreateProxy :one
INSERT INTO proxies (name, protocol, host, port, username, password, url, status, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, protocol, host, port, username, password, url, status, note, created_at, updated_at
`

type AdminCreateProxyParams struct {
	Name     string
	Protocol string
	Host     string
	Port     int32
	Username pgtype.Text
	Password pgtype.Text
	Url      string
	Status   string
	Note     pgtype.Text
}

func (q *Queries) AdminCreateProxy(ctx context.Context, arg AdminCreateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, adminCreateProxy,
		arg.Name,
		arg.Protocol,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.Url,
		arg.Status,
		arg.Note,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Url,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteProxy = `-- name: AdminDeleteProxy :execrows
DELETE FROM proxies WHERE id = $1
`

// 物理删除；被 channels/subscription_accounts 引用时 FK RESTRICT 报 23503，上层降级 409。
func (q *Queries) AdminDeleteProxy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteProxy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetProxy = `-- name: AdminGetProxy :one
SELECT id, name, protocol, host, port, username, password, url, status, note, created_at, updated_at FROM proxies WHERE id = $1
`

func (q *Queries) AdminGetProxy(ctx context.Context, id int64) (Proxy, error) {
	row := q.db.QueryRow(ctx, adminGetProxy, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Url,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListProxies = `-- name: AdminListProxies :many

SELECT p.id, p.name, p.protocol, p.host, p.port, p.username, p.password, p.url, p.status, p.note, p.created_at, p.updated_at,
       (SELECT count(*) FROM channels c WHERE c.proxy_id = p.id AND c.status <> 'archived')::bigint AS channel_refs,
       (SELECT count(*) FROM subscription_accounts a WHERE a.proxy_id = p.id AND a.status <> 'archived')::bigint AS account_refs
FROM proxies p
ORDER BY p.status, p.name
`

type AdminListProxiesRow struct {
	ID          int64
	Name        string
	Protocol    string
	Host        string
	Port        int32
	Username    pgtype.Text
	Password    pgtype.Text
	Url         string
	Status      string
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ChannelRefs int64
	AccountRefs int64
}

// 出站代理实体管理（网关中心 · 代理）。
// 引用计数随行返回：删除护栏（被引用 → 409）与「停用后引用方回退直连」的提示都靠它。
func (q *Queries) AdminListProxies(ctx context.Context) ([]AdminListProxiesRow, error) {
	rows, err := q.db.Query(ctx, adminListProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListProxiesRow
	for rows.Next() {
		var i AdminListProxiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protocol,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.Url,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelRefs,
			&i.AccountRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetProxyStatus = `-- name: AdminSetProxyStatus :one
UPDATE proxies
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, protocol, host, port, username, password, url, status, note, created_at, updated_at
`

type AdminSetProxyStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) AdminSetProxyStatus(ctx context.Context, arg AdminSetProxyStatusParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, adminSetProxyStatus, arg.ID, arg.Status)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Url,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateProxy = `-- name: AdminUpdateProxy :one
UPDATE proxies
SET name = $2,
    protocol = $3,
    host = $4,
    port = $5,
    username = $6,
    password = $7,
    url = $8,
    note = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, protocol, host, port, username, password, url, status, note, created_at, updated_at
`

type AdminUpdateProxyParams struct {
	ID       int64
	Name     string
	Protocol string
	Host     string
	Port     int32
	Username pgtype.Text
	Password pgtype.Text
	Url      string
	Note     pgtype.Text
}

func (q *Queries) AdminUpdateProxy(ctx context.Context, arg AdminUpdateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, adminUpdateProxy,
		arg.ID,
		arg.Name,
		arg.Protocol,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.Url,
		arg.Note,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Url,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
