// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reconcileCostLedgerMismatch = `-- name: ReconcileCostLedgerMismatch :many

SELECT cs.request_record_id, cs.total_cost_amount, cs.currency, ple.amount AS ledger_amount, ple.currency AS ledger_currency
FROM cost_snapshots cs
JOIN provider_ledger_entries ple
  ON ple.request_record_id = cs.request_record_id AND ple.entry_type = 'usage_debit'
WHERE cs.created_at >= $1 AND cs.created_at < $2
  AND (ple.amount <> cs.total_cost_amount OR ple.currency <> cs.currency)
LIMIT 20
`

type ReconcileCostLedgerMismatchParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type ReconcileCostLedgerMismatchRow struct {
	RequestRecordID int64
	TotalCostAmount pgtype.Numeric
	Currency        string
	LedgerAmount    pgtype.Numeric
	LedgerCurrency  string
}

// 每日对账不变量（PLAN §9.1，fx-reconciliation worker 专用）。
// 思路：同一笔钱的两条独立表示互相验证，任何一路被改坏当天报警。
// 各查询 LIMIT 20：对账只需要「有没有 + 例子」，不需要全量清单。
// I1｜成本分录 = 成本快照：每笔已结算请求的 provider 扣款金额/币种必须与成本快照一致。
func (q *Queries) ReconcileCostLedgerMismatch(ctx context.Context, arg ReconcileCostLedgerMismatchParams) ([]ReconcileCostLedgerMismatchRow, error) {
	rows, err := q.db.Query(ctx, reconcileCostLedgerMismatch, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcileCostLedgerMismatchRow
	for rows.Next() {
		var i ReconcileCostLedgerMismatchRow
		if err := rows.Scan(
			&i.RequestRecordID,
			&i.TotalCostAmount,
			&i.Currency,
			&i.LedgerAmount,
			&i.LedgerCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileFxCompleteness = `-- name: ReconcileFxCompleteness :many
SELECT id
FROM cost_snapshots
WHERE created_at >= $1 AND created_at < $2
  AND (
      (currency = 'USD' AND (fx_rate IS NOT NULL OR total_cost_amount_usd <> total_cost_amount))
   OR (currency <> 'USD' AND (fx_rate IS NULL OR fx_rate_date IS NULL))
  )
LIMIT 20
`

type ReconcileFxCompletenessParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

// I2｜快照汇率完备性哨兵：CHECK 约束是主防线，此查询防「约束被误删」。
func (q *Queries) ReconcileFxCompleteness(ctx context.Context, arg ReconcileFxCompletenessParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, reconcileFxCompleteness, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileFxConversion = `-- name: ReconcileFxConversion :many
SELECT id, total_cost_amount, fx_rate, total_cost_amount_usd
FROM cost_snapshots
WHERE created_at >= $1 AND created_at < $2
  AND currency <> 'USD'
  AND total_cost_amount_usd <> round(total_cost_amount / fx_rate, 10)
LIMIT 20
`

type ReconcileFxConversionParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type ReconcileFxConversionRow struct {
	ID                 int64
	TotalCostAmount    pgtype.Numeric
	FxRate             pgtype.Numeric
	TotalCostAmountUsd pgtype.Numeric
}

// I3｜换算冗余一致：usd 归一列必须等于 原币总额 ÷ 钉住汇率 的单次舍入值（D4 审计抓手）。
// round(numeric, 10) 为四舍五入，与 Go 侧 big.Rat half-up 单次舍入同口径（金额恒非负）。
func (q *Queries) ReconcileFxConversion(ctx context.Context, arg ReconcileFxConversionParams) ([]ReconcileFxConversionRow, error) {
	rows, err := q.db.Query(ctx, reconcileFxConversion, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcileFxConversionRow
	for rows.Next() {
		var i ReconcileFxConversionRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalCostAmount,
			&i.FxRate,
			&i.TotalCostAmountUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileProviderBalance = `-- name: ReconcileProviderBalance :many
SELECT pb.provider_id, pb.currency, pb.balance, COALESCE(agg.total, 0)::numeric AS ledger_total
FROM provider_balances pb
LEFT JOIN (
    SELECT provider_id, currency,
        SUM(CASE WHEN entry_type IN ('usage_debit', 'probe_debit', 'adjustment_debit') THEN -amount ELSE amount END) AS total
    FROM provider_ledger_entries
    GROUP BY provider_id, currency
) agg ON agg.provider_id = pb.provider_id AND agg.currency = pb.currency
WHERE pb.balance <> COALESCE(agg.total, 0)
LIMIT 20
`

type ReconcileProviderBalanceRow struct {
	ProviderID  int64
	Currency    string
	Balance     pgtype.Numeric
	LedgerTotal pgtype.Numeric
}

// I4｜余额 = 分录累计（按 provider × currency）：余额行永远等于账本签名和（账本只追加）。
func (q *Queries) ReconcileProviderBalance(ctx context.Context) ([]ReconcileProviderBalanceRow, error) {
	rows, err := q.db.Query(ctx, reconcileProviderBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcileProviderBalanceRow
	for rows.Next() {
		var i ReconcileProviderBalanceRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.Currency,
			&i.Balance,
			&i.LedgerTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
