// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing_traces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoutingDecisionTraceByRequestID = `-- name: GetRoutingDecisionTraceByRequestID :one
SELECT
    t.id,
    t.request_record_id,
    t.mode,
    t.requested_model_id,
    t.protocol,
    t.endpoint,
    t.trace_status,
    t.schema_version,
    t.algorithm_version,
    t.pool_size,
    t.eligible_count,
    t.baseline_order,
    t.actual_scan_order,
    t.attempted_channel_ids,
    t.selected_channel_id,
    t.fallback_count,
    t.final_result,
    t.sticky_key_present,
    t.sticky_before_channel_id,
    t.sticky_before_version,
    t.sticky_action,
    t.sticky_reason,
    t.sticky_after_channel_id,
    t.sticky_after_version,
    t.capacity_wait_ms,
    t.capacity_wait_result,
    t.trace_payload,
    t.created_at,
    t.updated_at,
    r.request_id,
    r.status AS request_status,
    r.final_channel_id
FROM routing_decision_traces t
JOIN request_records r ON r.id = t.request_record_id
WHERE r.request_id = $1
LIMIT 1
`

type GetRoutingDecisionTraceByRequestIDRow struct {
	ID                    int64
	RequestRecordID       int64
	Mode                  string
	RequestedModelID      string
	Protocol              string
	Endpoint              string
	TraceStatus           string
	SchemaVersion         int32
	AlgorithmVersion      string
	PoolSize              int32
	EligibleCount         int32
	BaselineOrder         []int64
	ActualScanOrder       []int64
	AttemptedChannelIds   []int64
	SelectedChannelID     pgtype.Int8
	FallbackCount         int32
	FinalResult           pgtype.Text
	StickyKeyPresent      bool
	StickyBeforeChannelID pgtype.Int8
	StickyBeforeVersion   pgtype.Int8
	StickyAction          pgtype.Text
	StickyReason          pgtype.Text
	StickyAfterChannelID  pgtype.Int8
	StickyAfterVersion    pgtype.Int8
	CapacityWaitMs        pgtype.Int4
	CapacityWaitResult    pgtype.Text
	TracePayload          []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RequestID             string
	RequestStatus         string
	FinalChannelID        pgtype.Int8
}

func (q *Queries) GetRoutingDecisionTraceByRequestID(ctx context.Context, requestID string) (GetRoutingDecisionTraceByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getRoutingDecisionTraceByRequestID, requestID)
	var i GetRoutingDecisionTraceByRequestIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.Mode,
		&i.RequestedModelID,
		&i.Protocol,
		&i.Endpoint,
		&i.TraceStatus,
		&i.SchemaVersion,
		&i.AlgorithmVersion,
		&i.PoolSize,
		&i.EligibleCount,
		&i.BaselineOrder,
		&i.ActualScanOrder,
		&i.AttemptedChannelIds,
		&i.SelectedChannelID,
		&i.FallbackCount,
		&i.FinalResult,
		&i.StickyKeyPresent,
		&i.StickyBeforeChannelID,
		&i.StickyBeforeVersion,
		&i.StickyAction,
		&i.StickyReason,
		&i.StickyAfterChannelID,
		&i.StickyAfterVersion,
		&i.CapacityWaitMs,
		&i.CapacityWaitResult,
		&i.TracePayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
		&i.RequestStatus,
		&i.FinalChannelID,
	)
	return i, err
}

const modelRuntimePool = `-- name: ModelRuntimePool :many
SELECT
    c.id AS channel_id,
    c.name AS channel_name,
    c.status AS channel_status,
    c.credential_valid,
    (c.credential <> '')::boolean AS has_credential,
    (p.origin <> '')::boolean AS has_origin,
    c.protocols,
    c.adapter_key,
    c.priority,
    c.concurrency_limit,
    c.config_revision AS channel_config_revision,
    c.capacity_revision AS channel_capacity_revision,
    p.origin,
    p.origin_revision AS provider_origin_revision,
    p.status_revision AS provider_status_revision,
    p.id AS provider_id,
    p.name AS provider_name,
    p.status AS provider_status,
    COALESCE(m.id, 0)::bigint AS model_db_id,
    (m.id IS NOT NULL)::boolean AS model_exists,
    COALESCE(m.status, '')::text AS model_status,
    COALESCE(cm.status, '')::text AS binding_status,
    (base.id IS NOT NULL)::boolean AS has_model_price,
    COALESCE((cost.id IS NOT NULL OR mult.id IS NOT NULL), false)::boolean AS has_channel_cost,
    COALESCE(base.id, 0)::bigint AS model_price_id,
    COALESCE(base.currency, '')::text AS base_currency,
    COALESCE(base.pricing_unit, '')::text AS base_pricing_unit,
    base.uncached_input_price,
    base.cache_read_input_price,
    base.cache_write_5m_input_price,
    base.cache_write_1h_input_price,
    base.cache_write_30m_input_price,
    base.output_price,
    base.reasoning_output_price,
    COALESCE(cost.id, 0)::bigint AS channel_price_id,
    COALESCE(cost.currency, '')::text AS cost_currency,
    COALESCE(cost.pricing_unit, '')::text AS cost_pricing_unit,
    cost.uncached_input_cost,
    cost.cache_read_input_cost,
    cost.cache_write_5m_input_cost,
    cost.cache_write_1h_input_cost,
    cost.cache_write_30m_input_cost,
    cost.output_cost,
    cost.reasoning_output_cost,
    COALESCE(mult.id, 0)::bigint AS channel_cost_multiplier_id,
    mult.multiplier AS cost_multiplier,
    COALESCE(recharge.id, 0)::bigint AS channel_recharge_factor_id,
    recharge.factor AS recharge_factor
FROM channels c
JOIN providers p ON p.id = c.provider_id
LEFT JOIN models m
  ON NULLIF($1::text, '') IS NOT NULL
 AND m.model_id = $1::text
LEFT JOIN channel_models cm ON cm.channel_id = c.id AND cm.model_id = m.id
LEFT JOIN LATERAL (
    SELECT mp.id, mp.currency, mp.pricing_unit,
           mp.uncached_input_price, mp.cache_read_input_price,
           mp.cache_write_5m_input_price, mp.cache_write_1h_input_price,
           mp.cache_write_30m_input_price, mp.output_price, mp.reasoning_output_price
    FROM model_prices mp
    WHERE mp.model_id = m.id
      AND mp.status = 'enabled'
      AND mp.effective_from <= $2
      AND (mp.effective_to IS NULL OR mp.effective_to > $2)
    ORDER BY mp.effective_from DESC, mp.id DESC
    LIMIT 1
) base ON TRUE
LEFT JOIN LATERAL (
    SELECT cp.id, cp.currency, cp.pricing_unit,
           cp.uncached_input_cost, cp.cache_read_input_cost,
           cp.cache_write_5m_input_cost, cp.cache_write_1h_input_cost,
           cp.cache_write_30m_input_cost, cp.output_cost, cp.reasoning_output_cost
    FROM channel_prices cp
    WHERE cp.channel_id = c.id
      AND cp.model_id = m.id
      AND cp.status = 'enabled'
      AND cp.effective_from <= $2
      AND (cp.effective_to IS NULL OR cp.effective_to > $2)
    ORDER BY cp.effective_from DESC, cp.id DESC
    LIMIT 1
) cost ON TRUE
LEFT JOIN LATERAL (
    SELECT ccm.id, ccm.multiplier
    FROM channel_cost_multipliers ccm
    WHERE ccm.channel_id = c.id
      AND (ccm.model_id = m.id OR ccm.model_id IS NULL)
      AND ccm.status = 'enabled'
      AND ccm.effective_from <= $2
      AND (ccm.effective_to IS NULL OR ccm.effective_to > $2)
    ORDER BY (ccm.model_id IS NULL) ASC, ccm.effective_from DESC, ccm.id DESC
    LIMIT 1
) mult ON TRUE
LEFT JOIN LATERAL (
    SELECT crf.id, crf.factor
    FROM channel_recharge_factors crf
    WHERE crf.channel_id = c.id
      AND crf.status = 'enabled'
      AND crf.effective_from <= $2
      AND (crf.effective_to IS NULL OR crf.effective_to > $2)
    ORDER BY crf.effective_from DESC, crf.id DESC
    LIMIT 1
) recharge ON TRUE
WHERE c.status <> 'archived'
ORDER BY c.priority, c.id
`

type ModelRuntimePoolParams struct {
	ModelID string
	AtTime  pgtype.Timestamptz
}

type ModelRuntimePoolRow struct {
	ChannelID               int64
	ChannelName             string
	ChannelStatus           string
	CredentialValid         bool
	HasCredential           bool
	HasOrigin               bool
	Protocols               []string
	AdapterKey              string
	Priority                int32
	ConcurrencyLimit        pgtype.Int4
	ChannelConfigRevision   int64
	ChannelCapacityRevision int64
	Origin                  string
	ProviderOriginRevision  int64
	ProviderStatusRevision  int64
	ProviderID              int64
	ProviderName            string
	ProviderStatus          string
	ModelDbID               int64
	ModelExists             bool
	ModelStatus             string
	BindingStatus           string
	HasModelPrice           bool
	HasChannelCost          bool
	ModelPriceID            int64
	BaseCurrency            string
	BasePricingUnit         string
	UncachedInputPrice      pgtype.Numeric
	CacheReadInputPrice     pgtype.Numeric
	CacheWrite5mInputPrice  pgtype.Numeric
	CacheWrite1hInputPrice  pgtype.Numeric
	CacheWrite30mInputPrice pgtype.Numeric
	OutputPrice             pgtype.Numeric
	ReasoningOutputPrice    pgtype.Numeric
	ChannelPriceID          int64
	CostCurrency            string
	CostPricingUnit         string
	UncachedInputCost       pgtype.Numeric
	CacheReadInputCost      pgtype.Numeric
	CacheWrite5mInputCost   pgtype.Numeric
	CacheWrite1hInputCost   pgtype.Numeric
	CacheWrite30mInputCost  pgtype.Numeric
	OutputCost              pgtype.Numeric
	ReasoningOutputCost     pgtype.Numeric
	ChannelCostMultiplierID int64
	CostMultiplier          pgtype.Numeric
	ChannelRechargeFactorID int64
	RechargeFactor          pgtype.Numeric
}

// ModelRuntimePool 返回全部未归档渠道及其数据库硬过滤事实，供选路诊断解释
// 「这条渠道为什么没进候选」。
//
// 它故意不做任何过滤：范围就是全部渠道。诊断的价值恰恰在于把被排除的渠道也列出来，
// 并给出被排除的具体原因（渠道停用 / 凭据无效 / 协议不匹配 / 未绑定该模型 / 缺价格等）。
// 过滤后的候选集由 FindModelCandidates 负责，两者互为对照。
func (q *Queries) ModelRuntimePool(ctx context.Context, arg ModelRuntimePoolParams) ([]ModelRuntimePoolRow, error) {
	rows, err := q.db.Query(ctx, modelRuntimePool, arg.ModelID, arg.AtTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRuntimePoolRow
	for rows.Next() {
		var i ModelRuntimePoolRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelStatus,
			&i.CredentialValid,
			&i.HasCredential,
			&i.HasOrigin,
			&i.Protocols,
			&i.AdapterKey,
			&i.Priority,
			&i.ConcurrencyLimit,
			&i.ChannelConfigRevision,
			&i.ChannelCapacityRevision,
			&i.Origin,
			&i.ProviderOriginRevision,
			&i.ProviderStatusRevision,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderStatus,
			&i.ModelDbID,
			&i.ModelExists,
			&i.ModelStatus,
			&i.BindingStatus,
			&i.HasModelPrice,
			&i.HasChannelCost,
			&i.ModelPriceID,
			&i.BaseCurrency,
			&i.BasePricingUnit,
			&i.UncachedInputPrice,
			&i.CacheReadInputPrice,
			&i.CacheWrite5mInputPrice,
			&i.CacheWrite1hInputPrice,
			&i.CacheWrite30mInputPrice,
			&i.OutputPrice,
			&i.ReasoningOutputPrice,
			&i.ChannelPriceID,
			&i.CostCurrency,
			&i.CostPricingUnit,
			&i.UncachedInputCost,
			&i.CacheReadInputCost,
			&i.CacheWrite5mInputCost,
			&i.CacheWrite1hInputCost,
			&i.CacheWrite30mInputCost,
			&i.OutputCost,
			&i.ReasoningOutputCost,
			&i.ChannelCostMultiplierID,
			&i.CostMultiplier,
			&i.ChannelRechargeFactorID,
			&i.RechargeFactor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoutingDecisionTrace = `-- name: UpsertRoutingDecisionTrace :exec
INSERT INTO routing_decision_traces (
    request_record_id, mode, requested_model_id, protocol, endpoint,
    pool_size, algorithm_version,
    sticky_key_present, sticky_before_channel_id, sticky_before_version,
    sticky_action, sticky_reason, sticky_after_channel_id, sticky_after_version,
    trace_status, schema_version, eligible_count, baseline_order, actual_scan_order,
    attempted_channel_ids, selected_channel_id, fallback_count, final_result,
    capacity_wait_ms, capacity_wait_result, trace_payload
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7,
    $8, $9,
    $10, $11, $12,
    $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23,
    $24, $25, $26
)
ON CONFLICT (request_record_id) DO UPDATE SET
    pool_size = EXCLUDED.pool_size,
    sticky_key_present = EXCLUDED.sticky_key_present,
    sticky_before_channel_id = EXCLUDED.sticky_before_channel_id,
    sticky_before_version = EXCLUDED.sticky_before_version,
    sticky_action = EXCLUDED.sticky_action,
    sticky_reason = EXCLUDED.sticky_reason,
    sticky_after_channel_id = EXCLUDED.sticky_after_channel_id,
    sticky_after_version = EXCLUDED.sticky_after_version,
    -- complete 是终态：一旦收口就不再被 partial 覆盖回去。
    trace_status = CASE
        WHEN routing_decision_traces.trace_status = 'complete' THEN 'complete'
        ELSE EXCLUDED.trace_status
    END,
    schema_version = GREATEST(routing_decision_traces.schema_version, EXCLUDED.schema_version),
    eligible_count = EXCLUDED.eligible_count,
    baseline_order = EXCLUDED.baseline_order,
    actual_scan_order = EXCLUDED.actual_scan_order,
    attempted_channel_ids = EXCLUDED.attempted_channel_ids,
    selected_channel_id = COALESCE(EXCLUDED.selected_channel_id, routing_decision_traces.selected_channel_id),
    fallback_count = EXCLUDED.fallback_count,
    final_result = COALESCE(EXCLUDED.final_result, routing_decision_traces.final_result),
    capacity_wait_ms = COALESCE(EXCLUDED.capacity_wait_ms, routing_decision_traces.capacity_wait_ms),
    capacity_wait_result = COALESCE(EXCLUDED.capacity_wait_result, routing_decision_traces.capacity_wait_result),
    trace_payload = EXCLUDED.trace_payload,
    updated_at = now()
`

type UpsertRoutingDecisionTraceParams struct {
	RequestRecordID       int64
	Mode                  string
	RequestedModelID      string
	Protocol              string
	Endpoint              string
	PoolSize              int32
	AlgorithmVersion      string
	StickyKeyPresent      bool
	StickyBeforeChannelID pgtype.Int8
	StickyBeforeVersion   pgtype.Int8
	StickyAction          pgtype.Text
	StickyReason          pgtype.Text
	StickyAfterChannelID  pgtype.Int8
	StickyAfterVersion    pgtype.Int8
	TraceStatus           string
	SchemaVersion         int32
	EligibleCount         int32
	BaselineOrder         []int64
	ActualScanOrder       []int64
	AttemptedChannelIds   []int64
	SelectedChannelID     pgtype.Int8
	FallbackCount         int32
	FinalResult           pgtype.Text
	CapacityWaitMs        pgtype.Int4
	CapacityWaitResult    pgtype.Text
	TracePayload          []byte
}

// 每个进入路由规划的请求恰好一条 trace：规划开始写 partial，生命周期结束幂等升级为 complete（§13.1）。
// partial 不得覆盖已有的 complete：进程异常留下的 partial 是有意义的「尚未收口」，
// 但一条已经收口的 trace 不能被后续 partial 写回退。
func (q *Queries) UpsertRoutingDecisionTrace(ctx context.Context, arg UpsertRoutingDecisionTraceParams) error {
	_, err := q.db.Exec(ctx, upsertRoutingDecisionTrace,
		arg.RequestRecordID,
		arg.Mode,
		arg.RequestedModelID,
		arg.Protocol,
		arg.Endpoint,
		arg.PoolSize,
		arg.AlgorithmVersion,
		arg.StickyKeyPresent,
		arg.StickyBeforeChannelID,
		arg.StickyBeforeVersion,
		arg.StickyAction,
		arg.StickyReason,
		arg.StickyAfterChannelID,
		arg.StickyAfterVersion,
		arg.TraceStatus,
		arg.SchemaVersion,
		arg.EligibleCount,
		arg.BaselineOrder,
		arg.ActualScanOrder,
		arg.AttemptedChannelIds,
		arg.SelectedChannelID,
		arg.FallbackCount,
		arg.FinalResult,
		arg.CapacityWaitMs,
		arg.CapacityWaitResult,
		arg.TracePayload,
	)
	return err
}
