// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing_traces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoutingDecisionTraceByRequestID = `-- name: GetRoutingDecisionTraceByRequestID :one
SELECT
    t.id,
    t.request_record_id,
    t.mode,
    t.requested_model_id,
    t.protocol,
    t.endpoint,
    t.trace_status,
    t.schema_version,
    t.algorithm_version,
    t.pool_size,
    t.eligible_count,
    t.baseline_order,
    t.actual_scan_order,
    t.attempted_channel_ids,
    t.selected_channel_id,
    t.fallback_count,
    t.final_result,
    t.sticky_key_present,
    t.sticky_before_channel_id,
    t.sticky_before_version,
    t.sticky_action,
    t.sticky_reason,
    t.sticky_after_channel_id,
    t.sticky_after_version,
    t.capacity_wait_ms,
    t.capacity_wait_result,
    t.trace_payload,
    t.created_at,
    t.updated_at,
    r.request_id,
    r.status AS request_status,
    r.final_channel_id
FROM routing_decision_traces t
JOIN request_records r ON r.id = t.request_record_id
WHERE r.request_id = $1
LIMIT 1
`

type GetRoutingDecisionTraceByRequestIDRow struct {
	ID                    int64
	RequestRecordID       int64
	Mode                  string
	RequestedModelID      string
	Protocol              string
	Endpoint              string
	TraceStatus           string
	SchemaVersion         int32
	AlgorithmVersion      string
	PoolSize              int32
	EligibleCount         int32
	BaselineOrder         []int64
	ActualScanOrder       []int64
	AttemptedChannelIds   []int64
	SelectedChannelID     pgtype.Int8
	FallbackCount         int32
	FinalResult           pgtype.Text
	StickyKeyPresent      bool
	StickyBeforeChannelID pgtype.Int8
	StickyBeforeVersion   pgtype.Int8
	StickyAction          pgtype.Text
	StickyReason          pgtype.Text
	StickyAfterChannelID  pgtype.Int8
	StickyAfterVersion    pgtype.Int8
	CapacityWaitMs        pgtype.Int4
	CapacityWaitResult    pgtype.Text
	TracePayload          []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RequestID             string
	RequestStatus         string
	FinalChannelID        pgtype.Int8
}

func (q *Queries) GetRoutingDecisionTraceByRequestID(ctx context.Context, requestID string) (GetRoutingDecisionTraceByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getRoutingDecisionTraceByRequestID, requestID)
	var i GetRoutingDecisionTraceByRequestIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.Mode,
		&i.RequestedModelID,
		&i.Protocol,
		&i.Endpoint,
		&i.TraceStatus,
		&i.SchemaVersion,
		&i.AlgorithmVersion,
		&i.PoolSize,
		&i.EligibleCount,
		&i.BaselineOrder,
		&i.ActualScanOrder,
		&i.AttemptedChannelIds,
		&i.SelectedChannelID,
		&i.FallbackCount,
		&i.FinalResult,
		&i.StickyKeyPresent,
		&i.StickyBeforeChannelID,
		&i.StickyBeforeVersion,
		&i.StickyAction,
		&i.StickyReason,
		&i.StickyAfterChannelID,
		&i.StickyAfterVersion,
		&i.CapacityWaitMs,
		&i.CapacityWaitResult,
		&i.TracePayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
		&i.RequestStatus,
		&i.FinalChannelID,
	)
	return i, err
}

const listChannelNames = `-- name: ListChannelNames :many
SELECT c.id, c.name, c.status
FROM channels c
WHERE c.id = ANY($1::bigint[])
ORDER BY c.id
`

type ListChannelNamesRow struct {
	ID     int64
	Name   string
	Status string
}

// ListChannelNames 按 id 批量取渠道名，供选路统计把 channel_id 翻译成可读名称。
func (q *Queries) ListChannelNames(ctx context.Context, channelIds []int64) ([]ListChannelNamesRow, error) {
	rows, err := q.db.Query(ctx, listChannelNames, channelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelNamesRow
	for rows.Next() {
		var i ListChannelNamesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveTrafficChannels = `-- name: LiveTrafficChannels :many
SELECT
    c.id AS channel_id,
    c.name AS channel_name,
    c.status AS channel_status,
    c.credential_valid,
    c.priority,
    c.concurrency_limit,
    p.id AS provider_id,
    p.name AS provider_name,
    p.status AS provider_status,
    (
        SELECT COUNT(*) FROM channel_models cm
        WHERE cm.channel_id = c.id AND cm.status = 'enabled'
    ) AS bound_models
FROM channels c
JOIN providers p ON p.id = c.provider_id
WHERE c.status <> 'archived'
ORDER BY c.id
`

type LiveTrafficChannelsRow struct {
	ChannelID        int64
	ChannelName      string
	ChannelStatus    string
	CredentialValid  bool
	Priority         int32
	ConcurrencyLimit pgtype.Int4
	ProviderID       int64
	ProviderName     string
	ProviderStatus   string
	BoundModels      int64
}

// LiveTrafficChannels 列出参与流量的渠道及其静态事实，运行态由 Redis 补齐。
// 归档渠道不出现；停用渠道保留，因为「配了却不在跑」本身是要看的信息。
func (q *Queries) LiveTrafficChannels(ctx context.Context) ([]LiveTrafficChannelsRow, error) {
	rows, err := q.db.Query(ctx, liveTrafficChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveTrafficChannelsRow
	for rows.Next() {
		var i LiveTrafficChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelStatus,
			&i.CredentialValid,
			&i.Priority,
			&i.ConcurrencyLimit,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderStatus,
			&i.BoundModels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveTrafficModels = `-- name: LiveTrafficModels :many
SELECT
    r.requested_model_id,
    COUNT(*) FILTER (WHERE r.status IN ('succeeded', 'failed')) AS request_total,
    COUNT(*) FILTER (WHERE r.status = 'succeeded') AS request_succeeded
FROM request_records r
WHERE r.created_at >= $1::timestamptz
GROUP BY 1
HAVING COUNT(*) > 0
ORDER BY request_total DESC
LIMIT $2
`

type LiveTrafficModelsParams struct {
	FromTime pgtype.Timestamptz
	RowLimit int32
}

type LiveTrafficModelsRow struct {
	RequestedModelID string
	RequestTotal     int64
	RequestSucceeded int64
}

// LiveTrafficModels 统计本分钟各模型的请求量。
// 与渠道侧的 Redis 观测不同源：模型维度的 in-flight 需要改准入热路径才能统计，
// 不值得为一个展示字段承担那个风险，所以这里只给已落库的请求数。
func (q *Queries) LiveTrafficModels(ctx context.Context, arg LiveTrafficModelsParams) ([]LiveTrafficModelsRow, error) {
	rows, err := q.db.Query(ctx, liveTrafficModels, arg.FromTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveTrafficModelsRow
	for rows.Next() {
		var i LiveTrafficModelsRow
		if err := rows.Scan(&i.RequestedModelID, &i.RequestTotal, &i.RequestSucceeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelRoutingExclusionStats = `-- name: ModelRoutingExclusionStats :many
WITH exclusions AS (
    SELECT
        candidate.value->>'excluded_reason' AS excluded_reason,
        (candidate.value->>'channel_id')::bigint AS channel_id
    FROM routing_decision_traces t
    CROSS JOIN LATERAL jsonb_array_elements(
        COALESCE(t.trace_payload->'candidates', '[]'::jsonb)
    ) AS candidate(value)
    WHERE t.requested_model_id = $1
      AND t.trace_status = 'complete'
      AND t.created_at >= $2::timestamptz
      AND t.created_at < $3::timestamptz
      AND COALESCE((candidate.value->>'eligible')::boolean, false) = false
      AND COALESCE(candidate.value->>'excluded_reason', '') <> ''
), per_reason_channel AS (
    SELECT excluded_reason, channel_id, COUNT(*) AS hits
    FROM exclusions
    GROUP BY 1, 2
)
SELECT
    e.excluded_reason::text AS excluded_reason,
    SUM(e.hits)::bigint AS occurrences,
    ((array_agg(e.channel_id ORDER BY e.hits DESC, e.channel_id))[1])::bigint AS sample_channel_id,
    COUNT(DISTINCT e.channel_id)::bigint AS channels_touched
FROM per_reason_channel e
GROUP BY 1
ORDER BY occurrences DESC, 1
`

type ModelRoutingExclusionStatsParams struct {
	RequestedModelID string
	FromTime         pgtype.Timestamptz
	ToTime           pgtype.Timestamptz
}

type ModelRoutingExclusionStatsRow struct {
	ExcludedReason  string
	Occurrences     int64
	SampleChannelID int64
	ChannelsTouched int64
}

// ModelRoutingExclusionStats 统计候选为什么没被用上。
//
// 成本提示：trace_payload.candidates 装的是全池非 archived 渠道，不是该模型的绑定渠道，
// 因此展开后的元素数约等于「选路次数 × 全池渠道数」。调用方必须限制时间窗（当前 24 小时），
// 否则这条查询会随保留期线性变慢。
//
// sample_channel_id 取该原因下出现次数最多的渠道，用于在界面上指认「主要是谁」。
func (q *Queries) ModelRoutingExclusionStats(ctx context.Context, arg ModelRoutingExclusionStatsParams) ([]ModelRoutingExclusionStatsRow, error) {
	rows, err := q.db.Query(ctx, modelRoutingExclusionStats, arg.RequestedModelID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRoutingExclusionStatsRow
	for rows.Next() {
		var i ModelRoutingExclusionStatsRow
		if err := rows.Scan(
			&i.ExcludedReason,
			&i.Occurrences,
			&i.SampleChannelID,
			&i.ChannelsTouched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelRoutingOutcomeStats = `-- name: ModelRoutingOutcomeStats :many
SELECT
    COALESCE(t.final_result, 'unknown')::text AS final_result,
    COUNT(*) AS occurrences
FROM routing_decision_traces t
WHERE t.requested_model_id = $1
  AND t.trace_status = 'complete'
  AND t.created_at >= $2::timestamptz
  AND t.created_at < $3::timestamptz
GROUP BY 1
ORDER BY occurrences DESC, 1
`

type ModelRoutingOutcomeStatsParams struct {
	RequestedModelID string
	FromTime         pgtype.Timestamptz
	ToTime           pgtype.Timestamptz
}

type ModelRoutingOutcomeStatsRow struct {
	FinalResult string
	Occurrences int64
}

// ModelRoutingOutcomeStats 统计选路终态分布（success / no_available_channel / ...）。
func (q *Queries) ModelRoutingOutcomeStats(ctx context.Context, arg ModelRoutingOutcomeStatsParams) ([]ModelRoutingOutcomeStatsRow, error) {
	rows, err := q.db.Query(ctx, modelRoutingOutcomeStats, arg.RequestedModelID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRoutingOutcomeStatsRow
	for rows.Next() {
		var i ModelRoutingOutcomeStatsRow
		if err := rows.Scan(&i.FinalResult, &i.Occurrences); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelRoutingSelectionStats = `-- name: ModelRoutingSelectionStats :many

SELECT
    t.selected_channel_id,
    COUNT(*) AS selections
FROM routing_decision_traces t
WHERE t.requested_model_id = $1
  AND t.trace_status = 'complete'
  AND t.created_at >= $2::timestamptz
  AND t.created_at < $3::timestamptz
GROUP BY 1
ORDER BY selections DESC, t.selected_channel_id
`

type ModelRoutingSelectionStatsParams struct {
	RequestedModelID string
	FromTime         pgtype.Timestamptz
	ToTime           pgtype.Timestamptz
}

type ModelRoutingSelectionStatsRow struct {
	SelectedChannelID pgtype.Int8
	Selections        int64
}

// 以下三个聚合共用同一个窗口口径：按 requested_model_id（本表冗余列，不必 JOIN
// request_records）加 created_at 范围，命中 idx_routing_decision_traces_model_created。
// 只统计 trace_status='complete'：partial 是进行中或进程崩溃遗留，payload 不完整；
// legacy_sampled 是改造前的采样行，schema 不同。
// ModelRoutingSelectionStats 统计流量最终落在哪条渠道。
// selected_channel_id 为 NULL 表示这次选路没能选出渠道（无可用候选等），单独归一行。
func (q *Queries) ModelRoutingSelectionStats(ctx context.Context, arg ModelRoutingSelectionStatsParams) ([]ModelRoutingSelectionStatsRow, error) {
	rows, err := q.db.Query(ctx, modelRoutingSelectionStats, arg.RequestedModelID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRoutingSelectionStatsRow
	for rows.Next() {
		var i ModelRoutingSelectionStatsRow
		if err := rows.Scan(&i.SelectedChannelID, &i.Selections); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelRoutingTraceCount = `-- name: ModelRoutingTraceCount :one
SELECT COUNT(*) AS total
FROM routing_decision_traces t
WHERE t.requested_model_id = $1
  AND t.created_at >= $2::timestamptz
  AND t.created_at < $3::timestamptz
`

type ModelRoutingTraceCountParams struct {
	RequestedModelID string
	FromTime         pgtype.Timestamptz
	ToTime           pgtype.Timestamptz
}

func (q *Queries) ModelRoutingTraceCount(ctx context.Context, arg ModelRoutingTraceCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, modelRoutingTraceCount, arg.RequestedModelID, arg.FromTime, arg.ToTime)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const modelRoutingTraceList = `-- name: ModelRoutingTraceList :many
SELECT
    t.created_at,
    t.final_result,
    t.eligible_count,
    COALESCE(jsonb_array_length(t.trace_payload->'candidates'), 0)::int AS candidate_count,
    t.selected_channel_id,
    t.fallback_count,
    t.capacity_wait_result,
    r.request_id
FROM routing_decision_traces t
JOIN request_records r ON r.id = t.request_record_id
WHERE t.requested_model_id = $1
  AND t.created_at >= $2::timestamptz
  AND t.created_at < $3::timestamptz
ORDER BY t.created_at DESC
LIMIT $5 OFFSET $4
`

type ModelRoutingTraceListParams struct {
	RequestedModelID string
	FromTime         pgtype.Timestamptz
	ToTime           pgtype.Timestamptz
	PageOffset       int32
	PageLimit        int32
}

type ModelRoutingTraceListRow struct {
	CreatedAt          pgtype.Timestamptz
	FinalResult        pgtype.Text
	EligibleCount      int32
	CandidateCount     int32
	SelectedChannelID  pgtype.Int8
	FallbackCount      int32
	CapacityWaitResult pgtype.Text
	RequestID          string
}

// ModelRoutingTraceList 是最近选路列表（分页），供逐条下钻到完整 trace。
// candidate_count 用 payload 里的候选数而非 pool_size：后者是全池渠道数，
// 与界面上「候选 N 条」不是一回事。
func (q *Queries) ModelRoutingTraceList(ctx context.Context, arg ModelRoutingTraceListParams) ([]ModelRoutingTraceListRow, error) {
	rows, err := q.db.Query(ctx, modelRoutingTraceList,
		arg.RequestedModelID,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRoutingTraceListRow
	for rows.Next() {
		var i ModelRoutingTraceListRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.FinalResult,
			&i.EligibleCount,
			&i.CandidateCount,
			&i.SelectedChannelID,
			&i.FallbackCount,
			&i.CapacityWaitResult,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelRuntimePool = `-- name: ModelRuntimePool :many
SELECT
    c.id AS channel_id,
    c.name AS channel_name,
    c.status AS channel_status,
    c.credential_valid,
    (c.credential <> '')::boolean AS has_credential,
    c.supply_form,
    EXISTS (
        SELECT 1 FROM subscription_accounts sa
        WHERE sa.channel_id = c.id AND sa.status = 'enabled'
    )::boolean AS has_schedulable_account,
    (p.origin <> '')::boolean AS has_origin,
    c.protocols,
    c.adapter_key,
    c.priority,
    c.concurrency_limit,
    c.config_revision AS channel_config_revision,
    c.capacity_revision AS channel_capacity_revision,
    p.origin,
    p.origin_revision AS provider_origin_revision,
    p.status_revision AS provider_status_revision,
    p.id AS provider_id,
    p.name AS provider_name,
    p.status AS provider_status,
    COALESCE(m.id, 0)::bigint AS model_db_id,
    (m.id IS NOT NULL)::boolean AS model_exists,
    COALESCE(m.status, '')::text AS model_status,
    COALESCE(cm.status, '')::text AS binding_status,
    (base.id IS NOT NULL)::boolean AS has_model_price,
    COALESCE((cost.id IS NOT NULL OR mult.id IS NOT NULL), false)::boolean AS has_channel_cost,
    COALESCE(base.id, 0)::bigint AS model_price_id,
    COALESCE(base.currency, '')::text AS base_currency,
    COALESCE(base.pricing_unit, '')::text AS base_pricing_unit,
    base.uncached_input_price,
    base.cache_read_input_price,
    base.cache_creation_5m_input_price,
    base.cache_creation_1h_input_price,
    base.cache_creation_30m_input_price,
    base.output_price,
    base.reasoning_output_price,
    COALESCE(cost.id, 0)::bigint AS channel_price_id,
    COALESCE(cost.currency, '')::text AS cost_currency,
    COALESCE(cost.pricing_unit, '')::text AS cost_pricing_unit,
    cost.uncached_input_cost,
    cost.cache_read_input_cost,
    cost.cache_creation_5m_input_cost,
    cost.cache_creation_1h_input_cost,
    cost.cache_creation_30m_input_cost,
    cost.output_cost,
    cost.reasoning_output_cost,
    COALESCE(mult.id, 0)::bigint AS channel_cost_multiplier_id,
    mult.multiplier AS cost_multiplier,
    COALESCE(recharge.id, 0)::bigint AS provider_recharge_rate_id,
    recharge.rate AS provider_recharge_rate
FROM channels c
JOIN providers p ON p.id = c.provider_id
LEFT JOIN models m
  ON NULLIF($1::text, '') IS NOT NULL
 AND m.model_id = $1::text
LEFT JOIN channel_models cm ON cm.channel_id = c.id AND cm.model_id = m.id
LEFT JOIN LATERAL (
    SELECT mp.id, mp.currency, mp.pricing_unit,
           mp.uncached_input_price, mp.cache_read_input_price,
           mp.cache_creation_5m_input_price, mp.cache_creation_1h_input_price,
           mp.cache_creation_30m_input_price, mp.output_price, mp.reasoning_output_price
    FROM model_prices mp
    WHERE mp.model_id = m.id
      AND mp.status = 'enabled'
      AND mp.effective_from <= $2
      AND (mp.effective_to IS NULL OR mp.effective_to > $2)
    ORDER BY mp.effective_from DESC, mp.id DESC
    LIMIT 1
) base ON TRUE
LEFT JOIN LATERAL (
    SELECT cp.id, cp.currency, cp.pricing_unit,
           cp.uncached_input_cost, cp.cache_read_input_cost,
           cp.cache_creation_5m_input_cost, cp.cache_creation_1h_input_cost,
           cp.cache_creation_30m_input_cost, cp.output_cost, cp.reasoning_output_cost
    FROM channel_prices cp
    WHERE cp.channel_id = c.id
      AND cp.model_id = m.id
      AND cp.status = 'enabled'
      AND cp.effective_from <= $2
      AND (cp.effective_to IS NULL OR cp.effective_to > $2)
    ORDER BY cp.effective_from DESC, cp.id DESC
    LIMIT 1
) cost ON TRUE
LEFT JOIN LATERAL (
    SELECT ccm.id, ccm.multiplier
    FROM channel_cost_multipliers ccm
    WHERE ccm.channel_id = c.id
      AND (ccm.model_id = m.id OR ccm.model_id IS NULL)
      AND ccm.status = 'enabled'
      AND ccm.effective_from <= $2
      AND (ccm.effective_to IS NULL OR ccm.effective_to > $2)
    ORDER BY (ccm.model_id IS NULL) ASC, ccm.effective_from DESC, ccm.id DESC
    LIMIT 1
) mult ON TRUE
LEFT JOIN LATERAL (
    SELECT prr.id, prr.rate
    FROM provider_recharge_rates prr
    WHERE prr.provider_id = p.id
      AND prr.status = 'enabled'
      AND prr.effective_from <= $2
      AND (prr.effective_to IS NULL OR prr.effective_to > $2)
    ORDER BY prr.effective_from DESC, prr.id DESC
    LIMIT 1
) recharge ON TRUE
WHERE c.status <> 'archived'
ORDER BY c.priority, c.id
`

type ModelRuntimePoolParams struct {
	ModelID string
	AtTime  pgtype.Timestamptz
}

type ModelRuntimePoolRow struct {
	ChannelID                  int64
	ChannelName                string
	ChannelStatus              string
	CredentialValid            bool
	HasCredential              bool
	SupplyForm                 string
	HasSchedulableAccount      bool
	HasOrigin                  bool
	Protocols                  []string
	AdapterKey                 string
	Priority                   int32
	ConcurrencyLimit           pgtype.Int4
	ChannelConfigRevision      int64
	ChannelCapacityRevision    int64
	Origin                     string
	ProviderOriginRevision     int64
	ProviderStatusRevision     int64
	ProviderID                 int64
	ProviderName               string
	ProviderStatus             string
	ModelDbID                  int64
	ModelExists                bool
	ModelStatus                string
	BindingStatus              string
	HasModelPrice              bool
	HasChannelCost             bool
	ModelPriceID               int64
	BaseCurrency               string
	BasePricingUnit            string
	UncachedInputPrice         pgtype.Numeric
	CacheReadInputPrice        pgtype.Numeric
	CacheCreation5mInputPrice  pgtype.Numeric
	CacheCreation1hInputPrice  pgtype.Numeric
	CacheCreation30mInputPrice pgtype.Numeric
	OutputPrice                pgtype.Numeric
	ReasoningOutputPrice       pgtype.Numeric
	ChannelPriceID             int64
	CostCurrency               string
	CostPricingUnit            string
	UncachedInputCost          pgtype.Numeric
	CacheReadInputCost         pgtype.Numeric
	CacheCreation5mInputCost   pgtype.Numeric
	CacheCreation1hInputCost   pgtype.Numeric
	CacheCreation30mInputCost  pgtype.Numeric
	OutputCost                 pgtype.Numeric
	ReasoningOutputCost        pgtype.Numeric
	ChannelCostMultiplierID    int64
	CostMultiplier             pgtype.Numeric
	ProviderRechargeRateID     int64
	ProviderRechargeRate       pgtype.Numeric
}

// ModelRuntimePool 返回全部未归档渠道及其数据库硬过滤事实，供选路诊断解释
// 「这条渠道为什么没进候选」。
//
// 它故意不做任何过滤：范围就是全部渠道。诊断的价值恰恰在于把被排除的渠道也列出来，
// 并给出被排除的具体原因（渠道停用 / 凭据无效 / 协议不匹配 / 未绑定该模型 / 缺价格等）。
// 过滤后的候选集由 FindModelCandidates 负责，两者互为对照。
func (q *Queries) ModelRuntimePool(ctx context.Context, arg ModelRuntimePoolParams) ([]ModelRuntimePoolRow, error) {
	rows, err := q.db.Query(ctx, modelRuntimePool, arg.ModelID, arg.AtTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRuntimePoolRow
	for rows.Next() {
		var i ModelRuntimePoolRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelStatus,
			&i.CredentialValid,
			&i.HasCredential,
			&i.SupplyForm,
			&i.HasSchedulableAccount,
			&i.HasOrigin,
			&i.Protocols,
			&i.AdapterKey,
			&i.Priority,
			&i.ConcurrencyLimit,
			&i.ChannelConfigRevision,
			&i.ChannelCapacityRevision,
			&i.Origin,
			&i.ProviderOriginRevision,
			&i.ProviderStatusRevision,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderStatus,
			&i.ModelDbID,
			&i.ModelExists,
			&i.ModelStatus,
			&i.BindingStatus,
			&i.HasModelPrice,
			&i.HasChannelCost,
			&i.ModelPriceID,
			&i.BaseCurrency,
			&i.BasePricingUnit,
			&i.UncachedInputPrice,
			&i.CacheReadInputPrice,
			&i.CacheCreation5mInputPrice,
			&i.CacheCreation1hInputPrice,
			&i.CacheCreation30mInputPrice,
			&i.OutputPrice,
			&i.ReasoningOutputPrice,
			&i.ChannelPriceID,
			&i.CostCurrency,
			&i.CostPricingUnit,
			&i.UncachedInputCost,
			&i.CacheReadInputCost,
			&i.CacheCreation5mInputCost,
			&i.CacheCreation1hInputCost,
			&i.CacheCreation30mInputCost,
			&i.OutputCost,
			&i.ReasoningOutputCost,
			&i.ChannelCostMultiplierID,
			&i.CostMultiplier,
			&i.ProviderRechargeRateID,
			&i.ProviderRechargeRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoutingDecisionTrace = `-- name: UpsertRoutingDecisionTrace :exec
INSERT INTO routing_decision_traces (
    request_record_id, mode, requested_model_id, protocol, endpoint,
    pool_size, algorithm_version,
    sticky_key_present, sticky_before_channel_id, sticky_before_version,
    sticky_before_account_id,
    sticky_action, sticky_reason, sticky_after_channel_id, sticky_after_version,
    trace_status, schema_version, eligible_count, baseline_order, actual_scan_order,
    attempted_channel_ids, selected_channel_id, fallback_count, final_result,
    capacity_wait_ms, capacity_wait_result, trace_payload,
    attempted_account_ids, selected_account_id
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7,
    $8, $9,
    $10, $11,
    $12, $13,
    $14, $15,
    $16, $17, $18,
    $19, $20, $21,
    $22, $23, $24,
    $25, $26, $27,
    $28, $29
)
ON CONFLICT (request_record_id) DO UPDATE SET
    pool_size = EXCLUDED.pool_size,
    sticky_key_present = EXCLUDED.sticky_key_present,
    sticky_before_channel_id = EXCLUDED.sticky_before_channel_id,
    sticky_before_version = EXCLUDED.sticky_before_version,
    sticky_before_account_id = EXCLUDED.sticky_before_account_id,
    sticky_action = EXCLUDED.sticky_action,
    sticky_reason = EXCLUDED.sticky_reason,
    sticky_after_channel_id = EXCLUDED.sticky_after_channel_id,
    sticky_after_version = EXCLUDED.sticky_after_version,
    -- complete 是终态：一旦收口就不再被 partial 覆盖回去。
    trace_status = CASE
        WHEN routing_decision_traces.trace_status = 'complete' THEN 'complete'
        ELSE EXCLUDED.trace_status
    END,
    schema_version = GREATEST(routing_decision_traces.schema_version, EXCLUDED.schema_version),
    eligible_count = EXCLUDED.eligible_count,
    baseline_order = EXCLUDED.baseline_order,
    actual_scan_order = EXCLUDED.actual_scan_order,
    attempted_channel_ids = EXCLUDED.attempted_channel_ids,
    attempted_account_ids = EXCLUDED.attempted_account_ids,
    selected_account_id = COALESCE(EXCLUDED.selected_account_id, routing_decision_traces.selected_account_id),
    selected_channel_id = COALESCE(EXCLUDED.selected_channel_id, routing_decision_traces.selected_channel_id),
    fallback_count = EXCLUDED.fallback_count,
    final_result = COALESCE(EXCLUDED.final_result, routing_decision_traces.final_result),
    capacity_wait_ms = COALESCE(EXCLUDED.capacity_wait_ms, routing_decision_traces.capacity_wait_ms),
    capacity_wait_result = COALESCE(EXCLUDED.capacity_wait_result, routing_decision_traces.capacity_wait_result),
    trace_payload = EXCLUDED.trace_payload,
    updated_at = now()
`

type UpsertRoutingDecisionTraceParams struct {
	RequestRecordID       int64
	Mode                  string
	RequestedModelID      string
	Protocol              string
	Endpoint              string
	PoolSize              int32
	AlgorithmVersion      string
	StickyKeyPresent      bool
	StickyBeforeChannelID pgtype.Int8
	StickyBeforeVersion   pgtype.Int8
	StickyBeforeAccountID pgtype.Int8
	StickyAction          pgtype.Text
	StickyReason          pgtype.Text
	StickyAfterChannelID  pgtype.Int8
	StickyAfterVersion    pgtype.Int8
	TraceStatus           string
	SchemaVersion         int32
	EligibleCount         int32
	BaselineOrder         []int64
	ActualScanOrder       []int64
	AttemptedChannelIds   []int64
	SelectedChannelID     pgtype.Int8
	FallbackCount         int32
	FinalResult           pgtype.Text
	CapacityWaitMs        pgtype.Int4
	CapacityWaitResult    pgtype.Text
	TracePayload          []byte
	AttemptedAccountIds   []int64
	SelectedAccountID     pgtype.Int8
}

// 每个进入路由规划的请求恰好一条 trace：规划开始写 partial，生命周期结束幂等升级为 complete（§13.1）。
// partial 不得覆盖已有的 complete：进程异常留下的 partial 是有意义的「尚未收口」，
// 但一条已经收口的 trace 不能被后续 partial 写回退。
func (q *Queries) UpsertRoutingDecisionTrace(ctx context.Context, arg UpsertRoutingDecisionTraceParams) error {
	_, err := q.db.Exec(ctx, upsertRoutingDecisionTrace,
		arg.RequestRecordID,
		arg.Mode,
		arg.RequestedModelID,
		arg.Protocol,
		arg.Endpoint,
		arg.PoolSize,
		arg.AlgorithmVersion,
		arg.StickyKeyPresent,
		arg.StickyBeforeChannelID,
		arg.StickyBeforeVersion,
		arg.StickyBeforeAccountID,
		arg.StickyAction,
		arg.StickyReason,
		arg.StickyAfterChannelID,
		arg.StickyAfterVersion,
		arg.TraceStatus,
		arg.SchemaVersion,
		arg.EligibleCount,
		arg.BaselineOrder,
		arg.ActualScanOrder,
		arg.AttemptedChannelIds,
		arg.SelectedChannelID,
		arg.FallbackCount,
		arg.FinalResult,
		arg.CapacityWaitMs,
		arg.CapacityWaitResult,
		arg.TracePayload,
		arg.AttemptedAccountIds,
		arg.SelectedAccountID,
	)
	return err
}
