// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminChannelAccountsLastFailure24h = `-- name: AdminChannelAccountsLastFailure24h :many
SELECT DISTINCT ON (r.final_account_id)
    r.final_account_id AS account_id,
    r.created_at AS failed_at,
    COALESCE(r.error_code, '') AS error_code
FROM request_records r
WHERE r.final_account_id IN (SELECT sa.id FROM subscription_accounts sa WHERE sa.channel_id = $1)
  AND r.status = 'failed'
  AND r.created_at > now() - interval '24 hours'
ORDER BY r.final_account_id, r.created_at DESC
`

type AdminChannelAccountsLastFailure24hRow struct {
	AccountID pgtype.Int8
	FailedAt  pgtype.Timestamptz
	ErrorCode string
}

// AdminChannelAccountsLastFailure24h 每账号近 24 小时最近一次失败（时间 + 错误码），tooltip 展示。
func (q *Queries) AdminChannelAccountsLastFailure24h(ctx context.Context, channelID int64) ([]AdminChannelAccountsLastFailure24hRow, error) {
	rows, err := q.db.Query(ctx, adminChannelAccountsLastFailure24h, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminChannelAccountsLastFailure24hRow
	for rows.Next() {
		var i AdminChannelAccountsLastFailure24hRow
		if err := rows.Scan(&i.AccountID, &i.FailedAt, &i.ErrorCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminChannelAccountsSale24h = `-- name: AdminChannelAccountsSale24h :many
SELECT
    r.final_account_id AS account_id,
    le.currency,
    COALESCE(sum(CASE
        WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
        WHEN le.entry_type IN ('refund', 'adjustment_credit') THEN -le.amount
        ELSE 0
    END), 0)::numeric AS sale_amount
FROM ledger_entries le
JOIN request_records r ON r.id = le.request_record_id
WHERE r.final_account_id IN (SELECT sa.id FROM subscription_accounts sa WHERE sa.channel_id = $1)
  AND le.created_at > now() - interval '24 hours'
GROUP BY r.final_account_id, le.currency
`

type AdminChannelAccountsSale24hRow struct {
	AccountID  pgtype.Int8
	Currency   string
	SaleAmount pgtype.Numeric
}

// AdminChannelAccountsSale24h 按账号 + 币种聚合近 24 小时净扣费（售卖额，与工作台 revenue 同口径 debit 族 − 冲正）。
func (q *Queries) AdminChannelAccountsSale24h(ctx context.Context, channelID int64) ([]AdminChannelAccountsSale24hRow, error) {
	rows, err := q.db.Query(ctx, adminChannelAccountsSale24h, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminChannelAccountsSale24hRow
	for rows.Next() {
		var i AdminChannelAccountsSale24hRow
		if err := rows.Scan(&i.AccountID, &i.Currency, &i.SaleAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminChannelAccountsUsage24h = `-- name: AdminChannelAccountsUsage24h :many
SELECT
    r.final_account_id AS account_id,
    count(*)::bigint AS total_requests,
    (count(*) FILTER (WHERE r.status = 'succeeded'))::bigint AS succeeded_requests,
    (count(*) FILTER (WHERE r.status = 'failed'))::bigint AS failed_requests,
    (count(*) FILTER (WHERE r.status = 'canceled'))::bigint AS canceled_requests,
    COALESCE(sum(
        ur.uncached_input_tokens + ur.cache_read_input_tokens
        + ur.cache_creation_5m_input_tokens + ur.cache_creation_1h_input_tokens
        + ur.cache_creation_30m_input_tokens + ur.output_tokens_total
    ), 0)::bigint AS total_tokens,
    COALESCE(avg(EXTRACT(EPOCH FROM (r.completed_at - r.started_at)) * 1000)
        FILTER (WHERE r.status = 'succeeded' AND r.completed_at IS NOT NULL AND r.started_at IS NOT NULL), 0)::bigint AS avg_latency_ms,
    COALESCE(avg(EXTRACT(EPOCH FROM (r.gateway_first_token_at - r.started_at)) * 1000)
        FILTER (WHERE r.status = 'succeeded' AND r.gateway_first_token_at IS NOT NULL AND r.started_at IS NOT NULL), 0)::bigint AS avg_first_token_ms
FROM request_records r
LEFT JOIN usage_records ur ON ur.request_record_id = r.id
WHERE r.final_account_id IN (SELECT sa.id FROM subscription_accounts sa WHERE sa.channel_id = $1)
  AND r.created_at > now() - interval '24 hours'
GROUP BY r.final_account_id
`

type AdminChannelAccountsUsage24hRow struct {
	AccountID         pgtype.Int8
	TotalRequests     int64
	SucceededRequests int64
	FailedRequests    int64
	CanceledRequests  int64
	TotalTokens       int64
	AvgLatencyMs      int64
	AvgFirstTokenMs   int64
}

// AdminChannelAccountsUsage24h 按账号聚合近 24 小时的请求/成功/失败/取消/token/延迟（渠道账号页「24H」列）。
// total_requests 包含已归属账号的全部终态记录（含 canceled）；running 尚未写入 final_account_id，不在此聚合。
// token 口径与请求详情一致：全部输入形态 + 输出总量；延迟只统计成功请求（失败的时长无意义）。
func (q *Queries) AdminChannelAccountsUsage24h(ctx context.Context, channelID int64) ([]AdminChannelAccountsUsage24hRow, error) {
	rows, err := q.db.Query(ctx, adminChannelAccountsUsage24h, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminChannelAccountsUsage24hRow
	for rows.Next() {
		var i AdminChannelAccountsUsage24hRow
		if err := rows.Scan(
			&i.AccountID,
			&i.TotalRequests,
			&i.SucceededRequests,
			&i.FailedRequests,
			&i.CanceledRequests,
			&i.TotalTokens,
			&i.AvgLatencyMs,
			&i.AvgFirstTokenMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCountAccountsByChannel = `-- name: AdminCountAccountsByChannel :one
SELECT
    count(*) AS total,
    count(*) FILTER (WHERE status = 'enabled') AS enabled,
    count(*) FILTER (WHERE status = 'disabled') AS disabled,
    count(*) FILTER (WHERE status = 'archived') AS archived,
    count(*) FILTER (WHERE status <> 'archived'
        AND subscription_expires_at IS NOT NULL
        AND subscription_expires_at < now() + interval '7 days') AS expiring_soon
FROM subscription_accounts
WHERE channel_id = $1
`

type AdminCountAccountsByChannelRow struct {
	Total        int64
	Enabled      int64
	Disabled     int64
	Archived     int64
	ExpiringSoon int64
}

// AdminCountAccountsByChannel 渠道账号聚合，供账号页签概览区与「池空 ≠ 熔断」的区分。
func (q *Queries) AdminCountAccountsByChannel(ctx context.Context, channelID int64) (AdminCountAccountsByChannelRow, error) {
	row := q.db.QueryRow(ctx, adminCountAccountsByChannel, channelID)
	var i AdminCountAccountsByChannelRow
	err := row.Scan(
		&i.Total,
		&i.Enabled,
		&i.Disabled,
		&i.Archived,
		&i.ExpiringSoon,
	)
	return i, err
}

const adminCreateSubscriptionAccount = `-- name: AdminCreateSubscriptionAccount :one
INSERT INTO subscription_accounts (
    channel_id, platform, credential_type, upstream_account_id, display_name,
    plan_type, credentials, proxy_url, proxy_id, concurrency_limit, priority,
    status, subscription_expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    'disabled', $12
)
RETURNING id, channel_id, platform, credential_type, upstream_account_id, display_name, plan_type, credentials, proxy_url, concurrency_limit, priority, status, disabled_reason, subscription_expires_at, usage_snapshot, last_success_at, config_revision, created_at, updated_at, proxy_id
`

type AdminCreateSubscriptionAccountParams struct {
	ChannelID             int64
	Platform              string
	CredentialType        string
	UpstreamAccountID     string
	DisplayName           string
	PlanType              pgtype.Text
	Credentials           []byte
	ProxyUrl              pgtype.Text
	ProxyID               pgtype.Int8
	ConcurrencyLimit      pgtype.Int4
	Priority              int32
	SubscriptionExpiresAt pgtype.Timestamptz
}

// AdminCreateSubscriptionAccount 落库新账号。导入一律落 disabled，由管理员显式启用。
// 重复导入由 (platform, upstream_account_id) 唯一键在数据库层拒绝，不依赖应用层先查后插。
func (q *Queries) AdminCreateSubscriptionAccount(ctx context.Context, arg AdminCreateSubscriptionAccountParams) (SubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, adminCreateSubscriptionAccount,
		arg.ChannelID,
		arg.Platform,
		arg.CredentialType,
		arg.UpstreamAccountID,
		arg.DisplayName,
		arg.PlanType,
		arg.Credentials,
		arg.ProxyUrl,
		arg.ProxyID,
		arg.ConcurrencyLimit,
		arg.Priority,
		arg.SubscriptionExpiresAt,
	)
	var i SubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.DisplayName,
		&i.PlanType,
		&i.Credentials,
		&i.ProxyUrl,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.Status,
		&i.DisabledReason,
		&i.SubscriptionExpiresAt,
		&i.UsageSnapshot,
		&i.LastSuccessAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const adminCreateSubscriptionLedgerEntry = `-- name: AdminCreateSubscriptionLedgerEntry :one
INSERT INTO subscription_ledger_entries (
    account_id, amount, currency, period_start, period_end, note, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, account_id, amount, currency, period_start, period_end, note, created_by, created_at, updated_at
`

type AdminCreateSubscriptionLedgerEntryParams struct {
	AccountID   int64
	Amount      pgtype.Numeric
	Currency    string
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	Note        pgtype.Text
	CreatedBy   pgtype.Text
}

// AdminCreateSubscriptionLedgerEntry 录入一期订阅费用（续费一次写一行）。
func (q *Queries) AdminCreateSubscriptionLedgerEntry(ctx context.Context, arg AdminCreateSubscriptionLedgerEntryParams) (SubscriptionLedgerEntry, error) {
	row := q.db.QueryRow(ctx, adminCreateSubscriptionLedgerEntry,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Note,
		arg.CreatedBy,
	)
	var i SubscriptionLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteSubscriptionAccountCascade = `-- name: AdminDeleteSubscriptionAccountCascade :execrows
WITH deleted_ledger AS (
    DELETE FROM subscription_ledger_entries
    WHERE subscription_ledger_entries.account_id = $1
)
DELETE FROM subscription_accounts WHERE subscription_accounts.id = $1
`

// AdminDeleteSubscriptionAccountCascade 物理删除账号，用于清理录错/试错的脏数据。
// 台账是账号自身的运营录入（非请求账务事实），随账号一并删除。
// 若账号已被请求历史引用（request_records.final_account_id NO ACTION 外键），
// 语句报 23503 整体回滚，上层降级为 conflict 提示保持归档——保住账务归因链路。
func (q *Queries) AdminDeleteSubscriptionAccountCascade(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteSubscriptionAccountCascade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetSubscriptionAccount = `-- name: AdminGetSubscriptionAccount :one
SELECT id, channel_id, platform, credential_type, upstream_account_id, display_name, plan_type, credentials, proxy_url, concurrency_limit, priority, status, disabled_reason, subscription_expires_at, usage_snapshot, last_success_at, config_revision, created_at, updated_at, proxy_id
FROM subscription_accounts
WHERE id = $1
`

// AdminGetSubscriptionAccount 取单个账号详情（含凭据，与渠道凭据同权：管理端可查看轮换）。
func (q *Queries) AdminGetSubscriptionAccount(ctx context.Context, id int64) (SubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, adminGetSubscriptionAccount, id)
	var i SubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.DisplayName,
		&i.PlanType,
		&i.Credentials,
		&i.ProxyUrl,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.Status,
		&i.DisabledReason,
		&i.SubscriptionExpiresAt,
		&i.UsageSnapshot,
		&i.LastSuccessAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const adminListPoolChannels = `-- name: AdminListPoolChannels :many
SELECT c.id, c.name, c.status, c.account_default_concurrency,
       p.id AS provider_id, p.name AS provider_name
FROM channels c
JOIN providers p ON p.id = c.provider_id
WHERE c.supply_form = 'pool'
  AND c.status <> 'archived'
ORDER BY c.priority, c.id
`

type AdminListPoolChannelsRow struct {
	ID                        int64
	Name                      string
	Status                    string
	AccountDefaultConcurrency pgtype.Int4
	ProviderID                int64
	ProviderName              string
}

// AdminListPoolChannels 列出全部未归档池型渠道（号池并发监测的钻取骨架：Provider → 池 → 账号）。
func (q *Queries) AdminListPoolChannels(ctx context.Context) ([]AdminListPoolChannelsRow, error) {
	rows, err := q.db.Query(ctx, adminListPoolChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListPoolChannelsRow
	for rows.Next() {
		var i AdminListPoolChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AccountDefaultConcurrency,
			&i.ProviderID,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSubscriptionAccounts = `-- name: AdminListSubscriptionAccounts :many
SELECT
    a.id,
    a.channel_id,
    a.platform,
    a.credential_type,
    a.upstream_account_id,
    a.display_name,
    a.plan_type,
    a.proxy_url,
    a.concurrency_limit,
    a.priority,
    a.status,
    a.disabled_reason,
    a.subscription_expires_at,
    a.usage_snapshot,
    a.last_success_at,
    a.config_revision,
    a.created_at,
    a.updated_at,
    (a.credentials ->> 'expires_at') AS token_expires_at,
    (a.credentials ? 'refresh_token') AS has_refresh_token,
    (a.credentials ->> 'email') AS email,
    a.proxy_id,
    apx.name AS proxy_name,
    apx.status AS proxy_status
FROM subscription_accounts a
LEFT JOIN proxies apx ON apx.id = a.proxy_id
WHERE a.channel_id = $1
  AND ($2::text IS NULL OR a.status = $2::text)
ORDER BY CASE a.status WHEN 'enabled' THEN 0 WHEN 'disabled' THEN 1 ELSE 2 END, a.priority, a.id
`

type AdminListSubscriptionAccountsParams struct {
	ChannelID int64
	Status    pgtype.Text
}

type AdminListSubscriptionAccountsRow struct {
	ID                    int64
	ChannelID             int64
	Platform              string
	CredentialType        string
	UpstreamAccountID     string
	DisplayName           string
	PlanType              pgtype.Text
	ProxyUrl              pgtype.Text
	ConcurrencyLimit      pgtype.Int4
	Priority              int32
	Status                string
	DisabledReason        pgtype.Text
	SubscriptionExpiresAt pgtype.Timestamptz
	UsageSnapshot         []byte
	LastSuccessAt         pgtype.Timestamptz
	ConfigRevision        int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	TokenExpiresAt        interface{}
	HasRefreshToken       interface{}
	Email                 interface{}
	ProxyID               pgtype.Int8
	ProxyName             pgtype.Text
	ProxyStatus           pgtype.Text
}

// AdminListSubscriptionAccounts 列出渠道下全部账号（含已停用与归档），供渠道详情的账号页签。
// 返回凭据摘要而非凭据本身：列表页不需要令牌明文，减少泄露面。
// 运维视角排序：在役（enabled）最前，其次停用，归档垫底；同层按优先级与 ID 稳定排序。
// 不能直接 ORDER BY status——那是字母序，archived 会排最前。
func (q *Queries) AdminListSubscriptionAccounts(ctx context.Context, arg AdminListSubscriptionAccountsParams) ([]AdminListSubscriptionAccountsRow, error) {
	rows, err := q.db.Query(ctx, adminListSubscriptionAccounts, arg.ChannelID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListSubscriptionAccountsRow
	for rows.Next() {
		var i AdminListSubscriptionAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Platform,
			&i.CredentialType,
			&i.UpstreamAccountID,
			&i.DisplayName,
			&i.PlanType,
			&i.ProxyUrl,
			&i.ConcurrencyLimit,
			&i.Priority,
			&i.Status,
			&i.DisabledReason,
			&i.SubscriptionExpiresAt,
			&i.UsageSnapshot,
			&i.LastSuccessAt,
			&i.ConfigRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenExpiresAt,
			&i.HasRefreshToken,
			&i.Email,
			&i.ProxyID,
			&i.ProxyName,
			&i.ProxyStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSubscriptionLedger = `-- name: AdminListSubscriptionLedger :many
SELECT id, account_id, amount, currency, period_start, period_end, note, created_by, created_at, updated_at
FROM subscription_ledger_entries
WHERE account_id = $1
ORDER BY period_start DESC, id DESC
`

// AdminListSubscriptionLedger 列出账号的订阅费用台账，供摊销与利用率的离线计算与页面展示。
func (q *Queries) AdminListSubscriptionLedger(ctx context.Context, accountID int64) ([]SubscriptionLedgerEntry, error) {
	rows, err := q.db.Query(ctx, adminListSubscriptionLedger, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionLedgerEntry
	for rows.Next() {
		var i SubscriptionLedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPickProbeAccount = `-- name: AdminPickProbeAccount :one
SELECT id
FROM subscription_accounts
WHERE channel_id = $1
  AND status = 'enabled'
ORDER BY priority, id
LIMIT 1
`

// AdminPickProbeAccount 为渠道检测选一个账号：未指定账号时取「调度视角最优先」的在役账号
// （priority 小者优先，同档按 ID 稳定），保证检测走的号与真实调度大概率一致。
func (q *Queries) AdminPickProbeAccount(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, adminPickProbeAccount, channelID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const adminReauthorizeSubscriptionAccount = `-- name: AdminReauthorizeSubscriptionAccount :one
UPDATE subscription_accounts
SET credentials = $3,
    plan_type = COALESCE($4, plan_type),
    subscription_expires_at = COALESCE($5, subscription_expires_at),
    updated_at = now()
WHERE platform = $1
  AND upstream_account_id = $2
RETURNING id, channel_id, platform, credential_type, upstream_account_id, display_name, plan_type, credentials, proxy_url, concurrency_limit, priority, status, disabled_reason, subscription_expires_at, usage_snapshot, last_success_at, config_revision, created_at, updated_at, proxy_id
`

type AdminReauthorizeSubscriptionAccountParams struct {
	Platform              string
	UpstreamAccountID     string
	Credentials           []byte
	PlanType              pgtype.Text
	SubscriptionExpiresAt pgtype.Timestamptz
}

// AdminReauthorizeSubscriptionAccount 用重新授权得到的新凭据覆盖既有账号（边界 21：续命是高频场景，
// 不应走删除重建）。按 (platform, upstream_account_id) 定位，保留其调度参数与台账关联。
func (q *Queries) AdminReauthorizeSubscriptionAccount(ctx context.Context, arg AdminReauthorizeSubscriptionAccountParams) (SubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, adminReauthorizeSubscriptionAccount,
		arg.Platform,
		arg.UpstreamAccountID,
		arg.Credentials,
		arg.PlanType,
		arg.SubscriptionExpiresAt,
	)
	var i SubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.DisplayName,
		&i.PlanType,
		&i.Credentials,
		&i.ProxyUrl,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.Status,
		&i.DisabledReason,
		&i.SubscriptionExpiresAt,
		&i.UsageSnapshot,
		&i.LastSuccessAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const adminSetSubscriptionAccountStatus = `-- name: AdminSetSubscriptionAccountStatus :one
UPDATE subscription_accounts
SET status = $2,
    disabled_reason = $3,
    config_revision = config_revision + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, channel_id, platform, credential_type, upstream_account_id, display_name, plan_type, credentials, proxy_url, concurrency_limit, priority, status, disabled_reason, subscription_expires_at, usage_snapshot, last_success_at, config_revision, created_at, updated_at, proxy_id
`

type AdminSetSubscriptionAccountStatusParams struct {
	ID             int64
	Status         string
	DisabledReason pgtype.Text
}

// AdminSetSubscriptionAccountStatus 启停或归档账号。状态影响可调度性，提升 config_revision。
// 归档不可逆到 enabled：恢复统一落 disabled，由调用方分两步执行（与 Provider/Channel 恢复一致）。
func (q *Queries) AdminSetSubscriptionAccountStatus(ctx context.Context, arg AdminSetSubscriptionAccountStatusParams) (SubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, adminSetSubscriptionAccountStatus, arg.ID, arg.Status, arg.DisabledReason)
	var i SubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.DisplayName,
		&i.PlanType,
		&i.Credentials,
		&i.ProxyUrl,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.Status,
		&i.DisabledReason,
		&i.SubscriptionExpiresAt,
		&i.UsageSnapshot,
		&i.LastSuccessAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const adminUpdateSubscriptionAccountConfig = `-- name: AdminUpdateSubscriptionAccountConfig :one
UPDATE subscription_accounts
SET display_name = $2,
    proxy_url = $3,
    proxy_id = $4,
    concurrency_limit = $5,
    priority = $6,
    subscription_expires_at = $7,
    config_revision = config_revision + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, channel_id, platform, credential_type, upstream_account_id, display_name, plan_type, credentials, proxy_url, concurrency_limit, priority, status, disabled_reason, subscription_expires_at, usage_snapshot, last_success_at, config_revision, created_at, updated_at, proxy_id
`

type AdminUpdateSubscriptionAccountConfigParams struct {
	ID                    int64
	DisplayName           string
	ProxyUrl              pgtype.Text
	ProxyID               pgtype.Int8
	ConcurrencyLimit      pgtype.Int4
	Priority              int32
	SubscriptionExpiresAt pgtype.Timestamptz
}

// AdminUpdateSubscriptionAccountConfig 修改调度参数（并发、优先级、代理、备注名）与订阅到期时间。
// 调度参数改变调度行为，故提升 config_revision；调用方须在同事务提升渠道 capacity_revision，
// 让运行态围栏立即感知（配置热更新传播）。subscription_expires_at 是运营录入的到期预警事实：
// 上游不提供机读到期时间，唯一写入路径就是这里（缺省 NULL 表示清除/未知）。
func (q *Queries) AdminUpdateSubscriptionAccountConfig(ctx context.Context, arg AdminUpdateSubscriptionAccountConfigParams) (SubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, adminUpdateSubscriptionAccountConfig,
		arg.ID,
		arg.DisplayName,
		arg.ProxyUrl,
		arg.ProxyID,
		arg.ConcurrencyLimit,
		arg.Priority,
		arg.SubscriptionExpiresAt,
	)
	var i SubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.DisplayName,
		&i.PlanType,
		&i.Credentials,
		&i.ProxyUrl,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.Status,
		&i.DisabledReason,
		&i.SubscriptionExpiresAt,
		&i.UsageSnapshot,
		&i.LastSuccessAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
	)
	return i, err
}

const countSchedulableAccountsByChannel = `-- name: CountSchedulableAccountsByChannel :one
SELECT count(*)
FROM subscription_accounts
WHERE channel_id = $1
  AND status = 'enabled'
`

// CountSchedulableAccountsByChannel 统计渠道下可调度账号数，用于「零账号池不成为候选」与
// 「池空 ≠ 熔断」的区分展示。
func (q *Queries) CountSchedulableAccountsByChannel(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSchedulableAccountsByChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountByPlatformUpstreamID = `-- name: GetAccountByPlatformUpstreamID :one
SELECT a.id, a.channel_id, a.display_name, a.status, c.name AS channel_name
FROM subscription_accounts a
JOIN channels c ON c.id = a.channel_id
WHERE a.platform = $1
  AND a.upstream_account_id = $2
`

type GetAccountByPlatformUpstreamIDParams struct {
	Platform          string
	UpstreamAccountID string
}

type GetAccountByPlatformUpstreamIDRow struct {
	ID          int64
	ChannelID   int64
	DisplayName string
	Status      string
	ChannelName string
}

// GetAccountByPlatformUpstreamID 按全局唯一键定位账号，供重复导入提示「已存在于哪个池」。
func (q *Queries) GetAccountByPlatformUpstreamID(ctx context.Context, arg GetAccountByPlatformUpstreamIDParams) (GetAccountByPlatformUpstreamIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByPlatformUpstreamID, arg.Platform, arg.UpstreamAccountID)
	var i GetAccountByPlatformUpstreamIDRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DisplayName,
		&i.Status,
		&i.ChannelName,
	)
	return i, err
}

const getAccountOutboundCredential = `-- name: GetAccountOutboundCredential :one
SELECT
    a.id,
    a.channel_id,
    a.platform,
    a.credential_type,
    a.upstream_account_id,
    a.credentials,
    a.proxy_url,
    a.status,
    apx.url AS proxy_entity_url
FROM subscription_accounts a
LEFT JOIN proxies apx ON apx.id = a.proxy_id AND apx.status = 'enabled'
WHERE a.id = $1
`

type GetAccountOutboundCredentialRow struct {
	ID                int64
	ChannelID         int64
	Platform          string
	CredentialType    string
	UpstreamAccountID string
	Credentials       []byte
	ProxyUrl          pgtype.Text
	Status            string
	ProxyEntityUrl    pgtype.Text
}

// GetAccountOutboundCredential 取指定账号的出站凭据与代理，供 transport 按 permit 固化的账号身份发请求。
// 与 ListSchedulableAccountsByChannel 分开，避免把凭据带进每请求的候选快照。
func (q *Queries) GetAccountOutboundCredential(ctx context.Context, id int64) (GetAccountOutboundCredentialRow, error) {
	row := q.db.QueryRow(ctx, getAccountOutboundCredential, id)
	var i GetAccountOutboundCredentialRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.Credentials,
		&i.ProxyUrl,
		&i.Status,
		&i.ProxyEntityUrl,
	)
	return i, err
}

const getEnabledProxyURL = `-- name: GetEnabledProxyURL :one
SELECT url FROM proxies WHERE id = $1 AND status = 'enabled'
`

// GetEnabledProxyURL 取启用代理的规范 URL（disabled/不存在返回 no rows → 调用方按直连处理）。
func (q *Queries) GetEnabledProxyURL(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getEnabledProxyURL, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const listAccountsNeedingTokenRefresh = `-- name: ListAccountsNeedingTokenRefresh :many
SELECT a.id, a.channel_id, a.credentials, a.proxy_url, a.status,
       apx.url AS proxy_entity_url
FROM subscription_accounts a
LEFT JOIN proxies apx ON apx.id = a.proxy_id AND apx.status = 'enabled'
WHERE a.status <> 'archived'
  AND a.credential_type = 'oauth'
  AND a.credentials ? 'refresh_token'
  AND (a.credentials ->> 'expires_at') IS NOT NULL
  AND (a.credentials ->> 'expires_at')::timestamptz < now() + make_interval(secs => $1::bigint)
ORDER BY (a.credentials ->> 'expires_at')::timestamptz
LIMIT $2
`

type ListAccountsNeedingTokenRefreshParams struct {
	WithinSeconds int64
	PageLimit     int32
}

type ListAccountsNeedingTokenRefreshRow struct {
	ID             int64
	ChannelID      int64
	Credentials    []byte
	ProxyUrl       pgtype.Text
	Status         string
	ProxyEntityUrl pgtype.Text
}

// ListAccountsNeedingTokenRefresh 分页扫描 access token 即将过期的账号，供后台保活刷新（第六节）。
// 只扫未归档的 oauth 账号；disabled 也刷——运维随时可能启用，启用瞬间就要有新鲜令牌可用。
// expires_at 缺失（异常凭据）不进扫描：刷不刷都没意义，等请求时兜底路径报错暴露。
func (q *Queries) ListAccountsNeedingTokenRefresh(ctx context.Context, arg ListAccountsNeedingTokenRefreshParams) ([]ListAccountsNeedingTokenRefreshRow, error) {
	rows, err := q.db.Query(ctx, listAccountsNeedingTokenRefresh, arg.WithinSeconds, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsNeedingTokenRefreshRow
	for rows.Next() {
		var i ListAccountsNeedingTokenRefreshRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Credentials,
			&i.ProxyUrl,
			&i.Status,
			&i.ProxyEntityUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulableAccountsByChannel = `-- name: ListSchedulableAccountsByChannel :many
SELECT
    a.id,
    a.priority,
    a.concurrency_limit,
    a.usage_snapshot,
    a.last_success_at,
    a.config_revision,
    c.account_default_concurrency
FROM subscription_accounts a
JOIN channels c ON c.id = a.channel_id
WHERE a.channel_id = $1
  AND a.status = 'enabled'
ORDER BY a.priority, a.id
`

type ListSchedulableAccountsByChannelRow struct {
	ID                        int64
	Priority                  int32
	ConcurrencyLimit          pgtype.Int4
	UsageSnapshot             []byte
	LastSuccessAt             pgtype.Timestamptz
	ConfigRevision            int64
	AccountDefaultConcurrency pgtype.Int4
}

// ListSchedulableAccountsByChannel 取某个池型渠道下可调度的账号，供每请求的候选快照聚合并发容量与资格。
// 这是热路径：只取调度必需列，凭据不在其中（真正出站时再按 permit 固化的账号 ID 单取）。
// 「可调度」在这里只判账号自身 enabled；渠道与服务商状态由候选查询的上层条件保证（绑定式语义）。
func (q *Queries) ListSchedulableAccountsByChannel(ctx context.Context, channelID int64) ([]ListSchedulableAccountsByChannelRow, error) {
	rows, err := q.db.Query(ctx, listSchedulableAccountsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulableAccountsByChannelRow
	for rows.Next() {
		var i ListSchedulableAccountsByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.ConcurrencyLimit,
			&i.UsageSnapshot,
			&i.LastSuccessAt,
			&i.ConfigRevision,
			&i.AccountDefaultConcurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountDisabled = `-- name: MarkAccountDisabled :exec
UPDATE subscription_accounts
SET status = 'disabled',
    disabled_reason = $2,
    config_revision = config_revision + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'enabled'
`

type MarkAccountDisabledParams struct {
	ID             int64
	DisabledReason pgtype.Text
}

// MarkAccountDisabled 在确认令牌吊销或上游风控封禁时永久停用账号（临时不可调度走 Redis 运行态，不落库）。
// 停用改变可调度性，故提升 config_revision，由调用方在同事务提升渠道 capacity_revision。
func (q *Queries) MarkAccountDisabled(ctx context.Context, arg MarkAccountDisabledParams) error {
	_, err := q.db.Exec(ctx, markAccountDisabled, arg.ID, arg.DisabledReason)
	return err
}

const touchAccountLastSuccess = `-- name: TouchAccountLastSuccess :exec
UPDATE subscription_accounts
SET last_success_at = $2,
    updated_at = now()
WHERE id = $1
`

type TouchAccountLastSuccessParams struct {
	ID            int64
	LastSuccessAt pgtype.Timestamptz
}

// TouchAccountLastSuccess 记录最近一次完整成功时间，供池内选号的 LRU 排序使用。
func (q *Queries) TouchAccountLastSuccess(ctx context.Context, arg TouchAccountLastSuccessParams) error {
	_, err := q.db.Exec(ctx, touchAccountLastSuccess, arg.ID, arg.LastSuccessAt)
	return err
}

const updateAccountTokens = `-- name: UpdateAccountTokens :exec
UPDATE subscription_accounts
SET credentials = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateAccountTokensParams struct {
	ID          int64
	Credentials []byte
}

// UpdateAccountTokens 写回刷新后的凭据文档。调用方负责「新 refresh token 非空才覆盖」的合并逻辑，
// 本语句只做整体替换；不动 config_revision——凭据轮换不改变调度参数，无需惊动运行态围栏。
func (q *Queries) UpdateAccountTokens(ctx context.Context, arg UpdateAccountTokensParams) error {
	_, err := q.db.Exec(ctx, updateAccountTokens, arg.ID, arg.Credentials)
	return err
}

const updateAccountUsageSnapshot = `-- name: UpdateAccountUsageSnapshot :exec
UPDATE subscription_accounts
SET usage_snapshot = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateAccountUsageSnapshotParams struct {
	ID            int64
	UsageSnapshot []byte
}

// UpdateAccountUsageSnapshot 写入上游返回的用量窗口快照（primary=5h、secondary=7d，任一可缺失）。
// 观测写入不改 config_revision，失败也不应影响交付。
func (q *Queries) UpdateAccountUsageSnapshot(ctx context.Context, arg UpdateAccountUsageSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateAccountUsageSnapshot, arg.ID, arg.UsageSnapshot)
	return err
}
