// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_account_quota.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAutoResetCreditAccounts = `-- name: ListAutoResetCreditAccounts :many
SELECT
    a.id,
    a.display_name,
    a.usage_snapshot,
    a.reset_credits_snapshot,
    a.auto_reset_credit_mode,
    a.auto_reset_credit_5h_threshold_percent,
    a.auto_reset_credit_7d_threshold_percent,
    a.auto_reset_credit_state
FROM subscription_accounts a
JOIN channels c ON c.id = a.channel_id
WHERE a.status = 'enabled'
  AND a.auto_reset_credit_enabled = true
  AND c.supply_form = 'pool'
ORDER BY a.id
LIMIT $1
`

type ListAutoResetCreditAccountsRow struct {
	ID                                int64
	DisplayName                       string
	UsageSnapshot                     []byte
	ResetCreditsSnapshot              []byte
	AutoResetCreditMode               string
	AutoResetCredit5hThresholdPercent pgtype.Int4
	AutoResetCredit7dThresholdPercent pgtype.Int4
	AutoResetCreditState              []byte
}

// ListAutoResetCreditAccounts 列出开启了自动用卡、启用中且属于池型渠道的账号，供 worker 周期评估。
// 带最近用量快照与重置卡快照/运行态，评估先看本地快照，只有触顶或快照陈旧才打上游。
func (q *Queries) ListAutoResetCreditAccounts(ctx context.Context, limit int32) ([]ListAutoResetCreditAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAutoResetCreditAccounts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutoResetCreditAccountsRow
	for rows.Next() {
		var i ListAutoResetCreditAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.UsageSnapshot,
			&i.ResetCreditsSnapshot,
			&i.AutoResetCreditMode,
			&i.AutoResetCredit5hThresholdPercent,
			&i.AutoResetCredit7dThresholdPercent,
			&i.AutoResetCreditState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountAutoResetCreditConfig = `-- name: UpdateAccountAutoResetCreditConfig :one
UPDATE subscription_accounts
SET auto_reset_credit_enabled = $2,
    auto_reset_credit_mode = $3,
    auto_reset_credit_5h_threshold_percent = $4,
    auto_reset_credit_7d_threshold_percent = $5,
    config_revision = config_revision + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, channel_id, platform, credential_type, upstream_account_id, display_name, plan_type, credentials, proxy_url, concurrency_limit, priority, status, disabled_reason, subscription_expires_at, usage_snapshot, last_success_at, config_revision, created_at, updated_at, proxy_id, fingerprint_mode, fingerprint_seed, response_timeout_ms, first_token_timeout_ms, usage_pause_threshold_percent, reset_credits_snapshot, auto_reset_credit_enabled, auto_reset_credit_mode, auto_reset_credit_5h_threshold_percent, auto_reset_credit_7d_threshold_percent, auto_reset_credit_state, account_profile
`

type UpdateAccountAutoResetCreditConfigParams struct {
	ID                     int64
	AutoResetCreditEnabled bool
	AutoResetCreditMode    string
	Threshold5hPercent     pgtype.Int4
	Threshold7dPercent     pgtype.Int4
}

// UpdateAccountAutoResetCreditConfig 修改账号的自动用卡开关、触发方式（any/all）与 5h/7d 触发阈值
// （NULL = 该窗口不参与触发）。是运营策略而非调度围栏参数：普通列更新，bump config_revision 只为审计定位。
func (q *Queries) UpdateAccountAutoResetCreditConfig(ctx context.Context, arg UpdateAccountAutoResetCreditConfigParams) (SubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountAutoResetCreditConfig,
		arg.ID,
		arg.AutoResetCreditEnabled,
		arg.AutoResetCreditMode,
		arg.Threshold5hPercent,
		arg.Threshold7dPercent,
	)
	var i SubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Platform,
		&i.CredentialType,
		&i.UpstreamAccountID,
		&i.DisplayName,
		&i.PlanType,
		&i.Credentials,
		&i.ProxyUrl,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.Status,
		&i.DisabledReason,
		&i.SubscriptionExpiresAt,
		&i.UsageSnapshot,
		&i.LastSuccessAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyID,
		&i.FingerprintMode,
		&i.FingerprintSeed,
		&i.ResponseTimeoutMs,
		&i.FirstTokenTimeoutMs,
		&i.UsagePauseThresholdPercent,
		&i.ResetCreditsSnapshot,
		&i.AutoResetCreditEnabled,
		&i.AutoResetCreditMode,
		&i.AutoResetCredit5hThresholdPercent,
		&i.AutoResetCredit7dThresholdPercent,
		&i.AutoResetCreditState,
		&i.AccountProfile,
	)
	return i, err
}

const updateAccountAutoResetCreditState = `-- name: UpdateAccountAutoResetCreditState :exec
UPDATE subscription_accounts
SET auto_reset_credit_state = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateAccountAutoResetCreditStateParams struct {
	ID                   int64
	AutoResetCreditState []byte
}

// UpdateAccountAutoResetCreditState 写入自动用卡的脱敏运行态（状态机 + 尝试指纹）。
func (q *Queries) UpdateAccountAutoResetCreditState(ctx context.Context, arg UpdateAccountAutoResetCreditStateParams) error {
	_, err := q.db.Exec(ctx, updateAccountAutoResetCreditState, arg.ID, arg.AutoResetCreditState)
	return err
}

const updateAccountProfileSnapshot = `-- name: UpdateAccountProfileSnapshot :exec
UPDATE subscription_accounts
SET account_profile = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateAccountProfileSnapshotParams struct {
	ID             int64
	AccountProfile []byte
}

// UpdateAccountProfileSnapshot 写入「刷新状态」拿到的上游账号画像（accounts/check + me），展示缓存。
func (q *Queries) UpdateAccountProfileSnapshot(ctx context.Context, arg UpdateAccountProfileSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateAccountProfileSnapshot, arg.ID, arg.AccountProfile)
	return err
}

const updateAccountResetCreditsSnapshot = `-- name: UpdateAccountResetCreditsSnapshot :exec

UPDATE subscription_accounts
SET reset_credits_snapshot = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateAccountResetCreditsSnapshotParams struct {
	ID                   int64
	ResetCreditsSnapshot []byte
}

// 号池账号的 Codex 用量主动查询与重置卡（admin 手动 / worker 自动共用）。
// 用量窗口快照本身仍走 UpdateAccountUsageSnapshot（与请求路径观测同一列）；这里只管重置卡快照、
// 自动用卡配置与运行态。三者都是观测/运行态列，不改 config_revision。
// UpdateAccountResetCreditsSnapshot 写入最近一次主动查用量得到的重置卡快照（只存到期时刻，不存卡 id）。
func (q *Queries) UpdateAccountResetCreditsSnapshot(ctx context.Context, arg UpdateAccountResetCreditsSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateAccountResetCreditsSnapshot, arg.ID, arg.ResetCreditsSnapshot)
	return err
}

const updateAccountSubscriptionFacts = `-- name: UpdateAccountSubscriptionFacts :exec
UPDATE subscription_accounts
SET plan_type = COALESCE($2, plan_type),
    subscription_expires_at = COALESCE($3, subscription_expires_at),
    updated_at = now()
WHERE id = $1
`

type UpdateAccountSubscriptionFactsParams struct {
	ID                    int64
	PlanType              pgtype.Text
	SubscriptionExpiresAt pgtype.Timestamptz
}

// UpdateAccountSubscriptionFacts 用上游权威值回写套餐与订阅到期（accounts/check 的 entitlement）。
// 任一参数为 NULL 表示该项上游没给，保留现值；到期日原本靠运营手工录入，这里让它随刷新自动更正。
func (q *Queries) UpdateAccountSubscriptionFacts(ctx context.Context, arg UpdateAccountSubscriptionFactsParams) error {
	_, err := q.db.Exec(ctx, updateAccountSubscriptionFacts, arg.ID, arg.PlanType, arg.SubscriptionExpiresAt)
	return err
}
