// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supply.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnabledBindingsByChannel = `-- name: CountEnabledBindingsByChannel :one
SELECT COUNT(*) AS enabled_bindings
FROM channel_models
WHERE channel_id = $1 AND status = 'enabled'
`

// CountEnabledBindingsByChannel 归档前置：archived Channel 下不得存在 enabled Binding。
func (q *Queries) CountEnabledBindingsByChannel(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledBindingsByChannel, channelID)
	var enabled_bindings int64
	err := row.Scan(&enabled_bindings)
	return enabled_bindings, err
}

const countOtherEnabledBindingsForModel = `-- name: CountOtherEnabledBindingsForModel :one
SELECT COUNT(*) AS remaining
FROM channel_models cm
WHERE cm.model_id = $1
  AND cm.status = 'enabled'
  AND cm.channel_id <> $2
`

type CountOtherEnabledBindingsForModelParams struct {
	ModelID          int64
	ExcludeChannelID int64
}

// CountOtherEnabledBindingsForModel 全局判断：排除目标 Channel 后，该 Model 是否仍有任意
// enabled Binding。只读 Binding 行状态，不读 Channel/Provider 实体状态。
func (q *Queries) CountOtherEnabledBindingsForModel(ctx context.Context, arg CountOtherEnabledBindingsForModelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherEnabledBindingsForModel, arg.ModelID, arg.ExcludeChannelID)
	var remaining int64
	err := row.Scan(&remaining)
	return remaining, err
}

const disableModelSupply = `-- name: DisableModelSupply :execrows
UPDATE models
SET status = 'disabled',
    disabled_reason = $1,
    disabled_at = now(),
    updated_at = now()
WHERE id = $2 AND status = 'enabled'
`

type DisableModelSupplyParams struct {
	Reason pgtype.Text
	ID     int64
}

// DisableModelSupply 暂停 Model 行并记录直接原因；供给失去最后支撑时由调用方连带执行。
func (q *Queries) DisableModelSupply(ctx context.Context, arg DisableModelSupplyParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableModelSupply, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableModelSupply = `-- name: EnableModelSupply :execrows
UPDATE models
SET status = 'enabled',
    disabled_reason = NULL,
    disabled_at = NULL,
    updated_at = now()
WHERE id = $1 AND status = 'disabled'
`

// EnableModelSupply 启用 Model 行并清空停用原因。调用方必须先在同一事务、同一 Model 锁内
// 确认 ModelHasRuntimeSupply 为真，否则会破坏「enabled 即可调用」的不变量。
func (q *Queries) EnableModelSupply(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, enableModelSupply, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDisabledModelsRecoverable = `-- name: ListDisabledModelsRecoverable :many
SELECT m.id AS model_id,
       m.model_id AS public_model_id,
       m.display_name,
       m.disabled_reason,
       m.disabled_at
FROM models m
WHERE m.status = 'disabled'
  AND m.disabled_reason IN ('binding_disabled', 'channel_disabled')
  AND EXISTS (
      SELECT 1
      FROM channel_models cm
      JOIN channels c ON c.id = cm.channel_id
      JOIN providers p ON p.id = c.provider_id
      WHERE cm.model_id = m.id
        AND cm.status = 'enabled'
        AND c.status = 'enabled'
        AND c.credential_valid
        AND p.status = 'enabled'
  )
ORDER BY m.model_id
`

type ListDisabledModelsRecoverableRow struct {
	ModelID        int64
	PublicModelID  string
	DisplayName    string
	DisabledReason pgtype.Text
	DisabledAt     pgtype.Timestamptz
}

// ListDisabledModelsRecoverable 列出因供给中断而停用、如今供给已恢复的模型（批量恢复入口）。
// 只列 binding_disabled / channel_disabled：管理员手动下架的不该被「恢复」列表打扰。
func (q *Queries) ListDisabledModelsRecoverable(ctx context.Context) ([]ListDisabledModelsRecoverableRow, error) {
	rows, err := q.db.Query(ctx, listDisabledModelsRecoverable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisabledModelsRecoverableRow
	for rows.Next() {
		var i ListDisabledModelsRecoverableRow
		if err := rows.Scan(
			&i.ModelID,
			&i.PublicModelID,
			&i.DisplayName,
			&i.DisabledReason,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledBindingModelIDsForChannel = `-- name: ListEnabledBindingModelIDsForChannel :many
SELECT DISTINCT cm.model_id
FROM channel_models cm
WHERE cm.channel_id = $1 AND cm.status = 'enabled'
ORDER BY cm.model_id
`

// ListEnabledBindingModelIDsForChannel 列出某 Channel 全部 enabled Binding 的模型（升序），
// 供 Channel 停用/归档前聚合锁定与影响计算。
func (q *Queries) ListEnabledBindingModelIDsForChannel(ctx context.Context, channelID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listEnabledBindingModelIDsForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var model_id int64
		if err := rows.Scan(&model_id); err != nil {
			return nil, err
		}
		items = append(items, model_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelRuntimeProtocols = `-- name: ListModelRuntimeProtocols :many
SELECT DISTINCT proto AS ingress_protocol
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
JOIN providers p ON p.id = c.provider_id
CROSS JOIN LATERAL unnest(c.protocols) AS proto
WHERE cm.model_id = $1
  AND cm.status = 'enabled'
  AND c.status = 'enabled'
  AND c.credential_valid
  AND p.status = 'enabled'
ORDER BY proto
`

// ListModelRuntimeProtocols 返回该 Model 当前可用渠道覆盖的入口协议集合。
// 协议不落库，恒等于实际供给能力。
func (q *Queries) ListModelRuntimeProtocols(ctx context.Context, modelID int64) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listModelRuntimeProtocols, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var ingress_protocol interface{}
		if err := rows.Scan(&ingress_protocol); err != nil {
			return nil, err
		}
		items = append(items, ingress_protocol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsLosingConfiguredSupply = `-- name: ListModelsLosingConfiguredSupply :many
SELECT m.id AS model_id,
       m.model_id AS public_model_id,
       m.display_name AS model_display_name
FROM models m
WHERE m.status = 'enabled'
  AND ($1::bigint IS NULL OR m.id = $1::bigint)
  AND EXISTS (
      SELECT 1
      FROM channel_models cm
      WHERE cm.channel_id = $2
        AND cm.model_id = m.id
        AND cm.status = 'enabled'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM channel_models cm2
      WHERE cm2.model_id = m.id
        AND cm2.channel_id <> $2
        AND cm2.status = 'enabled'
  )
ORDER BY m.id
`

type ListModelsLosingConfiguredSupplyParams struct {
	ModelID   pgtype.Int8
	ChannelID int64
}

type ListModelsLosingConfiguredSupplyRow struct {
	ModelID          int64
	PublicModelID    string
	ModelDisplayName string
}

// ListModelsLosingConfiguredSupply 返回「排除目标 Channel 上将失效的 enabled Binding 后，
// 失去最后一条配置支撑」的 enabled 模型。model_id 为空表示该 Channel 全部 Binding 同时失效，
// 否则只针对单条 Binding（停用/解除）。不读 Channel/Provider 实体状态。
func (q *Queries) ListModelsLosingConfiguredSupply(ctx context.Context, arg ListModelsLosingConfiguredSupplyParams) ([]ListModelsLosingConfiguredSupplyRow, error) {
	rows, err := q.db.Query(ctx, listModelsLosingConfiguredSupply, arg.ModelID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsLosingConfiguredSupplyRow
	for rows.Next() {
		var i ListModelsLosingConfiguredSupplyRow
		if err := rows.Scan(&i.ModelID, &i.PublicModelID, &i.ModelDisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsLosingRuntimeSupply = `-- name: ListModelsLosingRuntimeSupply :many
SELECT m.id AS model_id,
       m.model_id AS public_model_id,
       m.display_name AS model_display_name
FROM models m
WHERE m.status = 'enabled'
  AND EXISTS (
      SELECT 1
      FROM channel_models cm
      JOIN channels c ON c.id = cm.channel_id
      JOIN providers p ON p.id = c.provider_id
      WHERE cm.model_id = m.id
        AND c.id = $1
        AND cm.status = 'enabled'
        AND c.status = 'enabled'
        AND p.status = 'enabled'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM channel_models cm2
      JOIN channels c2 ON c2.id = cm2.channel_id
      JOIN providers p2 ON p2.id = c2.provider_id
      WHERE cm2.model_id = m.id
        AND c2.id <> $1
        AND cm2.status = 'enabled'
        AND c2.status = 'enabled'
        AND p2.status = 'enabled'
        AND c2.credential_valid
  )
ORDER BY m.id
`

type ListModelsLosingRuntimeSupplyRow struct {
	ModelID          int64
	PublicModelID    string
	ModelDisplayName string
}

// ListModelsLosingRuntimeSupply 返回暂停目标 Channel 后，按 Channel/Provider 当前启用状态
// 已无其他运行候选的 enabled 模型。只用于结果预览，不改变配置支撑定义。
func (q *Queries) ListModelsLosingRuntimeSupply(ctx context.Context, channelID int64) ([]ListModelsLosingRuntimeSupplyRow, error) {
	rows, err := q.db.Query(ctx, listModelsLosingRuntimeSupply, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsLosingRuntimeSupplyRow
	for rows.Next() {
		var i ListModelsLosingRuntimeSupplyRow
		if err := rows.Scan(&i.ModelID, &i.PublicModelID, &i.ModelDisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsLosingSalePrice = `-- name: ListModelsLosingSalePrice :many
SELECT m.id AS model_id,
       m.model_id AS public_model_id,
       m.display_name AS model_display_name
FROM models m
WHERE m.status = 'enabled'
  AND m.id = $1
  -- 目标窗口此刻确实在供价：撤一条本来就不可售的草稿行，对客户没有新影响。
  AND EXISTS (
      SELECT 1
      FROM model_prices target
      WHERE target.model_id = m.id
        AND ($2::bigint IS NULL
             OR target.id = $2::bigint)
        AND target.status = 'enabled'
        AND target.effective_from <= now()
        AND (target.effective_to IS NULL OR target.effective_to > now())
        AND (target.sale_uncached_input_price IS NOT NULL OR target.sale_discount IS NOT NULL)
  )
  -- 排除目标窗口后已无其他可售窗口。exclude 为空时该子查询恒无行，
  -- 对应 replace 语义：当前窗口整组失效，剩余集合为空。
  AND NOT EXISTS (
      SELECT 1
      FROM model_prices mp
      WHERE mp.model_id = m.id
        AND $2::bigint IS NOT NULL
        AND mp.id <> $2::bigint
        AND mp.status = 'enabled'
        AND mp.effective_from <= now()
        AND (mp.effective_to IS NULL OR mp.effective_to > now())
        AND (mp.sale_uncached_input_price IS NOT NULL OR mp.sale_discount IS NOT NULL)
  )
ORDER BY m.id
`

type ListModelsLosingSalePriceParams struct {
	ModelID        int64
	ExcludePriceID pgtype.Int8
}

type ListModelsLosingSalePriceRow struct {
	ModelID          int64
	PublicModelID    string
	ModelDisplayName string
}

// ListModelsLosingSalePrice 判断撤掉某条价格窗口后，该 enabled 模型是否失去可解析售价。
// exclude_price_id 为空表示整组当前窗口都会被替换（Create 的 replace_overlapping_enabled 路径）。
// 返回非空即「撤了它模型就没法卖了」，调用方必须先取得管理员确认。
func (q *Queries) ListModelsLosingSalePrice(ctx context.Context, arg ListModelsLosingSalePriceParams) ([]ListModelsLosingSalePriceRow, error) {
	rows, err := q.db.Query(ctx, listModelsLosingSalePrice, arg.ModelID, arg.ExcludePriceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsLosingSalePriceRow
	for rows.Next() {
		var i ListModelsLosingSalePriceRow
		if err := rows.Scan(&i.ModelID, &i.PublicModelID, &i.ModelDisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsWithoutRuntimeSupply = `-- name: ListModelsWithoutRuntimeSupply :many
SELECT m.id AS model_id,
       m.model_id AS public_model_id,
       m.display_name
FROM models m
WHERE m.status = 'enabled'
  AND NOT EXISTS (
      SELECT 1
      FROM channel_models cm
      JOIN channels c ON c.id = cm.channel_id
      JOIN providers p ON p.id = c.provider_id
      WHERE cm.model_id = m.id
        AND cm.status = 'enabled'
        AND c.status = 'enabled'
        AND c.credential_valid
        AND p.status = 'enabled'
  )
ORDER BY m.model_id
`

type ListModelsWithoutRuntimeSupplyRow struct {
	ModelID       int64
	PublicModelID string
	DisplayName   string
}

// ListModelsWithoutRuntimeSupply 列出 enabled 但当前没有任何运行候选的模型。
// 这是不变量被打破的信号（例如渠道凭据集体失效），供后台告警，不自动改状态。
func (q *Queries) ListModelsWithoutRuntimeSupply(ctx context.Context) ([]ListModelsWithoutRuntimeSupplyRow, error) {
	rows, err := q.db.Query(ctx, listModelsWithoutRuntimeSupply)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsWithoutRuntimeSupplyRow
	for rows.Next() {
		var i ListModelsWithoutRuntimeSupplyRow
		if err := rows.Scan(&i.ModelID, &i.PublicModelID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplyCandidatesForChannels = `-- name: ListSupplyCandidatesForChannels :many
SELECT cm.model_id,
       m.model_id AS public_model_id,
       m.display_name,
       m.status AS model_status,
       proto AS ingress_protocol,
       COUNT(DISTINCT c.id) AS supporting_channels
FROM channels c
JOIN channel_models cm ON cm.channel_id = c.id AND cm.status = 'enabled'
JOIN models m ON m.id = cm.model_id
CROSS JOIN LATERAL unnest(c.protocols) AS proto
WHERE c.id = ANY($1::bigint[])
GROUP BY cm.model_id, m.model_id, m.display_name, m.status, proto
ORDER BY m.model_id, proto
`

type ListSupplyCandidatesForChannelsRow struct {
	ModelID            int64
	PublicModelID      string
	DisplayName        string
	ModelStatus        string
	IngressProtocol    interface{}
	SupportingChannels int64
}

// ListSupplyCandidatesForChannels 按给定 Channel 集合计算「模型 × 协议」供给覆盖：
// enabled Binding 去重，协议来自渠道的 protocols 数组展开。不读 Model 当前状态。
func (q *Queries) ListSupplyCandidatesForChannels(ctx context.Context, channelIds []int64) ([]ListSupplyCandidatesForChannelsRow, error) {
	rows, err := q.db.Query(ctx, listSupplyCandidatesForChannels, channelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplyCandidatesForChannelsRow
	for rows.Next() {
		var i ListSupplyCandidatesForChannelsRow
		if err := rows.Scan(
			&i.ModelID,
			&i.PublicModelID,
			&i.DisplayName,
			&i.ModelStatus,
			&i.IngressProtocol,
			&i.SupportingChannels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockModelsForSupplyChange = `-- name: LockModelsForSupplyChange :many

SELECT id FROM models
WHERE id = ANY($1::bigint[])
ORDER BY id
FOR UPDATE
`

// 模型供给状态归属。
//
// 供给的根是 Model：模型 enabled 即对外可售，不再有「线路售卖意图」这一层。
// 由此产生一条不变量：**enabled 的模型必定至少有一条可用渠道能供**。
// 它需要双向守住：
//
//	减法侧——停用/解绑渠道前，检查哪些模型会失去全部供给（本文件的 Losing* 查询）；
//	加法侧——启用模型前，检查是否已有供给（ModelHasConfiguredSupply / ModelHasRuntimeSupply）。
//
// 「配置支撑」只看 enabled 的 Channel-Model Binding，不读 Channel/Provider 实体状态；
// 「运行候选」额外要求 Channel、Provider enabled 且凭据有效。前者管配置意图，后者管此刻能不能打通。
// 影响计算查询必须在 LockModelsForSupplyChange 取得的 Model 行锁内执行。
// LockModelsForSupplyChange 按 model_id 升序锁定 Model 行，作为供给变更的串行化点。
// 收缩侧（停用/解除 Binding、停用 Channel、停用 Model）与扩张侧（启用 Binding、启用 Model）
// 都必须先取得该锁再计算或校验。
func (q *Queries) LockModelsForSupplyChange(ctx context.Context, modelIds []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockModelsForSupplyChange, modelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelDisableImpactCounts = `-- name: ModelDisableImpactCounts :one
SELECT COUNT(*) AS enabled_bindings,
       COUNT(DISTINCT c.id) AS channels,
       COUNT(DISTINCT c.provider_id) AS providers
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
WHERE cm.model_id = $1 AND cm.status = 'enabled'
`

type ModelDisableImpactCountsRow struct {
	EnabledBindings int64
	Channels        int64
	Providers       int64
}

// ModelDisableImpactCounts 统计 Model 全局暂停影响范围内的 enabled Binding 及其 Channel/Provider 数。
func (q *Queries) ModelDisableImpactCounts(ctx context.Context, modelID int64) (ModelDisableImpactCountsRow, error) {
	row := q.db.QueryRow(ctx, modelDisableImpactCounts, modelID)
	var i ModelDisableImpactCountsRow
	err := row.Scan(&i.EnabledBindings, &i.Channels, &i.Providers)
	return i, err
}

const modelHasConfiguredSupply = `-- name: ModelHasConfiguredSupply :one
SELECT EXISTS (
    SELECT 1
    FROM channel_models cm
    WHERE cm.model_id = $1
      AND cm.status = 'enabled'
) AS supported
`

// ModelHasConfiguredSupply 判断该 Model 是否存在任意 enabled Binding（配置意图层面的供给）。
func (q *Queries) ModelHasConfiguredSupply(ctx context.Context, modelID int64) (bool, error) {
	row := q.db.QueryRow(ctx, modelHasConfiguredSupply, modelID)
	var supported bool
	err := row.Scan(&supported)
	return supported, err
}

const modelHasEffectiveBasePrice = `-- name: ModelHasEffectiveBasePrice :one
SELECT EXISTS (
    SELECT 1 FROM model_prices mp
    WHERE mp.model_id = $1
      AND mp.status = 'enabled'
      AND mp.effective_from <= now()
      AND (mp.effective_to IS NULL OR mp.effective_to > now())
) AS has_base
`

// ModelHasEffectiveBasePrice 判断该 Model 此刻是否有一条生效中的基准价窗口。
// 草稿行（有基准价、无售价）这里为真；与 ModelHasResolvableSalePrice 合起来区分启用失败原因。
func (q *Queries) ModelHasEffectiveBasePrice(ctx context.Context, modelID int64) (bool, error) {
	row := q.db.QueryRow(ctx, modelHasEffectiveBasePrice, modelID)
	var has_base bool
	err := row.Scan(&has_base)
	return has_base, err
}

const modelHasResolvableSalePrice = `-- name: ModelHasResolvableSalePrice :one
SELECT EXISTS (
    SELECT 1 FROM model_prices mp
    WHERE mp.model_id = $1
      AND mp.status = 'enabled'
      AND mp.effective_from <= now()
      AND (mp.effective_to IS NULL OR mp.effective_to > now())
      AND (mp.sale_uncached_input_price IS NOT NULL OR mp.sale_discount IS NOT NULL)
) AS has_sale
`

// ModelHasResolvableSalePrice 判断生效基准价窗口上是否已配售价折扣或绝对售价。
func (q *Queries) ModelHasResolvableSalePrice(ctx context.Context, modelID int64) (bool, error) {
	row := q.db.QueryRow(ctx, modelHasResolvableSalePrice, modelID)
	var has_sale bool
	err := row.Scan(&has_sale)
	return has_sale, err
}

const modelHasRuntimeSupply = `-- name: ModelHasRuntimeSupply :one
SELECT EXISTS (
    SELECT 1
    FROM channel_models cm
    JOIN channels c ON c.id = cm.channel_id
    JOIN providers p ON p.id = c.provider_id
    WHERE cm.model_id = $1
      AND cm.status = 'enabled'
      AND c.status = 'enabled'
      AND c.credential_valid
      AND p.status = 'enabled'
      AND EXISTS (
          SELECT 1 FROM model_prices mp
          WHERE mp.model_id = cm.model_id
            AND mp.status = 'enabled'
            AND mp.effective_from <= now()
            AND (mp.effective_to IS NULL OR mp.effective_to > now())
            AND (mp.sale_uncached_input_price IS NOT NULL OR mp.sale_discount IS NOT NULL)
      )
      AND (
          EXISTS (
              SELECT 1 FROM channel_prices cp
              WHERE cp.channel_id = c.id AND cp.model_id = cm.model_id AND cp.status = 'enabled'
          )
          OR EXISTS (
              SELECT 1 FROM channel_cost_multipliers ccm
              WHERE ccm.channel_id = c.id
                AND (ccm.model_id = cm.model_id OR ccm.model_id IS NULL)
                AND ccm.status = 'enabled'
          )
      )
) AS supported
`

// ModelHasRuntimeSupply 判断该 Model 此刻是否真的能打通：需要 Binding、Channel、Provider
// 三级 enabled、凭据有效，且渠道成本可解析（有绝对覆盖或价格倍率，否则不参与计费也就进不了候选）。
// 这是启用模型的前置条件，用于守住「enabled 即可调用」的不变量。
//
// 基准价条件必须与 FindModelCandidates 取 base 的那个 INNER JOIN LATERAL 对齐：
// 那边没有生效基准价就没有候选。少了这一条，一个没配价的模型能被成功 enable、
// 出现在 /v1/models 里，却对每次调用都返回 404。
// 售价也要可解析：允许库里只有基准价的草稿行，但那种行不可售，不能拿来 enable。
func (q *Queries) ModelHasRuntimeSupply(ctx context.Context, modelID int64) (bool, error) {
	row := q.db.QueryRow(ctx, modelHasRuntimeSupply, modelID)
	var supported bool
	err := row.Scan(&supported)
	return supported, err
}

const modelHasSuccessorSalePriceWindow = `-- name: ModelHasSuccessorSalePriceWindow :one
SELECT EXISTS (
    SELECT 1
    FROM model_prices mp
    WHERE mp.model_id = $1
      AND mp.id <> $2
      AND mp.status = 'enabled'
      AND mp.effective_from <= $3::timestamptz
      AND (mp.effective_to IS NULL OR mp.effective_to > $3::timestamptz)
      AND (mp.sale_uncached_input_price IS NOT NULL OR mp.sale_discount IS NOT NULL)
) AS has_successor
`

type ModelHasSuccessorSalePriceWindowParams struct {
	ModelID        int64
	ExcludePriceID int64
	ExpiresAt      pgtype.Timestamptz
}

// ModelHasSuccessorSalePriceWindow 判断给定到期时刻之后是否还有接续的可售窗口。
// 窗口自然到期没有任何管理员操作可以拦截，创建带到期时间的窗口时用它当场提示。
func (q *Queries) ModelHasSuccessorSalePriceWindow(ctx context.Context, arg ModelHasSuccessorSalePriceWindowParams) (bool, error) {
	row := q.db.QueryRow(ctx, modelHasSuccessorSalePriceWindow, arg.ModelID, arg.ExcludePriceID, arg.ExpiresAt)
	var has_successor bool
	err := row.Scan(&has_successor)
	return has_successor, err
}
