// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoCloseResolvedTickets = `-- name: AutoCloseResolvedTickets :execrows

UPDATE tickets
SET status = 'closed', closed_at = now(), updated_at = now()
WHERE status = 'resolved' AND last_message_at < $1
`

// 工单维护 worker 查询：超期自动关闭与孤儿附件清理。
// AutoCloseResolvedTickets 把 resolved 且超期无新消息的工单批量关闭，返回关闭条数。
func (q *Queries) AutoCloseResolvedTickets(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, autoCloseResolvedTickets, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindAdminTicketAttachments = `-- name: BindAdminTicketAttachments :execrows
UPDATE ticket_attachments
SET ticket_id = $1, message_id = $2
WHERE uid = ANY($3::uuid[])
  AND message_id IS NULL
  AND uploader_type = 'admin'
`

type BindAdminTicketAttachmentsParams struct {
	TicketID  pgtype.Int8
	MessageID pgtype.Int8
	Uids      []pgtype.UUID
}

// BindAdminTicketAttachments 把运营上传的孤儿附件绑定到消息，语义同上。
func (q *Queries) BindAdminTicketAttachments(ctx context.Context, arg BindAdminTicketAttachmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAdminTicketAttachments, arg.TicketID, arg.MessageID, arg.Uids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindUserTicketAttachments = `-- name: BindUserTicketAttachments :execrows
UPDATE ticket_attachments
SET ticket_id = $1, message_id = $2
WHERE uid = ANY($3::uuid[])
  AND message_id IS NULL
  AND uploader_type = 'user'
  AND user_id = $4
`

type BindUserTicketAttachmentsParams struct {
	TicketID  pgtype.Int8
	MessageID pgtype.Int8
	Uids      []pgtype.UUID
	UserID    pgtype.Int8
}

// BindUserTicketAttachments 把用户本人的孤儿附件绑定到消息；返回实际绑定条数，
// 少于入参个数说明存在无效引用（不存在 / 已绑定 / 不属于该用户），由调用方在事务里回滚。
func (q *Queries) BindUserTicketAttachments(ctx context.Context, arg BindUserTicketAttachmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindUserTicketAttachments,
		arg.TicketID,
		arg.MessageID,
		arg.Uids,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearTicketAdminUnread = `-- name: ClearTicketAdminUnread :execrows
UPDATE tickets
SET admin_unread = false, updated_at = now()
WHERE id = $1 AND admin_unread
`

// ClearTicketAdminUnread 运营打开详情时清除队列红点（幂等）。
func (q *Queries) ClearTicketAdminUnread(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearTicketAdminUnread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearTicketUserUnread = `-- name: ClearTicketUserUnread :execrows
UPDATE tickets
SET user_unread = false, updated_at = now()
WHERE id = $1 AND user_unread
`

// ClearTicketUserUnread 用户打开详情时清除未读红点（幂等）。
func (q *Queries) ClearTicketUserUnread(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearTicketUserUnread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeAdminTicket = `-- name: CloseAdminTicket :one
UPDATE tickets
SET status = 'closed', closed_at = now(), updated_at = now()
WHERE uid = $1 AND status <> 'closed'
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

// CloseAdminTicket 运营直接关闭工单（终态）。
func (q *Queries) CloseAdminTicket(ctx context.Context, uid pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, closeAdminTicket, uid)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeConsoleTicket = `-- name: CloseConsoleTicket :one
UPDATE tickets
SET status = 'closed', closed_at = now(), user_unread = false, updated_at = now()
WHERE uid = $1 AND user_id = $2 AND status <> 'closed'
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

type CloseConsoleTicketParams struct {
	Uid    pgtype.UUID
	UserID int64
}

// CloseConsoleTicket 用户主动关闭本人工单；已关闭时不匹配任何行（幂等由调用方兜底）。
func (q *Queries) CloseConsoleTicket(ctx context.Context, arg CloseConsoleTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, closeConsoleTicket, arg.Uid, arg.UserID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAdminTickets = `-- name: CountAdminTickets :one
SELECT COUNT(*) AS total
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND ($2::text IS NULL OR t.category = $2::text)
  AND (
    $3::text IS NULL
    OR t.subject ILIKE '%' || $3::text || '%'
    OR u.email ILIKE '%' || $3::text || '%'
  )
`

type CountAdminTicketsParams struct {
	Status   pgtype.Text
	Category pgtype.Text
	Search   pgtype.Text
}

// CountAdminTickets 统计与 ListAdminTickets 同口径的总数（分页 meta 用）。
func (q *Queries) CountAdminTickets(ctx context.Context, arg CountAdminTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminTickets, arg.Status, arg.Category, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countConsoleTickets = `-- name: CountConsoleTickets :one
SELECT COUNT(*) AS total
FROM tickets
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND (
    $3::text IS NULL
    OR subject ILIKE '%' || $3::text || '%'
  )
`

type CountConsoleTicketsParams struct {
	UserID int64
	Status pgtype.Text
	Search pgtype.Text
}

// CountConsoleTickets 统计与 ListConsoleTickets 同口径的总数（分页 meta 用）。
func (q *Queries) CountConsoleTickets(ctx context.Context, arg CountConsoleTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsoleTickets, arg.UserID, arg.Status, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUserOrphanTicketAttachments = `-- name: CountUserOrphanTicketAttachments :one
SELECT COUNT(*) AS total
FROM ticket_attachments
WHERE user_id = $1 AND message_id IS NULL
`

// CountUserOrphanTicketAttachments 统计用户未绑定附件数（上传配额检查，命中孤儿部分索引）。
func (q *Queries) CountUserOrphanTicketAttachments(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countUserOrphanTicketAttachments, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTicket = `-- name: CreateTicket :one

INSERT INTO tickets (uid, user_id, subject, category)
VALUES ($1, $2, $3, $4)
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

type CreateTicketParams struct {
	Uid      pgtype.UUID
	UserID   int64
	Subject  string
	Category string
}

// Console 侧工单查询：所有读写都强制携带 user_id 归属条件，防止越权。
// CreateTicket 创建工单（初始态 open，admin_unread 默认 true 提示运营有新工单）。
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Uid,
		arg.UserID,
		arg.Subject,
		arg.Category,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketAttachment = `-- name: CreateTicketAttachment :one
INSERT INTO ticket_attachments (uid, user_id, uploader_type, file_name, mime_type, size_bytes, data)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
RETURNING id, uid, ticket_id, message_id, uploader_type, file_name, mime_type, size_bytes, created_at
`

type CreateTicketAttachmentParams struct {
	Uid          pgtype.UUID
	UserID       pgtype.Int8
	UploaderType string
	FileName     string
	MimeType     string
	SizeBytes    int32
	Data         []byte
}

type CreateTicketAttachmentRow struct {
	ID           int64
	Uid          pgtype.UUID
	TicketID     pgtype.Int8
	MessageID    pgtype.Int8
	UploaderType string
	FileName     string
	MimeType     string
	SizeBytes    int32
	CreatedAt    pgtype.Timestamptz
}

// CreateTicketAttachment 写入孤儿附件（ticket_id / message_id 为 NULL），提交消息时再绑定。
func (q *Queries) CreateTicketAttachment(ctx context.Context, arg CreateTicketAttachmentParams) (CreateTicketAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createTicketAttachment,
		arg.Uid,
		arg.UserID,
		arg.UploaderType,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Data,
	)
	var i CreateTicketAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TicketID,
		&i.MessageID,
		&i.UploaderType,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createTicketMessage = `-- name: CreateTicketMessage :one

INSERT INTO ticket_messages (ticket_id, author_type, body, body_text)
VALUES ($1, $2, $3, $4)
RETURNING id, ticket_id, author_type, body, body_text, created_at
`

type CreateTicketMessageParams struct {
	TicketID   int64
	AuthorType string
	Body       []byte
	BodyText   string
}

// 工单跨 surface 共用查询：消息与附件的读写由 Console 与 Admin 两侧共同使用，
// 归属与状态校验在各自 service 层完成后才会调到这里。
// CreateTicketMessage 追加一条工单消息（对话流按 id 升序即时间序）。
func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error) {
	row := q.db.QueryRow(ctx, createTicketMessage,
		arg.TicketID,
		arg.AuthorType,
		arg.Body,
		arg.BodyText,
	)
	var i TicketMessage
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorType,
		&i.Body,
		&i.BodyText,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrphanTicketAttachments = `-- name: DeleteOrphanTicketAttachments :execrows
DELETE FROM ticket_attachments
WHERE message_id IS NULL AND created_at < $1
`

// DeleteOrphanTicketAttachments 删除超期未绑定消息的孤儿附件（编辑中放弃的上传），返回删除条数。
func (q *Queries) DeleteOrphanTicketAttachments(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanTicketAttachments, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminTicket = `-- name: GetAdminTicket :one
SELECT t.id, t.uid, t.subject, t.category, t.status, t.user_unread, t.admin_unread,
    t.last_message_at, t.resolved_at, t.closed_at, t.created_at, t.updated_at,
    u.id AS user_id, u.email AS user_email, u.created_at AS user_created_at
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE t.uid = $1
`

type GetAdminTicketRow struct {
	ID            int64
	Uid           pgtype.UUID
	Subject       string
	Category      string
	Status        string
	UserUnread    bool
	AdminUnread   bool
	LastMessageAt pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	UserID        int64
	UserEmail     string
	UserCreatedAt pgtype.Timestamptz
}

// GetAdminTicket 按 uid 取工单详情，连带用户侧栏信息。
func (q *Queries) GetAdminTicket(ctx context.Context, uid pgtype.UUID) (GetAdminTicketRow, error) {
	row := q.db.QueryRow(ctx, getAdminTicket, uid)
	var i GetAdminTicketRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserCreatedAt,
	)
	return i, err
}

const getConsoleTicket = `-- name: GetConsoleTicket :one
SELECT id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
FROM tickets
WHERE uid = $1 AND user_id = $2
`

type GetConsoleTicketParams struct {
	Uid    pgtype.UUID
	UserID int64
}

// GetConsoleTicket 按 uid 取本人工单；uid 与 user_id 必须同时匹配。
func (q *Queries) GetConsoleTicket(ctx context.Context, arg GetConsoleTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getConsoleTicket, arg.Uid, arg.UserID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketAttachmentData = `-- name: GetTicketAttachmentData :one
SELECT uid, file_name, mime_type, size_bytes, data
FROM ticket_attachments
WHERE uid = $1
`

type GetTicketAttachmentDataRow struct {
	Uid       pgtype.UUID
	FileName  string
	MimeType  string
	SizeBytes int32
	Data      []byte
}

// GetTicketAttachmentData 按 uid 取附件内容（签名下载端点用；签名即鉴权，不查归属）。
func (q *Queries) GetTicketAttachmentData(ctx context.Context, uid pgtype.UUID) (GetTicketAttachmentDataRow, error) {
	row := q.db.QueryRow(ctx, getTicketAttachmentData, uid)
	var i GetTicketAttachmentDataRow
	err := row.Scan(
		&i.Uid,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Data,
	)
	return i, err
}

const listAdminTickets = `-- name: ListAdminTickets :many

SELECT t.id, t.uid, t.subject, t.category, t.status, t.admin_unread,
    t.last_message_at, t.created_at,
    u.id AS user_id, u.email AS user_email
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND ($2::text IS NULL OR t.category = $2::text)
  AND (
    $3::text IS NULL
    OR t.subject ILIKE '%' || $3::text || '%'
    OR u.email ILIKE '%' || $3::text || '%'
  )
ORDER BY t.last_message_at DESC, t.id DESC
LIMIT $5 OFFSET $4
`

type ListAdminTicketsParams struct {
	Status     pgtype.Text
	Category   pgtype.Text
	Search     pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type ListAdminTicketsRow struct {
	ID            int64
	Uid           pgtype.UUID
	Subject       string
	Category      string
	Status        string
	AdminUnread   bool
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UserID        int64
	UserEmail     string
}

// Admin 侧工单查询：运营队列、详情与状态流转。单管理员，无坐席归属概念。
// ListAdminTickets 分页列出工单队列（最近更新在前），可按状态、分类过滤，
// 按主题或用户邮箱模糊搜索。
func (q *Queries) ListAdminTickets(ctx context.Context, arg ListAdminTicketsParams) ([]ListAdminTicketsRow, error) {
	rows, err := q.db.Query(ctx, listAdminTickets,
		arg.Status,
		arg.Category,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminTicketsRow
	for rows.Next() {
		var i ListAdminTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Subject,
			&i.Category,
			&i.Status,
			&i.AdminUnread,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleTickets = `-- name: ListConsoleTickets :many
SELECT id, uid, subject, category, status, user_unread, last_message_at, created_at
FROM tickets
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND (
    $3::text IS NULL
    OR subject ILIKE '%' || $3::text || '%'
  )
ORDER BY last_message_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListConsoleTicketsParams struct {
	UserID     int64
	Status     pgtype.Text
	Search     pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type ListConsoleTicketsRow struct {
	ID            int64
	Uid           pgtype.UUID
	Subject       string
	Category      string
	Status        string
	UserUnread    bool
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// ListConsoleTickets 分页列出本人工单（最近更新在前），可按主题和状态过滤。
func (q *Queries) ListConsoleTickets(ctx context.Context, arg ListConsoleTicketsParams) ([]ListConsoleTicketsRow, error) {
	rows, err := q.db.Query(ctx, listConsoleTickets,
		arg.UserID,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleTicketsRow
	for rows.Next() {
		var i ListConsoleTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Subject,
			&i.Category,
			&i.Status,
			&i.UserUnread,
			&i.LastMessageAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketAttachmentsMeta = `-- name: ListTicketAttachmentsMeta :many
SELECT id, uid, ticket_id, message_id, uploader_type, file_name, mime_type, size_bytes, created_at
FROM ticket_attachments
WHERE ticket_id = $1 AND message_id IS NOT NULL
ORDER BY id
`

type ListTicketAttachmentsMetaRow struct {
	ID           int64
	Uid          pgtype.UUID
	TicketID     pgtype.Int8
	MessageID    pgtype.Int8
	UploaderType string
	FileName     string
	MimeType     string
	SizeBytes    int32
	CreatedAt    pgtype.Timestamptz
}

// ListTicketAttachmentsMeta 取某工单全部已绑定附件的元数据（不含二进制），详情页拼签名 URL 用。
func (q *Queries) ListTicketAttachmentsMeta(ctx context.Context, ticketID pgtype.Int8) ([]ListTicketAttachmentsMetaRow, error) {
	rows, err := q.db.Query(ctx, listTicketAttachmentsMeta, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketAttachmentsMetaRow
	for rows.Next() {
		var i ListTicketAttachmentsMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TicketID,
			&i.MessageID,
			&i.UploaderType,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT id, ticket_id, author_type, body, body_text, created_at
FROM ticket_messages
WHERE ticket_id = $1
ORDER BY id
`

// ListTicketMessages 取某工单全部消息（升序），详情页对话流用。
func (q *Queries) ListTicketMessages(ctx context.Context, ticketID int64) ([]TicketMessage, error) {
	rows, err := q.db.Query(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketMessage
	for rows.Next() {
		var i TicketMessage
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorType,
			&i.Body,
			&i.BodyText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenAdminTicket = `-- name: ReopenAdminTicket :one
UPDATE tickets
SET status = 'open', resolved_at = NULL, closed_at = NULL, updated_at = now()
WHERE uid = $1 AND status = ANY(ARRAY['resolved'::text, 'closed'::text])
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

// ReopenAdminTicket 运营把 resolved/closed 工单拉回 open（误操作恢复）。
func (q *Queries) ReopenAdminTicket(ctx context.Context, uid pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, reopenAdminTicket, uid)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveAdminTicket = `-- name: ResolveAdminTicket :one
UPDATE tickets
SET status = 'resolved', resolved_at = now(), user_unread = true, updated_at = now()
WHERE uid = $1 AND status = ANY(ARRAY['open'::text, 'pending'::text])
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

// ResolveAdminTicket 标记已解决；仅 open/pending 可解决，resolved 超期由 worker 关闭。
func (q *Queries) ResolveAdminTicket(ctx context.Context, uid pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, resolveAdminTicket, uid)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const summarizeConsoleTickets = `-- name: SummarizeConsoleTickets :one
SELECT
    COUNT(*) FILTER (WHERE status <> 'closed') AS active_total,
    COUNT(*) FILTER (WHERE user_unread) AS unread_total
FROM tickets
WHERE user_id = $1
`

type SummarizeConsoleTicketsRow struct {
	ActiveTotal int64
	UnreadTotal int64
}

// SummarizeConsoleTickets 返回未关闭工单数与未读数（侧栏角标轮询）。
func (q *Queries) SummarizeConsoleTickets(ctx context.Context, userID int64) (SummarizeConsoleTicketsRow, error) {
	row := q.db.QueryRow(ctx, summarizeConsoleTickets, userID)
	var i SummarizeConsoleTicketsRow
	err := row.Scan(&i.ActiveTotal, &i.UnreadTotal)
	return i, err
}

const touchTicketOnAdminMessage = `-- name: TouchTicketOnAdminMessage :one
UPDATE tickets
SET status = 'pending', user_unread = true, last_message_at = now(), updated_at = now()
WHERE id = $1 AND status <> 'closed'
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

// TouchTicketOnAdminMessage 客服回复后的状态推进：转入 pending 并提醒用户；
// closed 不匹配任何行，由调用方判定并拒绝。
func (q *Queries) TouchTicketOnAdminMessage(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, touchTicketOnAdminMessage, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTicketOnUserMessage = `-- name: TouchTicketOnUserMessage :one
UPDATE tickets
SET status = 'open', admin_unread = true, resolved_at = NULL,
    last_message_at = now(), updated_at = now()
WHERE id = $1 AND status <> 'closed'
RETURNING id, uid, user_id, subject, category, status, user_unread, admin_unread,
    last_message_at, resolved_at, closed_at, created_at, updated_at
`

// TouchTicketOnUserMessage 用户回复后的状态推进：pending/resolved 回到 open（重开），
// 提醒运营有新消息；closed 不匹配任何行，由调用方判定并拒绝。
func (q *Queries) TouchTicketOnUserMessage(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, touchTicketOnUserMessage, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Status,
		&i.UserUnread,
		&i.AdminUnread,
		&i.LastMessageAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
