// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listConsoleUsageByAPIKey = `-- name: ListConsoleUsageByAPIKey :many
WITH windowed AS MATERIALIZED (
    SELECT
        r.id,
        r.stream,
        r.requested_model_id,
        r.api_key_id,
        r.endpoint,
        r.request_id,
        r.client_ip
    FROM request_records r
    WHERE r.user_id = $7
      AND ($8::timestamptz IS NULL OR r.created_at >= $8::timestamptz)
      AND ($9::timestamptz IS NULL OR r.created_at < $9::timestamptz)
)
SELECT
    w.api_key_id AS group_id,
    COALESCE(NULLIF(ak.name, ''), ak.key_prefix, '') AS group_name,
    COUNT(*)::bigint AS request_count,
    SUM(
        COALESCE(ur.uncached_input_tokens, 0)
        + COALESCE(ur.cache_read_input_tokens, 0)
        + COALESCE(ur.cache_creation_5m_input_tokens, 0)
        + COALESCE(ur.cache_creation_1h_input_tokens, 0)
        + COALESCE(ur.cache_creation_30m_input_tokens, 0)
        + COALESCE(ur.output_tokens_total, 0)
    )::bigint AS token_count,
    SUM(ch.charge_usd)::numeric AS charge_usd
FROM windowed w
JOIN usage_records ur ON ur.request_record_id = w.id
LEFT JOIN api_keys ak ON ak.id = w.api_key_id
LEFT JOIN models m ON m.model_id = w.requested_model_id
JOIN LATERAL (
    SELECT SUM(
        CASE
            WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
            WHEN le.entry_type IN ('credit', 'refund', 'adjustment_credit') THEN -le.amount
            ELSE 0
        END
    ) AS charge_usd
    FROM ledger_entries le
    WHERE le.request_record_id = w.id AND le.currency = 'USD'
) ch ON ch.charge_usd > 0
WHERE (
      COALESCE(cardinality($1::bigint[]), 0) = 0
      OR w.api_key_id = ANY($1::bigint[])
  )
  AND (
      COALESCE(cardinality($2::text[]), 0) = 0
      OR w.requested_model_id = ANY($2::text[])
  )
  AND (
      COALESCE(cardinality($3::text[]), 0) = 0
      OR w.endpoint = ANY($3::text[])
  )
  AND (
      COALESCE(cardinality($4::text[]), 0) = 0
      OR (w.stream AND 'stream' = ANY($4::text[]))
      OR ((NOT w.stream) AND 'sync' = ANY($4::text[]))
  )
  AND (
      $5::text IS NULL
      OR btrim($5::text) = ''
      OR w.requested_model_id ILIKE '%' || btrim($5::text) || '%'
      OR COALESCE(m.display_name, '') ILIKE '%' || btrim($5::text) || '%'
      OR w.request_id ILIKE '%' || btrim($5::text) || '%'
      OR COALESCE(w.client_ip, '') ILIKE '%' || btrim($5::text) || '%'
  )
GROUP BY w.api_key_id, COALESCE(NULLIF(ak.name, ''), ak.key_prefix, '')
ORDER BY charge_usd DESC, group_id ASC
LIMIT $6
`

type ListConsoleUsageByAPIKeyParams struct {
	ApiKeyIds   []int64
	ModelIds    []string
	Endpoints   []string
	StreamTypes []string
	Q           pgtype.Text
	RowLimit    int32
	UserID      int64
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
}

type ListConsoleUsageByAPIKeyRow struct {
	GroupID      int64
	GroupName    string
	RequestCount int64
	TokenCount   int64
	ChargeUsd    pgtype.Numeric
}

// 明细排行：按 API 密钥分组，按消费降序。
func (q *Queries) ListConsoleUsageByAPIKey(ctx context.Context, arg ListConsoleUsageByAPIKeyParams) ([]ListConsoleUsageByAPIKeyRow, error) {
	rows, err := q.db.Query(ctx, listConsoleUsageByAPIKey,
		arg.ApiKeyIds,
		arg.ModelIds,
		arg.Endpoints,
		arg.StreamTypes,
		arg.Q,
		arg.RowLimit,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleUsageByAPIKeyRow
	for rows.Next() {
		var i ListConsoleUsageByAPIKeyRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.RequestCount,
			&i.TokenCount,
			&i.ChargeUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleUsageByModel = `-- name: ListConsoleUsageByModel :many
WITH windowed AS MATERIALIZED (
    SELECT
        r.id,
        r.created_at,
        r.stream,
        r.requested_model_id,
        r.ingress_protocol,
        r.api_key_id,
        r.endpoint,
        r.request_id,
        r.client_ip
    FROM request_records r
    WHERE r.user_id = $2
      AND ($3::timestamptz IS NULL OR r.created_at >= $3::timestamptz)
      AND ($4::timestamptz IS NULL OR r.created_at < $4::timestamptz)
),
billed AS MATERIALIZED (
    SELECT
        w.id,
        w.created_at,
        w.requested_model_id,
        w.ingress_protocol,
        ch.charge_usd,
        (
            COALESCE(ur.uncached_input_tokens, 0)
            + COALESCE(ur.cache_read_input_tokens, 0)
            + COALESCE(ur.cache_creation_5m_input_tokens, 0)
            + COALESCE(ur.cache_creation_1h_input_tokens, 0)
            + COALESCE(ur.cache_creation_30m_input_tokens, 0)
            + COALESCE(ur.output_tokens_total, 0)
        ) AS total_tokens
    FROM windowed w
    JOIN usage_records ur ON ur.request_record_id = w.id
    LEFT JOIN api_keys ak ON ak.id = w.api_key_id
    LEFT JOIN models m ON m.model_id = w.requested_model_id
    JOIN LATERAL (
        SELECT SUM(
            CASE
                WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
                WHEN le.entry_type IN ('credit', 'refund', 'adjustment_credit') THEN -le.amount
                ELSE 0
            END
        ) AS charge_usd
        FROM ledger_entries le
        WHERE le.request_record_id = w.id AND le.currency = 'USD'
    ) ch ON ch.charge_usd > 0
    WHERE (
          COALESCE(cardinality($5::bigint[]), 0) = 0
          OR w.api_key_id = ANY($5::bigint[])
      )
      AND (
          COALESCE(cardinality($6::text[]), 0) = 0
          OR w.requested_model_id = ANY($6::text[])
      )
      AND (
          COALESCE(cardinality($7::text[]), 0) = 0
          OR w.endpoint = ANY($7::text[])
      )
      AND (
          COALESCE(cardinality($8::text[]), 0) = 0
          OR (w.stream AND 'stream' = ANY($8::text[]))
          OR ((NOT w.stream) AND 'sync' = ANY($8::text[]))
      )
      AND (
          $9::text IS NULL
          OR btrim($9::text) = ''
          OR w.requested_model_id ILIKE '%' || btrim($9::text) || '%'
          OR COALESCE(m.display_name, '') ILIKE '%' || btrim($9::text) || '%'
          OR w.request_id ILIKE '%' || btrim($9::text) || '%'
          OR COALESCE(w.client_ip, '') ILIKE '%' || btrim($9::text) || '%'
      )
),
totals AS (
    SELECT
        requested_model_id,
        COUNT(*)::bigint AS request_count,
        SUM(total_tokens)::bigint AS token_count,
        SUM(charge_usd)::numeric AS charge_usd
    FROM billed
    GROUP BY requested_model_id
),
latest AS (
    SELECT DISTINCT ON (b.requested_model_id)
        b.requested_model_id,
        b.ingress_protocol,
        ps.uncached_input_price,
        ps.output_price
    FROM billed b
    LEFT JOIN price_snapshots ps ON ps.request_record_id = b.id
    ORDER BY b.requested_model_id, b.created_at DESC, b.id DESC
)
SELECT
    t.requested_model_id AS group_id,
    COALESCE(NULLIF(m.display_name, ''), t.requested_model_id) AS group_name,
    t.request_count,
    t.token_count,
    t.charge_usd,
    COALESCE(l.ingress_protocol, '') AS ingress_protocol,
    l.uncached_input_price AS input_price_per_1m,
    l.output_price AS output_price_per_1m
FROM totals t
LEFT JOIN models m ON m.model_id = t.requested_model_id
LEFT JOIN latest l ON l.requested_model_id = t.requested_model_id
ORDER BY t.charge_usd DESC, t.requested_model_id ASC
LIMIT $1
`

type ListConsoleUsageByModelParams struct {
	RowLimit    int32
	UserID      int64
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	ApiKeyIds   []int64
	ModelIds    []string
	Endpoints   []string
	StreamTypes []string
	Q           pgtype.Text
}

type ListConsoleUsageByModelRow struct {
	GroupID          string
	GroupName        string
	RequestCount     int64
	TokenCount       int64
	ChargeUsd        pgtype.Numeric
	IngressProtocol  string
	InputPricePer1m  pgtype.Numeric
	OutputPricePer1m pgtype.Numeric
}

// 明细排行：按请求模型分组，按消费降序。协议与单价取该模型最近一条扣费请求。
func (q *Queries) ListConsoleUsageByModel(ctx context.Context, arg ListConsoleUsageByModelParams) ([]ListConsoleUsageByModelRow, error) {
	rows, err := q.db.Query(ctx, listConsoleUsageByModel,
		arg.RowLimit,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
		arg.ApiKeyIds,
		arg.ModelIds,
		arg.Endpoints,
		arg.StreamTypes,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleUsageByModelRow
	for rows.Next() {
		var i ListConsoleUsageByModelRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.RequestCount,
			&i.TokenCount,
			&i.ChargeUsd,
			&i.IngressProtocol,
			&i.InputPricePer1m,
			&i.OutputPricePer1m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleUsageFilterModels = `-- name: ListConsoleUsageFilterModels :many
SELECT DISTINCT
    r.requested_model_id AS model_id,
    COALESCE(NULLIF(m.display_name, ''), r.requested_model_id) AS display_name
FROM request_records r
JOIN usage_records ur ON ur.request_record_id = r.id
LEFT JOIN models m ON m.model_id = r.requested_model_id
JOIN LATERAL (
    SELECT SUM(
        CASE
            WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
            WHEN le.entry_type IN ('credit', 'refund', 'adjustment_credit') THEN -le.amount
            ELSE 0
        END
    ) AS charge_usd
    FROM ledger_entries le
    WHERE le.request_record_id = r.id AND le.currency = 'USD'
) ch ON ch.charge_usd > 0
WHERE r.user_id = $1
ORDER BY display_name, model_id
`

type ListConsoleUsageFilterModelsRow struct {
	ModelID     string
	DisplayName string
}

// 模型筛选项：当前用户实际扣费请求上出现过的模型。
func (q *Queries) ListConsoleUsageFilterModels(ctx context.Context, userID int64) ([]ListConsoleUsageFilterModelsRow, error) {
	rows, err := q.db.Query(ctx, listConsoleUsageFilterModels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleUsageFilterModelsRow
	for rows.Next() {
		var i ListConsoleUsageFilterModelsRow
		if err := rows.Scan(&i.ModelID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleUsageTimeseries = `-- name: ListConsoleUsageTimeseries :many

WITH windowed AS MATERIALIZED (
    SELECT
        r.id,
        r.created_at,
        r.stream,
        r.started_at,
        r.completed_at,
        r.requested_model_id,
        r.api_key_id,
        r.endpoint,
        r.request_id,
        r.client_ip
    FROM request_records r
    WHERE r.user_id = $2
      AND r.created_at >= $3::timestamptz
      AND r.created_at < $4::timestamptz
),
billed AS MATERIALIZED (
    SELECT
        (
            date_trunc(
                $5::text,
                w.created_at AT TIME ZONE $1::text
            ) AT TIME ZONE $1::text
        ) AS bucket_start,
        w.started_at,
        w.completed_at,
        ch.charge_usd,
        COALESCE(ur.uncached_input_tokens, 0) AS uncached_input_tokens,
        COALESCE(ur.cache_read_input_tokens, 0) AS cache_read_input_tokens,
        (
            COALESCE(ur.cache_creation_5m_input_tokens, 0)
            + COALESCE(ur.cache_creation_1h_input_tokens, 0)
            + COALESCE(ur.cache_creation_30m_input_tokens, 0)
        ) AS cache_creation_input_tokens,
        COALESCE(ur.output_tokens_total, 0) AS output_tokens,
        COALESCE(ur.uncached_input_tokens, 0)::numeric
            * COALESCE(ps.uncached_input_price, 0) / 1000000 AS uncached_input_charge_usd,
        (
            GREATEST(
                COALESCE(ur.output_tokens_total, 0) - COALESCE(ur.reasoning_output_tokens, 0),
                0
            )::numeric * COALESCE(ps.output_price, 0)
            + COALESCE(ur.reasoning_output_tokens, 0)::numeric
                * COALESCE(ps.reasoning_output_price, ps.output_price, 0)
        ) / 1000000 AS output_charge_usd,
        COALESCE(ur.cache_read_input_tokens, 0)::numeric
            * COALESCE(ps.cache_read_input_price, ps.uncached_input_price, 0)
            / 1000000 AS cache_read_charge_usd,
        (
            COALESCE(ur.cache_creation_5m_input_tokens, 0)::numeric
                * COALESCE(ps.cache_creation_5m_input_price, ps.uncached_input_price, 0)
            + COALESCE(ur.cache_creation_1h_input_tokens, 0)::numeric
                * COALESCE(ps.cache_creation_1h_input_price, ps.uncached_input_price, 0)
            + COALESCE(ur.cache_creation_30m_input_tokens, 0)::numeric
                * COALESCE(ps.cache_creation_30m_input_price, ps.uncached_input_price, 0)
        ) / 1000000 AS cache_creation_charge_usd,
        -- 缓存读若按未缓存价计费要多花多少，再减去缓存创建相对未缓存价的溢价。
        (
            COALESCE(ur.cache_read_input_tokens, 0)::numeric
                * (
                    COALESCE(ps.uncached_input_price, 0)
                    - COALESCE(ps.cache_read_input_price, ps.uncached_input_price, 0)
                )
            - (
                COALESCE(ur.cache_creation_5m_input_tokens, 0)::numeric
                    * (
                        COALESCE(ps.cache_creation_5m_input_price, ps.uncached_input_price, 0)
                        - COALESCE(ps.uncached_input_price, 0)
                    )
                + COALESCE(ur.cache_creation_1h_input_tokens, 0)::numeric
                    * (
                        COALESCE(ps.cache_creation_1h_input_price, ps.uncached_input_price, 0)
                        - COALESCE(ps.uncached_input_price, 0)
                    )
                + COALESCE(ur.cache_creation_30m_input_tokens, 0)::numeric
                    * (
                        COALESCE(ps.cache_creation_30m_input_price, ps.uncached_input_price, 0)
                        - COALESCE(ps.uncached_input_price, 0)
                    )
            )
        ) / 1000000 AS cache_saved_usd
    FROM windowed w
    JOIN usage_records ur ON ur.request_record_id = w.id
    LEFT JOIN price_snapshots ps ON ps.request_record_id = w.id
    LEFT JOIN api_keys ak ON ak.id = w.api_key_id
    LEFT JOIN models m ON m.model_id = w.requested_model_id
    JOIN LATERAL (
        SELECT SUM(
            CASE
                WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
                WHEN le.entry_type IN ('credit', 'refund', 'adjustment_credit') THEN -le.amount
                ELSE 0
            END
        ) AS charge_usd
        FROM ledger_entries le
        WHERE le.request_record_id = w.id AND le.currency = 'USD'
    ) ch ON ch.charge_usd > 0
    WHERE (
          COALESCE(cardinality($6::bigint[]), 0) = 0
          OR w.api_key_id = ANY($6::bigint[])
      )
      AND (
          COALESCE(cardinality($7::text[]), 0) = 0
          OR w.requested_model_id = ANY($7::text[])
      )
      AND (
          COALESCE(cardinality($8::text[]), 0) = 0
          OR w.endpoint = ANY($8::text[])
      )
      AND (
          COALESCE(cardinality($9::text[]), 0) = 0
          OR (w.stream AND 'stream' = ANY($9::text[]))
          OR ((NOT w.stream) AND 'sync' = ANY($9::text[]))
      )
      AND (
          $10::text IS NULL
          OR btrim($10::text) = ''
          OR w.requested_model_id ILIKE '%' || btrim($10::text) || '%'
          OR COALESCE(m.display_name, '') ILIKE '%' || btrim($10::text) || '%'
          OR w.request_id ILIKE '%' || btrim($10::text) || '%'
          OR COALESCE(w.client_ip, '') ILIKE '%' || btrim($10::text) || '%'
      )
),
grouped AS (
    SELECT
        b.bucket_start,
        COUNT(*)::bigint AS request_count,
        SUM(
            b.uncached_input_tokens + b.cache_read_input_tokens
            + b.cache_creation_input_tokens + b.output_tokens
        )::bigint AS token_count,
        SUM(b.uncached_input_tokens)::bigint AS uncached_input_token_count,
        SUM(b.cache_read_input_tokens)::bigint AS cache_read_token_count,
        SUM(b.cache_creation_input_tokens)::bigint AS cache_creation_token_count,
        SUM(b.output_tokens)::bigint AS output_token_count,
        SUM(b.charge_usd)::numeric AS charge_usd,
        SUM(b.uncached_input_charge_usd)::numeric AS uncached_input_charge_usd,
        SUM(b.output_charge_usd)::numeric AS output_charge_usd,
        SUM(b.cache_read_charge_usd)::numeric AS cache_read_charge_usd,
        SUM(b.cache_creation_charge_usd)::numeric AS cache_creation_charge_usd,
        SUM(b.cache_saved_usd)::numeric AS cache_saved_usd,
        -- 请求中心的耗时卡也要按桶出热力条，顺带在这里算掉，省一次全表扫描。
        COALESCE(
            AVG(EXTRACT(EPOCH FROM (b.completed_at - b.started_at)) * 1000)
                FILTER (WHERE b.completed_at IS NOT NULL AND b.started_at IS NOT NULL),
            0
        )::float8 AS average_latency_ms
    FROM billed b
    GROUP BY b.bucket_start
),
bucket_starts AS (
    SELECT series.local_start
    FROM generate_series(
        date_trunc(
            $5::text,
            $11::timestamptz AT TIME ZONE $1::text
        ),
        date_trunc(
            $5::text,
            $12::timestamptz AT TIME ZONE $1::text
        ),
        CASE $5::text
            WHEN 'minute' THEN interval '1 minute'
            WHEN 'hour' THEN interval '1 hour'
            WHEN 'day' THEN interval '1 day'
            WHEN 'week' THEN interval '1 week'
            WHEN 'month' THEN interval '1 month'
            WHEN 'quarter' THEN interval '3 months'
            WHEN 'year' THEN interval '1 year'
            ELSE interval '1 day'
        END
    ) AS series(local_start)
    WHERE series.local_start < (
        $12::timestamptz AT TIME ZONE $1::text
    )
),
buckets AS (
    SELECT
        local_start,
        local_start + CASE $5::text
            WHEN 'minute' THEN interval '1 minute'
            WHEN 'hour' THEN interval '1 hour'
            WHEN 'day' THEN interval '1 day'
            WHEN 'week' THEN interval '1 week'
            WHEN 'month' THEN interval '1 month'
            WHEN 'quarter' THEN interval '3 months'
            WHEN 'year' THEN interval '1 year'
            ELSE interval '1 day'
        END AS local_end
    FROM bucket_starts
)
SELECT
    (bk.local_start AT TIME ZONE $1::text)::timestamptz AS bucket_start,
    (bk.local_end AT TIME ZONE $1::text)::timestamptz AS bucket_end,
    COALESCE(g.request_count, 0)::bigint AS request_count,
    COALESCE(g.token_count, 0)::bigint AS token_count,
    COALESCE(g.uncached_input_token_count, 0)::bigint AS uncached_input_token_count,
    COALESCE(g.cache_read_token_count, 0)::bigint AS cache_read_token_count,
    COALESCE(g.cache_creation_token_count, 0)::bigint AS cache_creation_token_count,
    COALESCE(g.output_token_count, 0)::bigint AS output_token_count,
    COALESCE(g.charge_usd, 0)::numeric AS charge_usd,
    COALESCE(g.uncached_input_charge_usd, 0)::numeric AS uncached_input_charge_usd,
    COALESCE(g.output_charge_usd, 0)::numeric AS output_charge_usd,
    COALESCE(g.cache_read_charge_usd, 0)::numeric AS cache_read_charge_usd,
    COALESCE(g.cache_creation_charge_usd, 0)::numeric AS cache_creation_charge_usd,
    COALESCE(g.cache_saved_usd, 0)::numeric AS cache_saved_usd,
    COALESCE(g.average_latency_ms, 0)::float8 AS average_latency_ms
FROM buckets bk
LEFT JOIN grouped g
    ON g.bucket_start = (bk.local_start AT TIME ZONE $1::text)::timestamptz
ORDER BY bucket_start
`

type ListConsoleUsageTimeseriesParams struct {
	Tz          string
	UserID      int64
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	Bucket      string
	ApiKeyIds   []int64
	ModelIds    []string
	Endpoints   []string
	StreamTypes []string
	Q           pgtype.Text
	SeriesFrom  pgtype.Timestamptz
	SeriesTo    pgtype.Timestamptz
}

type ListConsoleUsageTimeseriesRow struct {
	BucketStart             pgtype.Timestamptz
	BucketEnd               pgtype.Timestamptz
	RequestCount            int64
	TokenCount              int64
	UncachedInputTokenCount int64
	CacheReadTokenCount     int64
	CacheCreationTokenCount int64
	OutputTokenCount        int64
	ChargeUsd               pgtype.Numeric
	UncachedInputChargeUsd  pgtype.Numeric
	OutputChargeUsd         pgtype.Numeric
	CacheReadChargeUsd      pgtype.Numeric
	CacheCreationChargeUsd  pgtype.Numeric
	CacheSavedUsd           pgtype.Numeric
	AverageLatencyMs        float64
}

// Console 用量统计：只查当前用户、且账本 USD 净扣费大于 0 的请求。
// 口径与 console/requests.sql 一致，只补两件请求中心做不到的事：
// 按时间分桶的趋势，以及按模型/密钥的分组排行。
//
// 账本一律用 JOIN LATERAL + idx_ledger_entries_request_record_id 做索引点查，
// 不要改回「charges CTE 再 JOIN windowed」：两个 CTE 的行数在 generic plan 下都会被
// 估成几十行，优化器随即选嵌套循环，1 万行请求会退化成上亿次比较（实测 8.5s）。
// LATERAL 的代价是固定的 N 次索引查找（1 万行约 13ms），不受参数估算影响。
// 按 bucket（minute/hour/day/week/month/quarter/year）分桶的用量与费用。
// from_time/to_time 是实际数据统计窗；series_from/series_to 是需要补齐的展示窗。
// 空桶由 generate_series 补齐，允许请求卡片展示尚未到达的未来桶。
func (q *Queries) ListConsoleUsageTimeseries(ctx context.Context, arg ListConsoleUsageTimeseriesParams) ([]ListConsoleUsageTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, listConsoleUsageTimeseries,
		arg.Tz,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
		arg.Bucket,
		arg.ApiKeyIds,
		arg.ModelIds,
		arg.Endpoints,
		arg.StreamTypes,
		arg.Q,
		arg.SeriesFrom,
		arg.SeriesTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleUsageTimeseriesRow
	for rows.Next() {
		var i ListConsoleUsageTimeseriesRow
		if err := rows.Scan(
			&i.BucketStart,
			&i.BucketEnd,
			&i.RequestCount,
			&i.TokenCount,
			&i.UncachedInputTokenCount,
			&i.CacheReadTokenCount,
			&i.CacheCreationTokenCount,
			&i.OutputTokenCount,
			&i.ChargeUsd,
			&i.UncachedInputChargeUsd,
			&i.OutputChargeUsd,
			&i.CacheReadChargeUsd,
			&i.CacheCreationChargeUsd,
			&i.CacheSavedUsd,
			&i.AverageLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleUsageTrendByGroup = `-- name: ListConsoleUsageTrendByGroup :many
WITH windowed AS MATERIALIZED (
    SELECT
        r.id,
        r.created_at,
        r.stream,
        r.requested_model_id,
        r.api_key_id,
        r.endpoint,
        r.request_id,
        r.client_ip
    FROM request_records r
    WHERE r.user_id = $1
      AND r.created_at >= $2::timestamptz
      AND r.created_at < $3::timestamptz
),
billed AS MATERIALIZED (
    SELECT
        (
            date_trunc(
                $5::text,
                w.created_at AT TIME ZONE $4::text
            ) AT TIME ZONE $4::text
        ) AS bucket_start,
        CASE $6::text
            WHEN 'api_key' THEN COALESCE(w.api_key_id::text, '')
            ELSE w.requested_model_id
        END AS group_id,
        CASE $6::text
            WHEN 'api_key' THEN COALESCE(NULLIF(ak.name, ''), w.api_key_id::text, '')
            ELSE COALESCE(NULLIF(m.display_name, ''), w.requested_model_id)
        END AS group_name,
        ch.charge_usd,
        (
            COALESCE(ur.uncached_input_tokens, 0)
            + COALESCE(ur.cache_read_input_tokens, 0)
            + COALESCE(ur.cache_creation_5m_input_tokens, 0)
            + COALESCE(ur.cache_creation_1h_input_tokens, 0)
            + COALESCE(ur.cache_creation_30m_input_tokens, 0)
            + COALESCE(ur.output_tokens_total, 0)
        ) AS total_tokens
    FROM windowed w
    JOIN usage_records ur ON ur.request_record_id = w.id
    LEFT JOIN api_keys ak ON ak.id = w.api_key_id
    LEFT JOIN models m ON m.model_id = w.requested_model_id
    JOIN LATERAL (
        SELECT SUM(
            CASE
                WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
                WHEN le.entry_type IN ('credit', 'refund', 'adjustment_credit') THEN -le.amount
                ELSE 0
            END
        ) AS charge_usd
        FROM ledger_entries le
        WHERE le.request_record_id = w.id AND le.currency = 'USD'
    ) ch ON ch.charge_usd > 0
    WHERE (
          COALESCE(cardinality($7::bigint[]), 0) = 0
          OR w.api_key_id = ANY($7::bigint[])
      )
      AND (
          COALESCE(cardinality($8::text[]), 0) = 0
          OR w.requested_model_id = ANY($8::text[])
      )
      AND (
          COALESCE(cardinality($9::text[]), 0) = 0
          OR w.endpoint = ANY($9::text[])
      )
      AND (
          COALESCE(cardinality($10::text[]), 0) = 0
          OR (w.stream AND 'stream' = ANY($10::text[]))
          OR ((NOT w.stream) AND 'sync' = ANY($10::text[]))
      )
),
ranked AS (
    SELECT b.group_id
    FROM billed b
    GROUP BY b.group_id
    ORDER BY SUM(b.charge_usd) DESC, b.group_id ASC
    LIMIT $11
),
folded AS (
    SELECT
        b.bucket_start,
        CASE WHEN r.group_id IS NULL THEN '__other__' ELSE b.group_id END AS group_id,
        CASE WHEN r.group_id IS NULL THEN '__other__' ELSE b.group_name END AS group_name,
        b.charge_usd,
        b.total_tokens
    FROM billed b
    LEFT JOIN ranked r ON r.group_id = b.group_id
)
SELECT
    f.bucket_start::timestamptz AS bucket_start,
    f.group_id::text AS group_id,
    -- 同一分组在窗口内可能改过名（密钥改名、模型换 display_name），取其一即可。
    MIN(f.group_name)::text AS group_name,
    COUNT(*)::bigint AS request_count,
    SUM(f.total_tokens)::bigint AS token_count,
    SUM(f.charge_usd)::numeric AS charge_usd
FROM folded f
GROUP BY f.bucket_start, f.group_id
ORDER BY f.bucket_start, SUM(f.charge_usd) DESC, f.group_id
`

type ListConsoleUsageTrendByGroupParams struct {
	UserID      int64
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	Tz          string
	Bucket      string
	Dimension   string
	ApiKeyIds   []int64
	ModelIds    []string
	Endpoints   []string
	StreamTypes []string
	TopN        int32
}

type ListConsoleUsageTrendByGroupRow struct {
	BucketStart  pgtype.Timestamptz
	GroupID      string
	GroupName    string
	RequestCount int64
	TokenCount   int64
	ChargeUsd    pgtype.Numeric
}

// 按「时间桶 × 分组」的二维聚合，给趋势图做堆叠。
// dimension 取 model / api_key；窗口内消费排前 top_n 的分组各占一段，
// 其余合并成 __other__ —— 趋势图上十几种颜色没法读，合并的阈值放在 SQL 里，
// 免得前端把上百个分组的整段序列都拉过去再丢掉。
// 空桶不在这里补：分组维度下补空桶会产生 桶数 × 分组数 行，交给 service 层按桶对齐。
func (q *Queries) ListConsoleUsageTrendByGroup(ctx context.Context, arg ListConsoleUsageTrendByGroupParams) ([]ListConsoleUsageTrendByGroupRow, error) {
	rows, err := q.db.Query(ctx, listConsoleUsageTrendByGroup,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
		arg.Tz,
		arg.Bucket,
		arg.Dimension,
		arg.ApiKeyIds,
		arg.ModelIds,
		arg.Endpoints,
		arg.StreamTypes,
		arg.TopN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleUsageTrendByGroupRow
	for rows.Next() {
		var i ListConsoleUsageTrendByGroupRow
		if err := rows.Scan(
			&i.BucketStart,
			&i.GroupID,
			&i.GroupName,
			&i.RequestCount,
			&i.TokenCount,
			&i.ChargeUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeConsoleUsageWindow = `-- name: SummarizeConsoleUsageWindow :one
WITH windowed AS MATERIALIZED (
    SELECT
        r.id,
        r.stream,
        r.requested_model_id,
        r.api_key_id,
        r.endpoint,
        r.request_id,
        r.client_ip
    FROM request_records r
    WHERE r.user_id = $6
      AND ($7::timestamptz IS NULL OR r.created_at >= $7::timestamptz)
      AND ($8::timestamptz IS NULL OR r.created_at < $8::timestamptz)
)
SELECT
    COUNT(*)::bigint AS request_count,
    COALESCE(SUM(
        COALESCE(ur.uncached_input_tokens, 0)
        + COALESCE(ur.cache_read_input_tokens, 0)
        + COALESCE(ur.cache_creation_5m_input_tokens, 0)
        + COALESCE(ur.cache_creation_1h_input_tokens, 0)
        + COALESCE(ur.cache_creation_30m_input_tokens, 0)
        + COALESCE(ur.output_tokens_total, 0)
    ), 0)::bigint AS token_count,
    COALESCE(SUM(COALESCE(ur.uncached_input_tokens, 0)), 0)::bigint AS uncached_input_token_count,
    COALESCE(SUM(COALESCE(ur.cache_read_input_tokens, 0)), 0)::bigint AS cache_read_token_count,
    COALESCE(SUM(
        COALESCE(ur.cache_creation_5m_input_tokens, 0)
        + COALESCE(ur.cache_creation_1h_input_tokens, 0)
        + COALESCE(ur.cache_creation_30m_input_tokens, 0)
    ), 0)::bigint AS cache_creation_token_count,
    COALESCE(SUM(COALESCE(ur.output_tokens_total, 0)), 0)::bigint AS output_token_count,
    COALESCE(SUM(ch.charge_usd), 0)::numeric AS charge_usd,
    COALESCE(SUM(
        COALESCE(ur.uncached_input_tokens, 0)::numeric
        * COALESCE(ps.uncached_input_price, 0) / 1000000
    ), 0)::numeric AS uncached_input_charge_usd,
    COALESCE(SUM(
        GREATEST(
            COALESCE(ur.output_tokens_total, 0) - COALESCE(ur.reasoning_output_tokens, 0),
            0
        )::numeric * COALESCE(ps.output_price, 0) / 1000000
        + COALESCE(ur.reasoning_output_tokens, 0)::numeric
            * COALESCE(ps.reasoning_output_price, ps.output_price, 0) / 1000000
    ), 0)::numeric AS output_charge_usd,
    COALESCE(SUM(
        COALESCE(ur.cache_read_input_tokens, 0)::numeric
        * COALESCE(ps.cache_read_input_price, ps.uncached_input_price, 0) / 1000000
    ), 0)::numeric AS cache_read_charge_usd,
    COALESCE(SUM(
        COALESCE(ur.cache_creation_5m_input_tokens, 0)::numeric
            * COALESCE(ps.cache_creation_5m_input_price, ps.uncached_input_price, 0) / 1000000
        + COALESCE(ur.cache_creation_1h_input_tokens, 0)::numeric
            * COALESCE(ps.cache_creation_1h_input_price, ps.uncached_input_price, 0) / 1000000
        + COALESCE(ur.cache_creation_30m_input_tokens, 0)::numeric
            * COALESCE(ps.cache_creation_30m_input_price, ps.uncached_input_price, 0) / 1000000
    ), 0)::numeric AS cache_creation_charge_usd,
    COALESCE(SUM(
        (
            COALESCE(ur.uncached_input_tokens, 0)::numeric
                * COALESCE(ps.uncached_input_price, 0)
            + GREATEST(
                COALESCE(ur.output_tokens_total, 0) - COALESCE(ur.reasoning_output_tokens, 0),
                0
            )::numeric * COALESCE(ps.output_price, 0)
            + COALESCE(ur.reasoning_output_tokens, 0)::numeric
                * COALESCE(ps.reasoning_output_price, ps.output_price, 0)
            + COALESCE(ur.cache_read_input_tokens, 0)::numeric
                * COALESCE(ps.cache_read_input_price, ps.uncached_input_price, 0)
            + COALESCE(ur.cache_creation_5m_input_tokens, 0)::numeric
                * COALESCE(ps.cache_creation_5m_input_price, ps.uncached_input_price, 0)
            + COALESCE(ur.cache_creation_1h_input_tokens, 0)::numeric
                * COALESCE(ps.cache_creation_1h_input_price, ps.uncached_input_price, 0)
            + COALESCE(ur.cache_creation_30m_input_tokens, 0)::numeric
                * COALESCE(ps.cache_creation_30m_input_price, ps.uncached_input_price, 0)
        ) / 1000000
        / COALESCE(NULLIF(ps.sale_discount, 0), 1)
    ), 0)::numeric AS list_charge_usd,
    COALESCE(SUM(
        (
            COALESCE(ur.cache_read_input_tokens, 0)::numeric
                * (
                    COALESCE(ps.uncached_input_price, 0)
                    - COALESCE(ps.cache_read_input_price, ps.uncached_input_price, 0)
                )
            - (
                COALESCE(ur.cache_creation_5m_input_tokens, 0)::numeric
                    * (
                        COALESCE(ps.cache_creation_5m_input_price, ps.uncached_input_price, 0)
                        - COALESCE(ps.uncached_input_price, 0)
                    )
                + COALESCE(ur.cache_creation_1h_input_tokens, 0)::numeric
                    * (
                        COALESCE(ps.cache_creation_1h_input_price, ps.uncached_input_price, 0)
                        - COALESCE(ps.uncached_input_price, 0)
                    )
                + COALESCE(ur.cache_creation_30m_input_tokens, 0)::numeric
                    * (
                        COALESCE(ps.cache_creation_30m_input_price, ps.uncached_input_price, 0)
                        - COALESCE(ps.uncached_input_price, 0)
                    )
            )
        ) / 1000000
    ), 0)::numeric AS cache_saved_usd
FROM windowed w
JOIN usage_records ur ON ur.request_record_id = w.id
LEFT JOIN price_snapshots ps ON ps.request_record_id = w.id
LEFT JOIN api_keys ak ON ak.id = w.api_key_id
LEFT JOIN models m ON m.model_id = w.requested_model_id
JOIN LATERAL (
    SELECT SUM(
        CASE
            WHEN le.entry_type IN ('debit', 'adjustment_debit') THEN le.amount
            WHEN le.entry_type IN ('credit', 'refund', 'adjustment_credit') THEN -le.amount
            ELSE 0
        END
    ) AS charge_usd
    FROM ledger_entries le
    WHERE le.request_record_id = w.id AND le.currency = 'USD'
) ch ON ch.charge_usd > 0
WHERE (
      COALESCE(cardinality($1::bigint[]), 0) = 0
      OR w.api_key_id = ANY($1::bigint[])
  )
  AND (
      COALESCE(cardinality($2::text[]), 0) = 0
      OR w.requested_model_id = ANY($2::text[])
  )
  AND (
      COALESCE(cardinality($3::text[]), 0) = 0
      OR w.endpoint = ANY($3::text[])
  )
  AND (
      COALESCE(cardinality($4::text[]), 0) = 0
      OR (w.stream AND 'stream' = ANY($4::text[]))
      OR ((NOT w.stream) AND 'sync' = ANY($4::text[]))
  )
  AND (
      $5::text IS NULL
      OR btrim($5::text) = ''
      OR w.requested_model_id ILIKE '%' || btrim($5::text) || '%'
      OR COALESCE(m.display_name, '') ILIKE '%' || btrim($5::text) || '%'
      OR w.request_id ILIKE '%' || btrim($5::text) || '%'
      OR COALESCE(w.client_ip, '') ILIKE '%' || btrim($5::text) || '%'
  )
`

type SummarizeConsoleUsageWindowParams struct {
	ApiKeyIds   []int64
	ModelIds    []string
	Endpoints   []string
	StreamTypes []string
	Q           pgtype.Text
	UserID      int64
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
}

type SummarizeConsoleUsageWindowRow struct {
	RequestCount            int64
	TokenCount              int64
	UncachedInputTokenCount int64
	CacheReadTokenCount     int64
	CacheCreationTokenCount int64
	OutputTokenCount        int64
	ChargeUsd               pgtype.Numeric
	UncachedInputChargeUsd  pgtype.Numeric
	OutputChargeUsd         pgtype.Numeric
	CacheReadChargeUsd      pgtype.Numeric
	CacheCreationChargeUsd  pgtype.Numeric
	ListChargeUsd           pgtype.Numeric
	CacheSavedUsd           pgtype.Numeric
}

// 单个时间窗的用量汇总，供卡片当期/上期各取一次。
// 只算用量与费用，不含耗时分位数：耗时归请求中心，这里不重复付出 percentile 的代价。
func (q *Queries) SummarizeConsoleUsageWindow(ctx context.Context, arg SummarizeConsoleUsageWindowParams) (SummarizeConsoleUsageWindowRow, error) {
	row := q.db.QueryRow(ctx, summarizeConsoleUsageWindow,
		arg.ApiKeyIds,
		arg.ModelIds,
		arg.Endpoints,
		arg.StreamTypes,
		arg.Q,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
	)
	var i SummarizeConsoleUsageWindowRow
	err := row.Scan(
		&i.RequestCount,
		&i.TokenCount,
		&i.UncachedInputTokenCount,
		&i.CacheReadTokenCount,
		&i.CacheCreationTokenCount,
		&i.OutputTokenCount,
		&i.ChargeUsd,
		&i.UncachedInputChargeUsd,
		&i.OutputChargeUsd,
		&i.CacheReadChargeUsd,
		&i.CacheCreationChargeUsd,
		&i.ListChargeUsd,
		&i.CacheSavedUsd,
	)
	return i, err
}
