// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_records.sql

package sqlc

import (
	"context"
)

const createUsageRecord = `-- name: CreateUsageRecord :one
INSERT INTO usage_records (
    request_record_id,
    uncached_input_tokens,
    uncached_input_tokens_state,
    cache_read_input_tokens,
    cache_read_input_tokens_state,
    cache_creation_5m_input_tokens,
    cache_creation_5m_input_tokens_state,
    cache_creation_1h_input_tokens,
    cache_creation_1h_input_tokens_state,
    cache_creation_30m_input_tokens,
    cache_creation_30m_input_tokens_state,
    output_tokens_total,
    output_tokens_total_state,
    reasoning_output_tokens,
    reasoning_output_tokens_state,
    usage_source,
    usage_mapping_version
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING id, request_record_id, uncached_input_tokens, uncached_input_tokens_state, cache_read_input_tokens, cache_read_input_tokens_state, cache_creation_5m_input_tokens, cache_creation_5m_input_tokens_state, cache_creation_1h_input_tokens, cache_creation_1h_input_tokens_state, output_tokens_total, output_tokens_total_state, reasoning_output_tokens, reasoning_output_tokens_state, usage_source, usage_mapping_version, created_at, cache_creation_30m_input_tokens, cache_creation_30m_input_tokens_state
`

type CreateUsageRecordParams struct {
	RequestRecordID                  int64
	UncachedInputTokens              int64
	UncachedInputTokensState         string
	CacheReadInputTokens             int64
	CacheReadInputTokensState        string
	CacheCreation5mInputTokens       int64
	CacheCreation5mInputTokensState  string
	CacheCreation1hInputTokens       int64
	CacheCreation1hInputTokensState  string
	CacheCreation30mInputTokens      int64
	CacheCreation30mInputTokensState string
	OutputTokensTotal                int64
	OutputTokensTotalState           string
	ReasoningOutputTokens            int64
	ReasoningOutputTokensState       string
	UsageSource                      string
	UsageMappingVersion              string
}

// CreateUsageRecord 创建一次请求最终用于计费和审计的协议无关 usage 记录。
func (q *Queries) CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, createUsageRecord,
		arg.RequestRecordID,
		arg.UncachedInputTokens,
		arg.UncachedInputTokensState,
		arg.CacheReadInputTokens,
		arg.CacheReadInputTokensState,
		arg.CacheCreation5mInputTokens,
		arg.CacheCreation5mInputTokensState,
		arg.CacheCreation1hInputTokens,
		arg.CacheCreation1hInputTokensState,
		arg.CacheCreation30mInputTokens,
		arg.CacheCreation30mInputTokensState,
		arg.OutputTokensTotal,
		arg.OutputTokensTotalState,
		arg.ReasoningOutputTokens,
		arg.ReasoningOutputTokensState,
		arg.UsageSource,
		arg.UsageMappingVersion,
	)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.UncachedInputTokens,
		&i.UncachedInputTokensState,
		&i.CacheReadInputTokens,
		&i.CacheReadInputTokensState,
		&i.CacheCreation5mInputTokens,
		&i.CacheCreation5mInputTokensState,
		&i.CacheCreation1hInputTokens,
		&i.CacheCreation1hInputTokensState,
		&i.OutputTokensTotal,
		&i.OutputTokensTotalState,
		&i.ReasoningOutputTokens,
		&i.ReasoningOutputTokensState,
		&i.UsageSource,
		&i.UsageMappingVersion,
		&i.CreatedAt,
		&i.CacheCreation30mInputTokens,
		&i.CacheCreation30mInputTokensState,
	)
	return i, err
}

const getUsageRecordByRequest = `-- name: GetUsageRecordByRequest :one
SELECT id, request_record_id, uncached_input_tokens, uncached_input_tokens_state, cache_read_input_tokens, cache_read_input_tokens_state, cache_creation_5m_input_tokens, cache_creation_5m_input_tokens_state, cache_creation_1h_input_tokens, cache_creation_1h_input_tokens_state, output_tokens_total, output_tokens_total_state, reasoning_output_tokens, reasoning_output_tokens_state, usage_source, usage_mapping_version, created_at, cache_creation_30m_input_tokens, cache_creation_30m_input_tokens_state
FROM usage_records
WHERE request_record_id = $1
`

// GetUsageRecordByRequest 按请求 ID 读取协议无关 usage 记录。
func (q *Queries) GetUsageRecordByRequest(ctx context.Context, requestRecordID int64) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, getUsageRecordByRequest, requestRecordID)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.UncachedInputTokens,
		&i.UncachedInputTokensState,
		&i.CacheReadInputTokens,
		&i.CacheReadInputTokensState,
		&i.CacheCreation5mInputTokens,
		&i.CacheCreation5mInputTokensState,
		&i.CacheCreation1hInputTokens,
		&i.CacheCreation1hInputTokensState,
		&i.OutputTokensTotal,
		&i.OutputTokensTotalState,
		&i.ReasoningOutputTokens,
		&i.ReasoningOutputTokensState,
		&i.UsageSource,
		&i.UsageMappingVersion,
		&i.CreatedAt,
		&i.CacheCreation30mInputTokens,
		&i.CacheCreation30mInputTokensState,
	)
	return i, err
}
