// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConsoleLedgerEntries = `-- name: CountConsoleLedgerEntries :one
SELECT COUNT(*) AS total
FROM ledger_entries
WHERE user_id = $1
  AND currency = $2
  AND (cardinality($3::text[]) = 0 OR entry_type = ANY ($3::text[]))
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
`

type CountConsoleLedgerEntriesParams struct {
	UserID     int64
	Currency   string
	EntryTypes []string
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

// CountConsoleLedgerEntries 返回与 ListConsoleLedgerEntries 相同过滤条件下的总条数。
// 供 offset 超出末页导致列表为空、拿不到窗口计数时兜底。
func (q *Queries) CountConsoleLedgerEntries(ctx context.Context, arg CountConsoleLedgerEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsoleLedgerEntries,
		arg.UserID,
		arg.Currency,
		arg.EntryTypes,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listConsoleLedgerEntries = `-- name: ListConsoleLedgerEntries :many
SELECT
    id,
    entry_type,
    amount,
    currency,
    balance_after,
    request_record_id,
    reason,
    created_at,
    COUNT(*) OVER () AS total_count
FROM ledger_entries
WHERE user_id = $1
  AND currency = $2
  AND (cardinality($3::text[]) = 0 OR entry_type = ANY ($3::text[]))
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type ListConsoleLedgerEntriesParams struct {
	UserID     int64
	Currency   string
	EntryTypes []string
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

type ListConsoleLedgerEntriesRow struct {
	ID              int64
	EntryType       string
	Amount          pgtype.Numeric
	Currency        string
	BalanceAfter    pgtype.Numeric
	RequestRecordID pgtype.Int8
	Reason          string
	CreatedAt       pgtype.Timestamptz
	TotalCount      int64
}

// ListConsoleLedgerEntries 按当前用户分页倒序列出钱包流水。
// user_id 必填（调用方只能传会话主体），entry_type / 时间为可选过滤；
// total_count 用窗口函数随行带出，省一次独立 COUNT 往返。
func (q *Queries) ListConsoleLedgerEntries(ctx context.Context, arg ListConsoleLedgerEntriesParams) ([]ListConsoleLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listConsoleLedgerEntries,
		arg.UserID,
		arg.Currency,
		arg.EntryTypes,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsoleLedgerEntriesRow
	for rows.Next() {
		var i ListConsoleLedgerEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.BalanceAfter,
			&i.RequestRecordID,
			&i.Reason,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
