// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: website_stats.sql

package sqlc

import (
	"context"
)

const minWebsiteFirstTokenMs = `-- name: MinWebsiteFirstTokenMs :one
SELECT COALESCE(MIN(EXTRACT(EPOCH FROM (gateway_first_token_at - started_at)) * 1000), 0)::float8 AS min_first_token_ms
FROM request_records
WHERE stream = TRUE
  AND status = 'succeeded'
  AND gateway_first_token_at IS NOT NULL
  AND started_at IS NOT NULL
  AND gateway_first_token_at > started_at
`

// 营销首页「最快首字」：客户侧 TTFT = gateway_first_token_at − started_at（毫秒），
// 与 console 请求明细 first_token_ms 同口径。只统计真正吐出过首 token 的成功流式请求；
// 非正数样本排除（时钟回拨 / 未观测）。无样本时返回 0，由 HTTP 层转成 null。
func (q *Queries) MinWebsiteFirstTokenMs(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, minWebsiteFirstTokenMs)
	var min_first_token_ms float64
	err := row.Scan(&min_first_token_ms)
	return min_first_token_ms, err
}
