// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaHealthCheck struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}
