// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_health_checks.sql

package sqlc

import (
	"context"
)

const createSchemaHealthCheck = `-- name: CreateSchemaHealthCheck :one
INSERT INTO schema_health_checks (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateSchemaHealthCheck(ctx context.Context, name string) (SchemaHealthCheck, error) {
	row := q.db.QueryRow(ctx, createSchemaHealthCheck, name)
	var i SchemaHealthCheck
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSchemaHealthCheckByName = `-- name: GetSchemaHealthCheckByName :one
SELECT id, name, created_at
FROM schema_health_checks
WHERE name = $1
`

func (q *Queries) GetSchemaHealthCheckByName(ctx context.Context, name string) (SchemaHealthCheck, error) {
	row := q.db.QueryRow(ctx, getSchemaHealthCheckByName, name)
	var i SchemaHealthCheck
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
